### ISSUE TITLE
incorrect red value shown in chrome picker when adjusting alpha

### ISSUE THREAD

**Issue by adamlounds** [casesandberg/react-color#10]
on the chrome picker (demo on http://casesandberg.github.io/react-color/#examples ), choose a colour by clicking on the gradient area. Ensure the hex value is shown, not RGBA or HSLA. Click into the hex display area so that the textbox has focus. Now drag the alpha slider - the view switches to RGBA but the R component shows the hex value and keeps the focus highlight border.

Tested on chrome canary (46.0.2485.0 canary (64-bit)) and webkit nightly (Version 8.0.8 (10600.8.9, r188509))

<img width="597" alt="screenshot 2015-08-17 17 45 02" src="https://cloud.githubusercontent.com/assets/1048527/9310476/cea56f52-4507-11e5-9b68-0f6f0e70f37e.png">

**Comment by casesandberg** [comment]
Thanks for catching this, this has been fixed in `1.0.5`!
