### ISSUE TITLE
Uncaught Invariant Violation: addComponentAsRefTo(...):

### ISSUE THREAD

**Issue by widirizki** [casesandberg/react-color#101]
After installation, I got this following error:

> Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

What's that mean? What's wrong with my installed package before?

**Comment by casesandberg** [comment]
Are you setting a ref on the component?

**Comment by widirizki** [comment]
@casesandberg No, I don't set a ref at all in my component. Anything wrong with my react? I use react version 0.14.7. Should I provide another info for you? Thanks.

**Comment by Mokto** [comment]
I have this issue as well.

Thanks !

**Comment by amalahussein** [comment]
Likewise.

**Comment by amalahussein** [comment]
My issue was actually unrelated..so nevermind, :-)

**Comment by actionnick** [comment]
In your project directory...

`rm -rf node_modules && npm install`

Brute force but this works. This is caused by `react-color` loading up a different _copy_ of react when bundling. You can check for multiple versions of React by doing `npm ls | grep react`. 

[More Info](https://gist.github.com/jimfb/4faa6cbfb1ef476bd105)

**Comment by Mokto** [comment]
Thanks @actionnick it resolved the issue !

**Comment by MichaelTaylor3D** [comment]
I get this issue, it seems that react color picker installs react in the node modules, not sure why since its set as a peer dependancy. Deleting the react folder in the color pickers node_modules folder seems to work, however, it breaks jenkins since it reinstalls the modules on every build.

**Comment by hyunchulkwak** [comment]
Thanks @MichaelTaylor3D 

I added postinstall scripts on package.json to workaround the issue for now.

```
"scripts": {
  "postinstall": "rimraf node_modules/react-color/node_modules/react"
}
```

**Comment by jjyang-ami** [comment]
@hyunchulkwak, thanks for the workaround but I still get errors of peer dependency when I install  with nested npm modules that is more than two levels.

Finally I found another solution for webpack.
Just add an alias path of `react` to `path.resolve('./node_modules/react')` to use common react for all npm modules required by webpack.

Hope this helps~

Reference: http://stackoverflow.com/questions/31169760/how-to-avoid-react-loading-twice-with-webpack-when-developing

**Comment by mjj2000** [comment]
@hyunchulkwak, thanks for the workaround but I still get errors of peer dependency when I install  with nested npm modules that is more than two levels.

Finally I found another solution for webpack.
Just add an alias path of `react` to `path.resolve('./node_modules/react')` to use common react for all npm modules required by webpack.

Hope this helps~

Reference: http://stackoverflow.com/questions/31169760/how-to-avoid-react-loading-twice-with-webpack-when-developing
