### ISSUE TITLE
How do we pass in custom colors to swatches color picker?

### ISSUE THREAD

**Issue by kevinchiu** [casesandberg/react-color#104]
How do we pass in custom colors to the swatches picker?

**Comment by casesandberg** [comment]
You can pass an array of arrays on the color prop!

See here how its done for the default props: https://github.com/casesandberg/react-color/blob/master/src/components/swatches/Swatches.js#L76

**Comment by amalahussein** [comment]
@casesandberg great library! Question on how we should over ride these defaults if we only have access to the parent component: ColorPicker? Or do you recommend, just pulling in the Swatches component directly?

**Comment by mjsarfatti** [comment]
If you use, for example, SketchPicker, you can pass an array of colors as **presetColors** as such:

`<SketchPicker presetColors={ ['#333333', '#666666', '#999999'] } />`

See here: https://github.com/casesandberg/react-color/blob/master/src/components/sketched/Sketch.js
