### ISSUE TITLE
2.0.0 breaks custom prop

### ISSUE THREAD

**Issue by fixpunkt** [casesandberg/react-color#106]
Hi there,

I've just tried to upgrade to 2.0.0. This caused my custom color picker component to break. I've taken a look inside the doc directory and wrapped my color picker with the CustomPicker HOC, but this didn't help either.

Can you give a complete description on how this feature has changed?

Cheers,

Jannik

**Comment by casesandberg** [comment]
I'm sorry to hear that. Could you paste the code for your component?

This is what it looks like internally on the other pickers: https://github.com/casesandberg/react-color/blob/master/src/components/material/Material.js

**Comment by fixpunkt** [comment]
The component that works witrh 1.3.0 looks like this:

`import React, {Component, PropTypes} from 'react'
import ColorPicker from 'react-color'

import {Hue, Saturation} from 'react-color/lib/components/common'

function Pointer() {
  return <div className="pointer"></div>
}

class SidebarColorPickerCustom extends Component {
  render() {
    return (
      <div className="sidebar-color-picker">
        <div className="saturation">
          <Saturation {...this.props}/>
        </div>
        <div className="hue">
          <Hue {...this.props}
            direction={'horizontal'}
            pointer={Pointer}/>
        </div>
      </div>
    )
  }
}

export default function SidebarColorPicker({id, color, onChangeComplete}) {
  return (<ColorPicker id={id}
                       custom={SidebarColorPickerCustom}
                       type="sketch"
                       color={color}
                       onChangeComplete={onChangeComplete}/>)
}

SidebarColorPicker.propTypes = {
  id: PropTypes.string.isRequired,
  color: PropTypes.string,
  onChangeComplete: PropTypes.func.isRequired
}
`

How do I have to change the code to make it work with 2.0.0?

**Comment by casesandberg** [comment]
Ah, apologies, the docs didnt get updated when I pushed 2.0.0 

Just wrap the export with `CustomPicker`, you can read about it here: http://casesandberg.github.io/react-color/#create-parent
