### ISSUE TITLE
'more examples' does not work properly

### ISSUE THREAD

**Issue by jma7889** [casesandberg/react-color#113]
I tried both examples in 'more examples'. I got the same issue, the color picker dialog is always displayed even display is set to false. I didn't change any code. 

And for the 2nd example, colored button is not shown, but the dialog is always shown.

    `<MyColorPicker />` 

I rename the example class and call the component as above.

**Comment by sosaucily** [comment]
Somehow many of the examples are documented as using features that don't actually exist.  Not sure what's up with that...

See here for an example of using the component as the example shows it:

https://github.com/casesandberg/react-color/blob/master/examples/Sketch.js

**Comment by casesandberg** [comment]
Sorry, the documentation site didnt get updated properly. To use a picker you have to deconstruct the import:

```
import { ChromePicker } from 'react-color'
```

**Comment by casesandberg** [comment]
Also check the updated docs if you are still having trouble: http://casesandberg.github.io/react-color/
