### ISSUE TITLE
'None' option

### ISSUE THREAD

**Issue by ewaldman** [casesandberg/react-color#115]
Hi.
I don't see a No Color option in the ColorPicker. In MS Word when you go to the background color menu, they give a choice of No Color. this is useful when user chose a color and now wants to remove the color. It would be nice if this product could support similar functionality for the Color Picker.

**Comment by casesandberg** [comment]
Which picker would you like a `none` option for? Currently these were all copies of existing pickers which do not have that functionality.

**Comment by Huxpro** [comment]
@casesandberg 
We do need a official or recommended approach to reset color to default.

@ewaldman 
I currently tried to do it with my own by `this.setState({ color: undefined })` and it's works fine for me. But It's weird that if you do `this.setState({ color: null })` you would get a `Cannot read property 'hex' of null` exception when instantiating ColorPicker next time.

**Comment by hszcg** [comment]
@casesandberg I would like to support `none` option in Sketch Picker. Could you please help that?

**Comment by casesandberg** [comment]
Would it make sense to be able to pass in 'transparent' with the props for
this? Then I can make the actual swatch look right with that.

**Comment by hszcg** [comment]
@casesandberg I think it would be good enough.

Taking the `SketchExample` for instance, adding a `none` btn would be perfect. (example as shown below, the `none` btn on the bottom-right)

![screen shot 2017-05-17 at 12 31 39 pm](https://cloud.githubusercontent.com/assets/1321488/26138594/e6a124ec-3afc-11e7-92f3-a27af516bd00.png)

**Comment by hszcg** [comment]
oh, the example pic is not `Sketch`, it's more likely to be `Photoshop`

Anyway, adding `none` btn in either one would be great!
