### ISSUE TITLE
Cannot resolve module 'react-material-design'

### ISSUE THREAD

**Issue by asaldivar** [casesandberg/react-color#12]
First, thanks for the module! When I require react-color into one of my components and run webpack I get the following error: 

```
ERROR in ./~/react-color/src/components/swatches/Swatches.jsx
Module not found: Error: Cannot resolve module 'react-material-design' in /Users/asaldivar/fuisz/studio/node_modules/react-color/src/components/swatches
 @ ./~/react-color/src/components/swatches/Swatches.jsx 16:15-47

ERROR in ./~/react-color/src/components/material/Material.jsx
Module not found: Error: Cannot resolve module 'react-material-design' in /Users/asaldivar/fuisz/studio/node_modules/react-color/src/components/material
 @ ./~/react-color/src/components/material/Material.jsx 15:15-47

ERROR in ./~/react-color/src/components/compact/Compact.jsx
Module not found: Error: Cannot resolve module 'react-material-design' in /Users/asaldivar/fuisz/studio/node_modules/react-color/src/components/compact
 @ ./~/react-color/src/components/compact/Compact.jsx 17:15-47
```

I could not find a react-material-design module. Would you please point me in the right direction?

**Comment by MFIMichael** [comment]
This is where I've gotten to in #9 -- the module is included with react-color, in the modules folder, but isn't resolving.

**Comment by casesandberg** [comment]
@asaldivar My mistake, I messed up with some require paths. Update via npm to 1.0.2 and that should fix all the issues!

**Comment by asaldivar** [comment]
Hmm, updated to ^1.0.2 but getting this now:
```
ERROR in ./~/react-color/modules/react-material-design/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./src/components/Raised in /Users/asaldivar/fuisz/studio/node_modules/react-color/modules/react-material-design
 @ ./~/react-color/modules/react-material-design/index.js 4:10-44

ERROR in ./~/react-color/modules/react-material-design/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./src/components/Tile in /Users/asaldivar/fuisz/studio/node_modules/react-color/modules/react-material-design
 @ ./~/react-color/modules/react-material-design/index.js 5:8-40

ERROR in ./~/react-color/modules/react-material-design/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./src/components/Tabs in /Users/asaldivar/fuisz/studio/node_modules/react-color/modules/react-material-design
 @ ./~/react-color/modules/react-material-design/index.js 7:8-40
```

I also, removed my node_modules and re-ran `npm i` but still getting this latest error.

I added the `.jsx` extension to the `./src/components/Raised`, `./src/components/Tile` and `./src/components/Tabs` paths in /react-material-design/index.js as well as to `./Tab` and `./Link` in /react-material-design/src/components/Tabs.jsx and got my webpack to successfully build all modules, but now i'm getting this error in the browser:

```
Uncaught TypeError: Cannot set property 'HighchartsAdapter' of undefined
```

**Comment by casesandberg** [comment]
Thanks for hunting this down @asaldivar, I am going to go through and fix these like you suggested. 

I do not know of `HighchartsAdapter`, is that something you are using in your project?

**Comment by asaldivar** [comment]
Still working on this. I added:

```
  resolve: {
    extensions: ["", ".js", ".jsx"] 
  },
```
to get around adding the extensions. Yes, HighchartsAdapter is something on my end. I'm going to try and rule out my stuff and let you know. Thanks!

**Comment by casesandberg** [comment]
^1.0.3 - fixes all of the paths, I triple checked it: https://github.com/casesandberg/react-color/commit/28891dbc2d0fdedd84b2d6bc668c044a6f9d87ef

Thanks so much for working through this with me, I have gotten into a lot of trouble with all this Webpack magic.

**Comment by asaldivar** [comment]
Ahh, so the error,
```
Uncaught TypeError: Cannot set property 'HighchartsAdapter' of undefined
```
was caused because react-highcarts precompiles before publish so when I removed `exclude: /node_modules/` from my loader (to get react-color to work) react-highcharts wouldn't work.  Is it possible for you to have react-color precompile before publish as well? Otherwise I don't believe I'll be able to use both components in my app because of the webpack configuration.

**Comment by casesandberg** [comment]
Ah! Just pushed `react-color@1.0.4` which should allow you to put back in that `exclude: /node_modules/`!

I ended up excluding `[/node_modules/, /modules/]` for my webpack and was able to go through and create ES5 versions of all of the things in my modules folder. This should allows you to put back in that exclude as everything but the documentation is now ES5 by default!

**Comment by MFIMichael** [comment]
Beautiful. :) Working here.

**Comment by asaldivar** [comment]
Awesome! It's working for me too! Thanks so much for solving this issue!
