### ISSUE TITLE
Suggestions on improving rendering perf

### ISSUE THREAD

**Issue by roman01la** [casesandberg/react-color#13]
Hi! As I pointed out on Twitter: “moving picker point doesn't feel smooth”, I would like to share with you some findings (sorry, I have no time to prepare a PR).

1. A huge perf loss is [here](https://github.com/casesandberg/react-color/blob/master/src/components/common/Saturation.jsx#L58-L61). That code means that on every mouse move it does query the DOM for some layout info, which is expensive operation. It's possible to reduce the frequency of that operations by caching those values within `componentDidMount` call and assigning the function which will update those props on `container` element resize (if it's resizeable of course) and window scroll, since these are cases when that props can change.

2. Moving the picker can be done with CSS Transforms, rather than [`top/left`](https://github.com/casesandberg/react-color/blob/master/src/components/common/Saturation.jsx#L40-L41) props. In addition to this `will-change: transform;` CSS rule can be added to let browser know and thus optimize frequently changing `transform` prop on that element.

3. Not actually related, but I didn't notice a single `shouldComponentUpdate` check :)

*Here's a short clip with the resulting perf I got after applying all of the suggestions from above: [see](https://www.dropbox.com/s/omqfvjchd58d6b8/Untitled.mov?dl=0). I know the picker is out of position :)*

**Comment by tjerkw** [comment]
I think the main reason of the performance penalty is the fact that when moving the picker:
https://github.com/casesandberg/react-color/blob/master/src/components/common/Saturation.jsx#L82

A react-render cycle is started:
https://github.com/casesandberg/react-color/blob/master/src/components/common/Saturation.jsx#L76

Which is basically a diff against two trees, which then results in a set of dom operations.
While diffing is relatively quick, it is not suited for realtime continuous changes, at least not if you want to have a butter smooth experience.

So i would recommend updating the dom directly, however it defeats the purpose of using react. So i would recommend dropping react (at least for the realtime updates).

React is not well suited for realtime components, at least not if you want it to work on a laptop that doesn't have a quad core processor.

**Comment by roman01la** [comment]
I'm somewhat agree, it's hard and probably impossible to get 60 FPS on such kind of components made with React. But, please, [check first the video I've dropped in the comment above](https://www.dropbox.com/s/omqfvjchd58d6b8/Untitled.mov?dl=0). It shows clearly that solving major perf issues listed above does improve experience a lot. Not 60 FPS actually, just 35-38, but I believe some improvements can be done on [color manipulation code](https://github.com/casesandberg/react-color/blob/master/src/components/Color.jsx#L18-L31) which seems does a bunch of computations inside of `tinycolor2` module (try to replace it with a couple of lighter functions). Also `shouldComponentUpdate` is what you need to prevent diffing.

**Comment by tjerkw** [comment]
Ah indeed, that might be sufficient. However, while i think React is cool, and helps a lot. We should be aware of where not to use it... Its actually quite surprising the components is still rather fast.

**Comment by roman01la** [comment]
Yeah, I'm totally ok to have a bunch of fast atomic and easy pluggable components made in vanilla JS. Do not over**react** :D

**Comment by roman01la** [comment]
[Here's a bunch of color conversion formulas](http://www.easyrgb.com/index.php?X=MATH), might be interesting to take a look at.

**Comment by jedwards1211** [comment]
The speed does get annoying to me because it's the #1 overhyped feature of React
