### ISSUE TITLE
Error: Minified exception occurred

### ISSUE THREAD

**Issue by gidili** [casesandberg/react-color#131]
First of all thanks for this awesome component!

I am simply importing from sources (added bundle.js to my project and then using require to import ColorPicker as in the examples) and I get this minified exception. 

**Simple question**: where/how do I get the non-minified version to see the actual error?

I am using react-color 1.3.0 and I am on React v0.14.8

**Comment by gidili** [comment]
Or maybe I should've just asked how to use the color picker from sources :)

**Comment by gidili** [comment]
I rebuilt it locally with browserify and now I can see the error:

`Super expression must be either null or a function, not undefined.`

![screenshot 2016-04-15 12 03 02](https://cloud.githubusercontent.com/assets/68134/14559642/27711114-0302-11e6-885d-1e0810054879.png)

Again all I am doing is a require for the bundle file, any pointers appreciated.

**Comment by casesandberg** [comment]
Ah, the bundle file is for the documentation website, not for the color picker. Just use 

```
var ChromePicker = require('react-color').ChromePicker
// or
import { ChromePicker } from 'react-color'
```
