### ISSUE TITLE
Lodash leaked as a global

### ISSUE THREAD

**Issue by mattijauhiainen** [casesandberg/react-color#134]
When I import the 'react-color' to my project it seems to assign lodash to the `_` global. This is unfortunate because I already have `_` defined and it gets overwritten and this breaks the app.

**Comment by png262** [comment]
i had the same issue, had to go into all of my existing files that used lodash and do a specific import from 'lodash' module to keep old lodash for rest of app

**Comment by jacobrask** [comment]
This is a "feature" of lodash, see https://github.com/lodash/lodash/issues/2251.

**Comment by jacobrask** [comment]
This would be fixed by only importing the methods from lodash that are actually used, so `import isString from 'lodash.isstring'` or `import isString from 'lodash/isString'` rather than `import _ from 'lodash'`.
