### ISSUE TITLE
Slider not hiding and type being ignored

### ISSUE THREAD

**Issue by chinshr** [casesandberg/react-color#136]
I am using the plane vanilla example on a material-ui page and the color picker never hides even the `display` property is set to false. Also `type` is begin ignored. Basically, I am always showing the page like this:

![screen shot 2016-04-21 at 1 01 54 pm](https://cloud.githubusercontent.com/assets/29537/14722718/c10d00b2-07c1-11e6-9251-d7522cfadaba.png)

```javascript
import React from 'react'
import ColorPicker from 'react-color';

export default class About extends React.Component {

  constructor() {
    super();
    this.state = {
      displayColorPicker: false,
    };
    this.handleClick = this.handleClick.bind(this);
  }

  handleClick() {
    this.setState({ displayColorPicker: !this.state.displayColorPicker });
  }

  render() {
    return (
      <div className="col-md-offset-2 col-md-10">
        <button onClick={ this.handleClick }>Pick Color</button>
        <ColorPicker display={ this.state.displayColorPicker } type="sketch" />
      </div>
    )
  }

}

```

**Comment by LPayyapilli** [comment]
This is happening for me as well. Its using the latest react-color version and the latest react version.

**Comment by kennedy0527** [comment]
same problem here with react 0.14.8 and react-color 2.0.0

```javascript
import ColorPicker from 'react-color';

<ColorPicker type="sketch" />
```
if import ColorPicker, type property will not work properly

ColorPicker will only show Chrome style (default?)

so I just follow the README example 
```javascript
import { SketchPicker } from 'react-color';

<SketchPicker />
```
it will show SketchPicker correctly 

but display property is still not working !!
picker is always visible even I set display property to false directly

**Comment by chinshr** [comment]
I have solved it using this

```jsx
    ...
    return (
      <div>
        <Paper style={ this.classes().default.swatch } onClick={ this.handleClick } />
        {this.state.displayColorPicker ? <div style={ this.classes().default.popover }>
          <div style={ this.classes().default.cover } onClick={ this.handleClose } />
          <SketchPicker color={ this.state.color } onChange={ this.handleChange } />
        </div> : null}
      </div>
    );
    ...
```

**Comment by casesandberg** [comment]
Sorry for the confusion. Seems when I updated the package to `2.0.0` I didnt push the new documentation to the github pages site. To answer your question, `react-color` no longer handles showing or hiding the color picker. Either use state and an onClick event as illustrated above or use another component that does showing and hiding!
