### ISSUE TITLE
Not working in prod with webpack

### ISSUE THREAD

**Issue by Mokto** [casesandberg/react-color#137]
Hi,

I get a weird issue.

Everything works fine in dev mode.
But when I push my minified code to production I get this :

`Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.`

Also my color picker is empty and when I try to click on the color picker I get this : `Uncaught TypeError: Cannot read property 'clientWidth' of undefined`

![capture d ecran 2016-04-28 a 10 28 23](https://cloud.githubusercontent.com/assets/5103928/14879861/f6288d92-0d2b-11e6-80a1-6dd9e24dd039.png)

Any idea ? 

Thanks for this great plugin !

**Comment by casesandberg** [comment]
Hm. Can you try upgrading to `2.1.0`. That color picker looks really odd though. How are you using it in your code?

**Comment by Mokto** [comment]
I think I understood the issue.

Package.json has react-addons-shallow-compare 15.0.2 as dependency and in my project I use react 0.14 so the error thrown is [Uncaught Invariant Violation: addComponentAsRefTo(...)](https://github.com/casesandberg/react-color/issues/101).
