### ISSUE TITLE
Component keeps resetting?

### ISSUE THREAD

**Issue by polarathene** [casesandberg/react-color#142]
I was using the example code with the toggle display button. Apart from the fact that toggling display doesn't actually work(visible never gets used), whenever I used the button though it was resetting the state of the picker. This appears to be due to `componentWillReceiveProps(nextProps: any)`.

Disabling that method allowed me to change the state of my component that the colour picker was in (I was just changing the background colour on colour selection, this also used to reset the picker state). I'm not sure if this is my fault or if the method is not doing what it should, in order to use it I ended up updating outdated dependencies.

I'm also curious why `merge` is being used? I noticed spread operators are being used elsewhere, why not use them for merging state objects?

**Comment by casesandberg** [comment]
Sorry about that, the documentation website was not updated with the new docs for `2.0.0`, please try the new example code there if you are still having issues. 

Also, what do you mean by use the spread operators for merging?

**Comment by polarathene** [comment]
@casesandberg I have seen lines like the [following](https://github.com/casesandberg/react-color/blob/bfb3d0de71a44ab9c3135755ac5f4344bfebab5e/src/components/common/ColorWrap.js#L17):

```JS
this.state = merge(color.toState(props.color, 0), {
        visible: props.display,
})
```

`color.toState()` returns an object that you seem to be merging the `visible` prop with. I think you could just do:

```JS
this.state = { ...color.toState(props.color, 0), visible: props.display }
```

Is there some other benefit of `merge` over the ES6 spread operator that you're using? I'll try the updated package & docs out and get back to you :)
