### ISSUE TITLE
Give Alpha component a direction option

### ISSUE THREAD

**Issue by jakedeichert** [casesandberg/react-color#155]
The Hue component allows a direction to be set, either horizontal or vertical.

It would be nice for the Alpha component to also have this ability.

I don't mind digging into this and preparing a PR, probably next week at the earliest.

Thoughts?

**Comment by casesandberg** [comment]
I would appreciate it 🎩

**Comment by jakedeichert** [comment]
Awesome. I'll be able to look into this in 1 or 2 weeks 👍

**Comment by casesandberg** [comment]
@jakedeichert Have you had a chance to look into this?

**Comment by jakedeichert** [comment]
@casesandberg I actually got sidetracked a few months ago and unfortunately didn't find time to look into this further.

I'd still like to contribute though! Thanks for reminding me about this. Wednesday/Thursday/Friday I think I have time after work to start digging into this.

How about I comment back here later this week to let you know if I start working on it?

**Comment by maximzah** [comment]
@jakedeichert @casesandberg  Did you engaged in the direction for the component alpha? Because I need this functionality urgently. 
If I do it myself, is there enough to move and rewrite code similar to helper "Hue"?
https://github.com/casesandberg/react-color/blob/master/src/helpers/hue.js **->** https://github.com/casesandberg/react-color/blob/master/src/helpers/alpha.js

**Comment by jakedeichert** [comment]
@maximzah I did not begin this yet. If you want, you can do this since you need it done fast. Not sure what the release cycle is like regarding how fast it could get pushed out.

Otherwise, I'll checkout the code tomorrow and take a look. I just started a new job this week :) pretty hectic but I think I have time.

**Comment by casesandberg** [comment]
This is live in `react-color@2.8.0`

```
<AlphaPicker direction="vertical" />
// or
<Alpha direction="vertical" />
```

**Comment by jakedeichert** [comment]
Well, me experimenting was interesting! I barely scratched the surface anyway. Great job @casesandberg 👍 

<img width="1034" alt="screen shot 2016-11-19 at 9 00 00 pm" src="https://cloud.githubusercontent.com/assets/1631044/20459748/2facb8f2-ae9b-11e6-8603-2f90a9df1ab0.png">
