### ISSUE TITLE
peerDependencies Issue in React 0.14

### ISSUE THREAD

**Issue by elsbree** [casesandberg/react-color#166]
The `react-addons-shallow-compare` dependency version specified at `^15.0.0` [here](https://github.com/casesandberg/react-color/blob/master/package.json#L43) isn't compatible with React v0.14, since it has React v15 as a peerDependency. Using this library with React v0.14 causes NPM to show a peerDependencies error because of this.

 If I change that line to `^15.0.0 || ^0.14.0` I can at least specify `"react-addons-shallow-compare": "^0.14.0"` in my own project's package.json file to prevent that error.

**Comment by acusti** [comment]
Same issues as #137. Also, there’s another PR that fixes it like yours, as well as applying the same version range to `"react-addons-test-utils"`: #154

**Comment by elsbree** [comment]
You're right, thanks! Guess I should have been more thorough in searching through the existing issues. I'll close this issue since it's a duplicate.
