### ISSUE TITLE
unsafe read from event 'touches' property

### ISSUE THREAD

**Issue by KurganskySergey** [casesandberg/react-color#175]
Saturation.js handleChange method line:
var left = (e.pageX || e.touches[0].pageX) - (container.getBoundingClientRect().left + window.pageXOffset);

e.pageX === 0
e.touches is undefined.

here goes uncaught exception "Cannot read property '0' of undefined"

steps to reproduce: 
- open color-picker.
- move cursor to the very top-left and the outside of browser's window
- move cursor up and down outside of browser window

**Comment by casesandberg** [comment]
I can't seem to reproduce this. What color picker are you having this problem with?

**Comment by skurgansky-sugarcrm** [comment]
1.3.6

**Comment by casesandberg** [comment]
Can you try updating to the latest and see if you still have the same problem?

**Comment by skurgansky-sugarcrm** [comment]
no issue on latest version. thnks
