### ISSUE TITLE
Leftover console.log

### ISSUE THREAD

**Issue by mdoelker** [casesandberg/react-color#176]
There is a leftover log statement in the render function of chrome/Chrome.js. As one can imagine, this spams the console quite a bit :D

**Comment by cpsubrian** [comment]
#177

**Comment by isTravis** [comment]
This issue should be reopened given that the leftover console.log has popped up again.

See comments on #174

**Comment by stoplion** [comment]
+1

**Comment by isTravis** [comment]
Thanks so much for the fix on this. Any chance of a fresh NPM version so we can install?
