### ISSUE TITLE
Extending ReactCSS.Component   is deprecated in ReactCSS 1.0.0

### ISSUE THREAD

**Issue by scottbarrow** [casesandberg/react-color#178]
console warning
Extending ReactCSS.Component
  is deprecated in ReactCSS 1.0.0

**Comment by irealva** [comment]
The mapbox color picker solves this in a neat way. Everything has a classname you can style with a css file: https://github.com/mapbox/react-colorpickr/blob/mb-pages/dist/colorpickr.css

**Comment by casesandberg** [comment]
I am not sure how this is an issue. Would you like this error to be guarded to not show up in development?
