### ISSUE TITLE
Cut a release since removing console.log

### ISSUE THREAD

**Issue by griffinmyers** [casesandberg/react-color#189]
Hello--

Thanks for the great color picker.  I appreciate all your effort building and maintaining it. 

Would it be possible to get a release cut with the `console.log` removed in 011d746c9587e7b0a9d5a11ba133e6b4cf93ad6b?

**Comment by egdelwonk** [comment]
+1

**Comment by casesandberg** [comment]
Sorry about that. New release at `react-color@2.2.1`

**Comment by griffinmyers** [comment]
🙇 thanks @casesandberg!
