### ISSUE TITLE
Add Event as Second Parameter to onChange

### ISSUE THREAD

**Issue by george-norris-salesforce** [casesandberg/react-color#190]
any way for onChange to receive an event?

```
<CompactPicker
    onChange={(color, evt) => {                    
      evt.stopPropagation;                      
      //this does not work
      this.updateColor(color);                      
  }}
color={lessonColor}
/>
```

**Comment by casesandberg** [comment]
Any reason you are stopping the propagation? If you take that line out does it work?

**Comment by doitshareit** [comment]
`evt` is `undefined`, thus accessing `stopPropagation` causes an error.

**Comment by casesandberg** [comment]
You can do this now in `react-color@2.4.3`!

**Comment by rm-rf-etc** [comment]
Using any callback with `onChange` in `SketchPicker` causes the circle to not update for me, and I don't know why. Any clues would be much appreciated.
