### ISSUE TITLE
Recent change breaks npm install

### ISSUE THREAD

**Issue by therealparmesh** [casesandberg/react-color#192]
A recent change after version 2.2.0 has broken my ability to run `npm install` in my project. I'm on node 5.12 with npm 3.10 and I had to restrict the version of react-color to 2.2.0 in order to get a deploy to work. I am skeptical of some recent changes to package.json but I have not taken a closer look.

**Comment by Smudded** [comment]
When I run `npm install` it installs version 2.2.0 despite having 2.2.2 in my package.json. I'm not extremely familiar with npm, but it seems like these issues are probably related.

**Comment by casesandberg** [comment]
Can you update to the latest version and see if this is still an issue?
