### ISSUE TITLE
[Documentation] last example broken

### ISSUE THREAD

**Issue by petermikitsh** [casesandberg/react-color#204]
In the last example in [Section 5](http://casesandberg.github.io/react-color/), attempting to click in any of the text input fields results in the picker closing, rather than selecting the input field.

**Comment by petermikitsh** [comment]
If you make the `popover` and `cover` div's siblings, rather than having `popover` be a parent of `cover`, it fixes the problem.

**Comment by casesandberg** [comment]
Nice! Think you could put this fix in a PR?

**Comment by petermikitsh** [comment]
Sure! It'd be only be fair to contribute since I am using this component in one of my projects. Except a PR in 48-72 hours.
