### ISSUE TITLE
Adding React and React-dom to dependencies is wrong

### ISSUE THREAD

**Issue by darkowic** [casesandberg/react-color#207]
Version: 2.2.4

I gets following error

> invariant.js:39 Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

This is because react-color install it's own react instance in node_modules. It's wrong and react and react-dom should be removed from dependencies (moved to dev dependencies)

**Comment by casesandberg** [comment]
`react` an `react-dom` are peer dependencies: https://github.com/casesandberg/react-color/blob/master/package.json#L46-L47 is there a better way to do this?

**Comment by darkowic** [comment]
I found 
http://stackoverflow.com/a/22004559/5185634
that before npm 3.0 the per dependencies are always installing. In my case I have old npm - 2.4.1 so it install automatically.
In version >3.0 it only raise warning so it should solve my problem.

**Comment by darkowic** [comment]
I confirm that npm > 3.0 solve my problem. It was of course because of two React instances.

**Comment by casesandberg** [comment]
Awesome! Glad to hear it
