### ISSUE TITLE
Gradient picker

### ISSUE THREAD

**Issue by AngeIII** [casesandberg/react-color#210]
Hi everyone! Good job guys. 
I have a question how hard will be implement gradient picker, with color stops.

Like user select first gradient color and end color.

Where I can start and maybe somebody can help me with this?

**Comment by casesandberg** [comment]
I am not sure what you are asking, could you add some more datils? Or maybe a picture?

**Comment by AngeIII** [comment]
Yes sure. I thing about something like this: http://i.stack.imgur.com/YFkzO.jpg

**Comment by casesandberg** [comment]
Hmm, yeah this is definitely outside of the scope of this package.
