### ISSUE TITLE
How to choose black and white from SliderPicker

### ISSUE THREAD

**Issue by sayasajer** [casesandberg/react-color#211]
Hi, 
Is there any way I choose black and white or maybe grey from SliderPicker component.

I want to use this in mobile and the best looking component with limited space with other elements is this SlidePicker.

Thanks.

**Comment by casesandberg** [comment]
Hmm. There is currently no way to do black, white or gray with the SliderPicker because it only changes hue. I wonder if maybe just adding 5 swatches below the 5 color ones that do white to black would make sense?

**Comment by sayasajer** [comment]
From what I see, SwatchesPicker also do not have white to black color.
Can you advice me how to do that manually just to include 5 color from white to black?
I'm afraid that I cannot use other small component like CompactPicker because my space limitation.
