### ISSUE TITLE
Jumpiness in the lower right of Saturation component

### ISSUE THREAD

**Issue by louh** [casesandberg/react-color#216]
As you drag around in the Saturation component, there is a loss of precision in the lower right corner and the pointer becomes jumping around. This is a GIF showing this behavior on the project page's Sketch example, but it is true in any color picker where the Saturation component is also used (e.g. Chrome, Photoshop).

![sep-01-2016 11-13-59](https://cloud.githubusercontent.com/assets/2553268/18172955/aa96f2ca-7035-11e6-9470-39ccb7189e74.gif)

**Comment by casesandberg** [comment]
Ah, good catch! I think that is an error because when I wrote the Saturation component I have the position updating in real time based off the value, instead it should let the client control the position so it will be smooth. I will put this on the TODO list!

**Comment by louh** [comment]
In my own app I've just implemented it this way - I read the initial value from props but subsequent updates are stored in the component state, which makes it a non-pure component, but I'm not noticing any performance jank and makes the picker position behave much more expected.

**Comment by casesandberg** [comment]
🙌 Can you open up a PR with the changes in here and I can look at them and get them merged in?

**Comment by casesandberg** [comment]
This is going to be addressed in the v3 update! Follow along with this issue here: https://github.com/casesandberg/react-color/issues/404
