### ISSUE TITLE
docs website: remove overflow: 'scroll' styles

### ISSUE THREAD

**Issue by louh** [casesandberg/react-color#217]
This is what the docs website looks like on my screen:

![screenshot 2016-09-01 11 24 12](https://cloud.githubusercontent.com/assets/2553268/18173503/d1c0c298-7037-11e6-9a95-16a3e3583952.png)

There are "disabled" scrollbars on each sidebar item. This is a result of `overflow: 'scroll'` being applied to a wrapping `<div>` element on each one, and it doesn't need to be there. Even for the "onChangeComplete" item, which does have a working horizontal scrollbar, it is entirely because the vertical scrollbar itself is taking up space it could be using. When I remove scrollbars, it looks much better (and perhaps as expected):

![screenshot 2016-09-01 11 24 02](https://cloud.githubusercontent.com/assets/2553268/18173563/0ca3b38e-7038-11e6-923d-3626685d06d0.png)

I am not sure how to make this change without affecting the react-material-design library itself.

A further note is the code samples on the right column, which are also displaying these phantom scrollbars. In these cases using `overflow: 'auto'` will work just fine, as the disabled scrollbars will not appear unless they are actually needed.

**Comment by casesandberg** [comment]
Ah! I am on a mac so I never knew this was an issue! Thanks, I will look into it!

**Comment by louh** [comment]
I'm also on a Mac! However in some cases the scroll bars turn on - On my work machine I have "Always show scrollbars" [turned on](https://support.apple.com/kb/PH18803?locale=en_US) and I believe it may always show if you connect a Macbook to an external display.

**Comment by casesandberg** [comment]
Oh cool, I had no idea, so I can recreate this to get it to go away, killer!

**Comment by casesandberg** [comment]
Thanks! This was fixed here: https://github.com/casesandberg/react-color/commit/c90affbc95326d532d19bb06fe9f2058e8cb24fb
