### ISSUE TITLE
Touch drag events don't work 

### ISSUE THREAD

**Issue by arkon** [casesandberg/react-color#22]

**Comment by casesandberg** [comment]
Thanks @arkon, I am going to be fixing this within the next two weeks and will go out in the `1.1.0` release!

**Comment by casesandberg** [comment]
Sorry for the delay, just got these in! https://github.com/casesandberg/react-color/commit/aba3bfd40233b30917aa450cdcefc8c295a1590d

Use them by updating to `1.1.2`

**Comment by arkon** [comment]
Awesome, thanks!
