### ISSUE TITLE
Saturation component pointer

### ISSUE THREAD

**Issue by potapovDim** [casesandberg/react-color#230]
```
  value: function render() {
      var styles = (0, _reactcss2.default)({
        'default': {
          color: {
            absolute: '0px 0px 0px 0px',
            background: 'hsl(' + this.props.hsl.h + ',100%, 50%)',
            borderRadius: this.props.radius
          },
          white: {
            absolute: '0px 0px 0px 0px',
            background: 'linear-gradient(to right, #fff, rgba(255,255,255,0))'
          },
          black: {
            absolute: '0px 0px 0px 0px',
            background: 'linear-gradient(to top, #000, rgba(0,0,0,0))',
            boxShadow: this.props.shadow
          },
          pointer: {
            position: 'absolute',
            top: -(this.props.hsv.v * 100) + 100 + '%', //why *100?
            left: this.props.hsv.s * 100 + '%', //why *100??
            cursor: 'default'
          },
          circle: {
            width: '4px',
            height: '4px',
            boxShadow: '0 0 0 1.5px #fff, inset 0 0 1px 1px rgba(0,0,0,.3),\n            0 0 1px 2px rgba(0,0,0,.4)',
            borderRadius: '50%',
            cursor: 'hand',
            transform: 'translate(-2px, -2px)'
          }
        }
      });
```

saturation back
![screen shot 2016-09-16 at 8 52 38 am](https://cloud.githubusercontent.com/assets/19333856/18576522/ef1a42c4-7bea-11e6-8b94-c1dc37a98007.png)
and i push it in state , when i give this data to saturation my pointer go to top right corner of window

**Comment by casesandberg** [comment]
I am not sure what you are asking, can you provide some more details?

**Comment by potapovDim** [comment]
@casesandberg when i move mouse saturation back me object (pic ) i write it to state , and saturation need props "hsv" what in this part of code   

```
pointer: {
            position: 'absolute',
            top: -(this.props.hsv.v * 100) + 100 + '%', //why *100?
            left: this.props.hsv.s * 100 + '%', //why *100??
            cursor: 'default'
          },
```
give pointer position top and left , top: -(this.props.hsv.v * 100) + 100 + '%' and left: this.props.hsv.s * 100 + '%',
when this.props.hsv.v * 100 ,this.props.hsv.s * 100 u do it pointer go to the top left corner of window

**Comment by KonstantinSimeonov** [comment]
This issue is most probably cause because the Saturation component propagates a HSV value, which is then converted to RGB with tinycolor in `toState` (helpers/color.js). Then this RGB value is used to compute the new HSV which is then passed to the Saturation component. This conversion, while convenient, causes losses of precision in some cases.

**Comment by DeanHristov** [comment]
Hi, guys. 

I have a question about "Saturation" component. I trying to create custom colour picker with "Saturation" where I want to divide "Saturation" and "lightness" into two differences views? 
Currently, they are together in "Saturation"

**Comment by casesandberg** [comment]
I am going to close this as the original question was answered. @DeanHristov Version 3.0.0 is being actively developed and there will be standalone components that are saturation and lightness and the current `<Saturation />` component is being renamed to spectrum. I opened up an issue to keep track of it: https://github.com/casesandberg/react-color/issues/483
