### ISSUE TITLE
Color values do not populate

### ISSUE THREAD

**Issue by mattvv** [casesandberg/react-color#25]
<img width="240" alt="screenshot 2015-08-18 11 20 12" src="https://cloud.githubusercontent.com/assets/117194/9335700/267bda34-459b-11e5-9c6d-897de0d60bca.png">

On my example, RGB and Hex codes do not populate by default, or when picking in the color picker. 
Clicking on the value and then typing something will display the code.

I've tried this using chrome, sketch and compact examples.

**Comment by casesandberg** [comment]
I cant seem to reproduce this. Can you upgrade to the latest version and let me know if you are having the same issue?
