### ISSUE TITLE
Export Checkerboard component

### ISSUE THREAD

**Issue by elliotbonneville** [casesandberg/react-color#250]
It would be super handy if you could export the Checkerboard component as well. I have a swatch element that is displayed when the color picker itself is hidden and I'd like to be able to show the same checkerboard behind that.

**Comment by casesandberg** [comment]
You can!

```
var { Checkboard } = require('react-color/lib/components/common');
```

Opening up a new ticket to add it to the docs: https://github.com/casesandberg/react-color/issues/251

**Comment by elliotbonneville** [comment]
Amazing! Thank you!

Great component, by the way. This is awesome work.
