### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by Prinzhorn** [casesandberg/react-color#266]
https://github.com/casesandberg/react-color/blob/53335f5b26a480495de703b53981d73f5acf78e6/.github/CONTRIBUTING.md

I assume it is outdated, since there's no gulpfile?

To be honest I have no idea how to start with react-color locally. I cloned the repo, did a `npm install` and checked the `package.json` for scripts. I then ran `npm run docs` which gave me

>ERROR in ./~/react-addons-shallow-compare/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' /home/alex/things/src/react-color/node_modules/react/lib/shallowCompare in /home/alex/things/src/react-color/node_modules/react-addons-shallow-compare
 @ ./~/react-addons-shallow-compare/index.js 1:17-52

It would be great if the CONTRIBUTING.md could be updated to contain guidelines for how to contribute. Thanks!

**Comment by casesandberg** [comment]
Not sure why it is doing that as `react-addons-shallow-compare` is in the package.json. Can you try running `npm install react-addons-shallow-compare` and see if that fixes your issue when running `npm run docs`?

**Comment by Prinzhorn** [comment]
Looking at the error message again the problem is the unmet peer dependency on react. So in order to `npm run docs` you need to `npm install react` first. Or would it make sense to have `react` in `devDependencies`?

**Comment by casesandberg** [comment]
Oh! Yeah it would make sense to have react in the devDependencies as well because the docs site uses it.
