### ISSUE TITLE
How do I adjust the height and width of the AlphaPicker ?

### ISSUE THREAD

**Issue by lingpri** [casesandberg/react-color#274]
Could you please provide an example of how to override the style of the components? I tried to change the style like below, and it doesnot seem to impact the picker. Thanks..

 <div style={ styles.picker }>
	              		<AlphaPicker  style={styles.alpha }/>
</div>

**Comment by casesandberg** [comment]
You can find more information about picker props here: http://casesandberg.github.io/react-color/#api-individual

In your case, you will want to do this:
```
<AlphaPicker  width="100px" height="30px" />
```
Or if you want to use them from the style object:
```
<AlphaPicker  { ...styles.alpha }/>
```

**Comment by ArCiGoUnoSquare** [comment]
Is it possible to set the height for the `<SketchPicker />`?

**Comment by ArCiGo** [comment]
@casesandberg Is it possible to set the height for the <SketchPicker />?
