### ISSUE TITLE
Update Documentation for `common` modules to point to `lib` versions

### ISSUE THREAD

**Issue by ardanak** [casesandberg/react-color#277]
When trying to implement a custom color picker component I got the following error.
Cannot resolve module 'react-color/src/components/common'

I used the example code from https://casesandberg.github.io/react-color/

..........................................................................................................
Example code:

var { Saturation } = require('react-color/src/components/common');

<Saturation
  {...this.props}
  pointer={ CustomPointer }
  onChange={ this.handleChange }  />

..........................................................................................................
My Code:

import React from 'react'
import { CustomPicker } from 'react-color'
import { Saturation } from 'react-color/src/components/common'

class MyColorPicker extends React.Component {
  render () {
    return (
      <div>
        <Saturation
          {...this.props}
          onChange={this.onChangeComplete} />
        {/\* <Hue
          {...this.props}
          onChangeComplete={this.onChangeComplete}
          direction={'horizontal'} /> */}
      </div>
    )
  }
}
export default CustomPicker(MyColorPicker)

..........................................................................................................

I noticed that the react-color/src folder doesn't exist in node_modules from a regular npm install.
The problem was fixed by changing src to lib.
'react-color/lib/components/common'

The code examples on the main website https://casesandberg.github.io/react-color/ and the github documentation need to be updated to use lib instead of src

**Comment by casesandberg** [comment]
Updated in `react-color@2.4.3`
