### ISSUE TITLE
Alpha Picker not rendering the color value

### ISSUE THREAD

**Issue by lingpri** [casesandberg/react-color#278]
I have a custom color picker that uses the CompactPicker and the Alpha Picker. I re-use this picker across different draw tools. When I pick a different draw tool, different default values for the picker gets passed down. During the initial phase its drawing fine, but during the next state change, the Alpha picker is still showing the old value from the previous draw.  Please advise , as to why this is happening?

  let rgbcolor = {
            r:color[0],
            g:color[1],
            b:color[2],
            a:color[3]
        }

 <AlphaPicker width="100px" height='10px' onChange={handleColorChange} color={rgbcolor}  />

https://gist.github.com/lingpri/f514e91e393e1583d1987f6582dc6e4f

**Comment by casesandberg** [comment]
You have to save the colors in state and then use `setState` in a handleColorChange callback that you have defined for the onChange handler:

```
class MyTestColorPicker extends React.Component {
  constructor(props) {
    super(props)

    this.state = {
      color: {
        r: props.color[0],
        g: props.color[1],
        b: props.color[2],
        a: props.color[3]
      }
    }
  }

  ...

  handleColorChange = (color) => this.setState({ color })

  ...

  <AlphaPicker ... onChange={ this.handleColorChange } color={ this.state.color }  />


}
```

**Comment by lingpri** [comment]
@ casesandberg - I have a container component that maintains the state and all the child components gets their values from props and rarely I use state. I do see the render method being called ..just that its not reflecting on the AlphaPicker. Why is the value in props not getting picked up.

 `<AlphaPicker width="100px" height='10px' onChange={handleColorChange} rgb={rgbcolor} color={rgbcolor}  />`

One level up Parent Component

```
render({label,size,width,type,style,outline,color,colorlabel,displayColorPicker,handleChange,handleDeleteSelectedGraphic}){

let handleColorChange = (value) => {

		let color = [];//value.rgb;		
		color[0] = value.rgb.r;
		color[1] = value.rgb.g;
		color[2] = value.rgb.b;
		color[3] = value.rgb.a;

		handleChange({label,size,width,type,style,outline,color,colorlabel,displayColorPicker});
	}
```

```
class ContainerComponent extends Component {


this.handleSymbologyChange =(changedDrawType)=> {

      let arr = [];

      this.state.drawTypes.forEach((drawType) => {
           
              if(drawType.label !== changedDrawType.label) {

                  arr.push(drawType);
            }
            else {
                  arr.push(changedDrawType);
            }

      });
      this.setState({drawTypes:arr});

    }

.......
render() {

    let alertViewSymbolChange = (symbol)=> {
         
          this.handleSymbologyChange({...selectedDrawType,symbol});

    }

   <SymbolComponent {...selectedDrawType.symbol} handleChange={alertViewSymbolChange} /> 

}

                  

 this.handleSymbologyChange =(changedDrawType)=> {

      let arr = [];

      this.state.drawTypes.forEach((drawType) => {

            //if(drawType.type !== changedDrawType.type && drawType.symbol.type !== changedDrawType.symbol.type) {
              if(drawType.label !== changedDrawType.label) {

                  arr.push(drawType);
            }
            else {
                  arr.push(changedDrawType);
            }

      });
       this.setState({drawTypes:arr});
       topic.publish('update-symbology',changedDrawType);
    }

```

**Comment by TK-Tang** [comment]
I have the same issue even when following caseandberg's example. The alpha value in the RGBA in SketchPicker just won't change whether through the textbox or the slider.
