### ISSUE TITLE
Very large package before bundling (58 MB)

### ISSUE THREAD

**Issue by lzrski** [casesandberg/react-color#279]
I am aware that there are several issues filed regarding the size this module adds to the bundled code. This one is about size "on disk" (which is mostly a problem for installation time).

```
$ du -sh node_modules/react-color/
58M	node_modules/react-color/

$ du -sh node_modules/react-color/node_modules/*
 52M	node_modules/react-color/node_modules/babel-jest
4.8M	node_modules/react-color/node_modules/lodash
132K	node_modules/react-color/node_modules/material-colors
 28K	node_modules/react-color/node_modules/merge
 20K	node_modules/react-color/node_modules/react-addons-shallow-compare
216K	node_modules/react-color/node_modules/reactcss
```

Shouldn't `babel-jest` be a development dependency?

**Comment by casesandberg** [comment]
Wow, great catch! That definitely wasn't meant to be in dependencies. Fixed in `react-color@2.4.1`
