### ISSUE TITLE
Cannot resolve module react-addons-shallow-compare v2.4.1

### ISSUE THREAD

**Issue by TLadd** [casesandberg/react-color#281]
When going form v2.4.0 => v2.4.1, I get a build error saying react-addons-shallow-compare cannot be resolved in ColorWrap, Alpha, EditableInput, Hue, and Saturation.

Believe the issue is just react-addons-shallow-compare being added to devDependencies instead of dependencies last update.

**Comment by MarshallOfSound** [comment]
I also have this issue, luckily @greenkeeperio-bot caught it for me 😆 

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/pull/1867

Can this get patched ASAP 👍

**Comment by casesandberg** [comment]
Sorry about that. Fixed in `react-color@2.4.2`
