### ISSUE TITLE
Wrong mouse position inside of scrolled iframes

### ISSUE THREAD

**Issue by Moerphy** [casesandberg/react-color#285]
Hi,

when a colorpicker is used inside of an iframe that is scrollable then all the mouse coordinates are offset by however much the containing iframe is scrolled.

Testcase: https://jsfiddle.net/4bbzuey1/ (scroll iframe a bit, then try to use a colorpicker)

Looks like the bug was introduced in #181 ironically enough:
```javascript
// helpers/saturation.js
var left = x - (container.getBoundingClientRect().left + (inIFrame ? 0 : window.pageXOffset));
var top = y - (container.getBoundingClientRect().top + (inIFrame ? 0 : window.pageYOffset));
```
When inIFrame is forced to false the color picker works like a charm again.

**Comment by afc163** [comment]
+1

**Comment by casesandberg** [comment]
This has been reverted in `react-color@2.4.3`
