### ISSUE TITLE
Using RGB values w/ no hue breaks saturation picker.

### ISSUE THREAD

**Issue by rickyvetter** [casesandberg/react-color#29]
Passing in a value like `{r: 100, g:100, b:100}` Will not allow you to use the saturation input to select colors. Because `oldHue` starts as undefined, and the if statement in `helpers/color.js` sets the hue to that undefined value:

```js
  toState: function toState(data, oldHue) {
    var color = tinycolor(data);
    var hsl = color.toHsl();
    var hsv = color.toHsv();

    if (hsl.s === 0) {
      hsl.h = oldHue;
      hsv.h = oldHue;
  }

    return {
      hsl: hsl,
      hex: color.toHex(),
      rgb: color.toRgb(),
      hsv: hsv,
      oldHue: data.h || oldHue || hsl.h
    };
  }
```

**Comment by casesandberg** [comment]
Ah. So this should probably fall back to `0` if the old hue is not defined? The only reason I have it tracking the old hue is because the color library I am using converts everything to RGB first and if you drag saturation over to the far left it would lose whatever hue you were at and it would switch to red (0).

```
if (hsl.s === 0) {
  hsl.h = oldHue || 0;
  hsv.h = oldHue || 0;
}
```

**Comment by rickyvetter** [comment]
That is definitely a way to fix it. I made a PR that sets `this.state.oldHue` in the constructor which should fix the problem. (which means it falls back to 250 currently). I don't have a strong opinion on which solution is better.

**Comment by WickyNilliams** [comment]
I maintain a [react color picker component](https://github.com/WickyNilliams/react-simple-colorpicker) and have dealt with this issue myself. A rising tide lifts all boats, as they say, so I thought I would offer my solution.

I found the easiest way to fix is not to keep the old value in memory, but to separate your internal representation of the colour from the colour library's representation (in this case tinycolor).

So my state might look like this:

```js
{
  color : {
    h : 0,
    s : 1,
    v : 1
    a : 0.5
  }
}
```

Whenever `h`, `s`, `v`, or `a` changes, update just that component of the color state, and use the color lib only to generate a value to pass to the `onChange` callback. See here: https://github.com/WickyNilliams/react-simple-colorpicker/blob/e17040872a695926ad7e6ee3aaca27ca161024d3/lib/components/ColorPicker.js#L112-L128

Also you must then check whether in `componentWillReceiveProps` if the new color coming in is different by comparing their rgb representation, and updating the internal state if they differ. See here https://github.com/WickyNilliams/react-simple-colorpicker/blob/e17040872a695926ad7e6ee3aaca27ca161024d3/lib/components/ColorPicker.js#L29-L33

This might sound complex, but it's actually really simple and works perfectly. Also pushes the use of the color lib to the edges of your component (input/output only)

Hopefully that makes sense and is useful :)

**Comment by casesandberg** [comment]
@rickyvetter This was temporarily fixed in `react-color@1.0.6`, but I will be implementing what @WickyNilliams suggested in `1.1.0` Thanks!

**Comment by WickyNilliams** [comment]
No problems. If you hit any issues with this approach, let me know, happy to help

**Comment by WickyNilliams** [comment]
While I'm here: I'll be releasing a colour lib which is just a collection of composable pure functions in the near future . Require just what you need, so footprint will be tiny. If that might be of interest (personally I really dislike tinycolor, and most color libs, for their awkward OO interfaces ) I'll file an issue when it's ready. If not, don't worry.

**Comment by casesandberg** [comment]
@WickyNilliams No way! That is exactly what I was looking for (and didnt want to roll my own), definitely on the same page as you with that! Are we talking few-weeks future or few-months future?

**Comment by WickyNilliams** [comment]
OK cool. Yeah I've found all the existing libs to be a disappointment. I just want functions! 

More like a few days haha. Basically I forked another well tested colour lib, removed all the extraneous stuff, broke into small modules etc, so not a whole lot of work. Just a case of some final clean up,  then release. So it will be some time next week I expect.

**Comment by casesandberg** [comment]
👏🙌

**Comment by casesandberg** [comment]
Hey @WickyNilliams, any update on the color library?

**Comment by WickyNilliams** [comment]
Excuse the delay. I've been busy, and I *slightly* (read: greatly) underestimated how much work was required to get the library up to scratch :) But! I will publish tomorrow.

I've tested locally against my color picker, and it works well. So hopefully it will be solid enough for use here too. If you find any issues or have suggestions for improving the API (I made a couple of decisions that i'm not 100% sure of), please let me know.

I will report back after publishing.

**Comment by casesandberg** [comment]
Sweet! Looking forward to using it and will send over issues / pull requests if I see anything!

**Comment by WickyNilliams** [comment]
Here you go https://github.com/wickynilliams/pure-color. `pure-color` on npm :)

**Comment by WickyNilliams** [comment]
Also i've updated my color picker to consume the library, if you'd like to see how I've used it. See this commit: https://github.com/WickyNilliams/react-simple-colorpicker/commit/4931077e6b166699feb8dc793218e01586d44d23
