### ISSUE TITLE
Let users add colors to presetColors for SketchPicker

### ISSUE THREAD

**Issue by gittestcoder** [casesandberg/react-color#305]
A feature I'd like to see is the ability to let users add a color to the presetColors list. Could add a [+] button somewhere in the ColorPicker, maybe at the end of the list of presetColors?

**Comment by casesandberg** [comment]
That is a great idea! Here is what I am thinking implementation would be like:

Add an `onAddPresetColor` callback, which will display the add button in the UI if present. Then all you would need to do would be to put a callback on that prop to push the color to your array of preset colors. Does that make sense?

**Comment by gittestcoder** [comment]
I like that idea! But now I'm thinking to make it complete it probably makes sense to be able to let users delete colors from the list too. Which means you'd probably have to have some way of selecting a color, then deleting it. What do you think about that?

**Comment by casesandberg** [comment]
Yeah, totally! We can do the same thing with an `onDeletePresetColor` callback that renders some sort of menu like in sketch: 

![image](https://cloud.githubusercontent.com/assets/4633636/21296256/a4bb8032-c535-11e6-84fe-fc50469547c3.png)

How does that sound?

**Comment by gittestcoder** [comment]
How do you access that menu? Right click?

**Comment by casesandberg** [comment]
Yeah! Can make the functionality the same on the BlockPicker as well!

**Comment by pbojinov** [comment]
It'd be interested in seeing support for setting preset colors as well. What do you guys think?

**Comment by justpushCar** [comment]
nice

**Comment by SpencerDawson** [comment]
Since I am actually in the process of working on this myself, I'll see what I can do about making a version for react-color.

**Comment by SpencerDawson** [comment]
@casesandberg So I have this working now, but I don't have a context menu involved. Simply right-clicking removes the color from the color palette.

I want to know your opinions on either introducing an unrelated component to color-react or to simply use an exist library for the context menu.

Also, the Palette component that was built. Should it be integrated into the other components that have multiple swatches?

**Comment by SpencerDawson** [comment]
@casesandberg 

![image](https://user-images.githubusercontent.com/6266417/30076104-d8b2b8f0-9245-11e7-9a98-a50cb66f598a.png)

What are your opinions on the small text, as opposed to introducing a context menu element? It turned out looking better than I thought it would.

**Comment by casesandberg** [comment]
Oh, I actually really like the look of that too!

**Comment by manu-st** [comment]
@SpencerDawson Any update on this front?

**Comment by SpencerDawson** [comment]
So there is some discussion in #413 about holding off until the new 3.0.0 build. Between that, and the fact that I my employer at the time moved me to maintenance on an AngularJS project, I haven't done too much with it.

I'm open to tackling this again on the weekends, but I need to dust that part of my brain off, plus review the reasoning behind the hold again.

**Comment by casesandberg** [comment]
After much deliberation, we are going to be utilizing children to control everything having to do with the swatches in v3.0.0. If someone would like to take a stab at making an example for this that would be great, but it wont live in the actual library itself.
