### ISSUE TITLE
SketchExample swatch not working

### ISSUE THREAD

**Issue by quangas** [casesandberg/react-color#306]
In your example for the SketchExample (last example), if you click on any of the swatches, the color don't get set or selected, but instead it just closes the Color Picker dialog.

**Comment by casesandberg** [comment]
That's weird, I will look into it!

**Comment by rgnevashev** [comment]
+1 It doesnt work if you click to any presetColors
![2017-01-05_20-14-53](https://cloud.githubusercontent.com/assets/123600/21690069/bf313f9a-d383-11e6-98aa-d09c2c60ddd2.png)

**Comment by quangas** [comment]
I've updated to 2.11.1 but the problem still persists.
