### ISSUE TITLE
Add Preset Tooltips

### ISSUE THREAD

**Issue by qasid** [casesandberg/react-color#307]
Is there a way to render ToolTip on hovering on color, that displays color information?  e.g color name "White"

**Comment by casesandberg** [comment]
Yeah, that is a great thing to add! Most colors are stored in the defaultProps as hex codes, however, unless you explicitly pass down the colors as string names. Would tooltips as hex codes be ok?

**Comment by qasid** [comment]
Hex codes will be good, but then it will be restricted to hex codes only. Could there be a possibility that tool tip content is passed in as props  
e.g.
`[ {

`[ {
"displayName": "White",
"rbg": "RGB(255,255,255)"
},
{
"displayName": "#000000",
"rbg": "RGB(0,0,0)"
}]` 


or expose a function to update tool tip content.
