### ISSUE TITLE
How to override <Hue /> componet styles for making one custom color picker?

### ISSUE THREAD

**Issue by Lorde-Y** [casesandberg/react-color#309]
I wanna to change<Hue />  styles, include pointer, slider styles and so on. How can i make custom style? Thank you.

**Comment by casesandberg** [comment]
You can follow along how to create custom pickers here: http://casesandberg.github.io/react-color/#create-helpers

Essentially: All you have to do is include the Hue helper component, wrap it in a div that is the width / height you want with position relative, and you can pass in a custom pointer via the `pointer={ CustomPointer }` prop!
