### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by fikriauliya** [casesandberg/react-color#31]
Do you plan to have bower package? 
Some client side developers (me included) doesn't use NPM but bower. Hope this good library is also in Bower package :smile:

**Comment by casesandberg** [comment]
@fikriauliya I unfortunately don't have the resources to get this working as a bower package. I do all of my React work in node / Webpack at the moment.

**Comment by jpatel3** [comment]
+1

**Comment by jpatel3** [comment]
@fikriauliya you can use with bower using below line -
```
"dependencies": {
  ...,
  "react-color": "https://github.com/casesandberg/react-color.git#v2.11.4",
  ...
}
```
