### ISSUE TITLE
UMD support

### ISSUE THREAD

**Issue by stevenxxiu** [casesandberg/react-color#310]
Can there be UMD support, so there is a /dist directory with a prebuilt version? This allows the package to be hosted on cdns, such as https://unpkg.com/. There's [something similar done for react-tabs](https://github.com/reactjs/react-tabs/blob/master/webpack.build.js). Thanks!

**Comment by casesandberg** [comment]
I don't really like having built files in repos, but I can definitely add it if you think it would be useful!

**Comment by jpatel3** [comment]
+1 I think it will be good addition.

**Comment by casesandberg** [comment]
There will now be a UMD bundled version distributed in 3.0.0, you can start using it now with `react-color@3.0.0-beta.3` 🎉

Here is the unpkg link: https://unpkg.com/react-color@3.0.0-beta.3/dist/react-color.min.js

Example is here: https://github.com/casesandberg/react-color/blob/3.0.0/examples/with-umd/index.html

**Comment by ekoeryanto** [comment]
@casesandberg could it be separated for each picker, eg react-color-sketch.js?

**Comment by UnHumbleBen** [comment]
@casesandberg Can UMD bundles also be made for version 2?
