### ISSUE TITLE
How do i can to change position colorPicker?

### ISSUE THREAD

**Issue by zevsik** [casesandberg/react-color#312]
Hi Guys.
I have a problem with position colorPicker.

You can see issue to [screenshot](http://www.awesomescreenshot.com/image/1993875/517d426f6b11a12960bf71f27e06031b)  

Is it posible that colorPicker display on top part?

**Comment by casesandberg** [comment]
Hey! Just wrap the component in a div with `position: absolute` and you can position it however you like!
