### ISSUE TITLE
Use PureRenderMixin to not rerender when you don't have to

### ISSUE THREAD

**Issue by jaredp** [casesandberg/react-color#32]

**Comment by casesandberg** [comment]
@jaredp Is there a way to do this with ES6 class declaration?

**Comment by jaredp** [comment]
https://gist.github.com/acdlite/453f227f5e5cbbf105f8 looks like the best bet, although if not you could hand-copy in a `shouldComponentUpdate()` method.  It's a real shame mixins aren't in ES6.
