### ISSUE TITLE
Styles are not being applied

### ISSUE THREAD

**Issue by pedronauck** [casesandberg/react-color#328]
Hi @casesandberg,

I was using your react-color with webpack and it was works great, so when I update to webpack 2, reactcss does'nt apply the styles and the component just render the markup without any style.

<img width="194" alt="screen shot 2017-02-14 at 01 04 33" src="https://cloud.githubusercontent.com/assets/2029172/22913422/b93a088c-f251-11e6-8394-d6920147f10c.png">

**Comment by casesandberg** [comment]
What version of `react-color` are you using? Also, are you getting any console errors?

**Comment by andrewgleave** [comment]
I found the same, though I haven't investigated it and just found this issue so I thought I'd chip in:

`"webpack": "^2.2.1", "react-color": "^2.10.0"`

**Comment by casesandberg** [comment]
This is bizarre, I just tried it with Webpack 2 and it works fine for me. Is it only happening to one color picker? Also, are you passing a `style` prop to the picker component?

**Comment by andrewgleave** [comment]
This is basically what I'm doing. This is code which used to use an older version of `react-color` so please correct me if anything is wrong.

    const pickerStyles = {
      position: 'absolute',
      top: SubNavHeight,
      left: parentXOffset - 20
    };

----
    
    <SketchPicker
      display={ this.state.showPicker }
      color={ color }
      presetColors={ presets }
      onClose={ this.handlePickerClose }
      onChange={ this.handlePickerChange }
      onChangeComplete={ this.handlePickerChangeComplete }
      positionCSS={ pickerStyles } />

**Comment by saboya** [comment]
I'm having the same issue, with Webpack2.

**Comment by pedronauck** [comment]
I'm using webpack `^2.2.1` and react-color `^2.11.1`. I think that's a problem with de [reactcss](http://reactcss.com/), the module doen'st applying the inline styles.

**Comment by andrewgleave** [comment]
If you're experiencing this and using `lodash-webpack-plugin` see: https://github.com/casesandberg/reactcss/issues/141#issuecomment-283709581

**Comment by saboya** [comment]
Nice catch, I am indeed using lodash-webpack-plugin. Will test again.

**Comment by casesandberg** [comment]
Sorry about this. I updated ReactCSS to not use `map` on objects, you shouldn't have to do anything special using `react-color@2.11.2`
