### ISSUE TITLE
how choose different picker

### ISSUE THREAD

**Issue by artsx** [casesandberg/react-color#332]
Hello,
How do you load the different pickers?
I tried to put:
`Import BlockPicker from 'react-color';`
`Import TwitterPicker from 'react-color';`

With `<BlockPicker ... />` `<TwitterPicker ... />` etc ... I still have the rendering of chrome,
I've tried to do also `<ColorPicker type="TwitterPicker" or type="Twitter" />` but there's nothing to do, I always render ChromePicker, I do something wrong?

Best regards,

**Comment by lucaas** [comment]
You are importing the default export from the module, which is the Chrome picker. What you want to do is import the named exports. 

```javascript
import { BlockPicker } from 'react-color';
```

See [using named exports](https://developer.mozilla.org/en/docs/web/javascript/reference/statements/export#Using_named_exports) for more information.

**Comment by artsx** [comment]
Damn you're right, I tried with the `{xxx}` but it did not work, I had a worry and I did not look further,

Thx a lot !
