### ISSUE TITLE
Uncaught Type Error with version 2.11.1

### ISSUE THREAD

**Issue by mbaggott** [casesandberg/react-color#334]
With my setup all was working fine a few weeks ago.
Have just updated npm packages, and am now getting an exception in console when i try to load SketchPicker
import { SketchPicker } from 'react-color';

The exception is: 

"Uncaught TypeError: (0 , _reactcss.hover) is not a function"

**Comment by mbaggott** [comment]
Nevermind, updated to version 2.11.3 and it is working. Thanks

**Comment by casesandberg** [comment]
Yeah sorry about that. I goofed and pushed a breaking change to a minor version. I corrected it.
