### ISSUE TITLE
Module Build Failed Stage-0 preset at fault

### ISSUE THREAD

**Issue by astericky** [casesandberg/react-color#336]
@casesandberg 

`ERROR in ./~/react-color/lib/index.js
Module build failed: Error: Couldn't find preset "stage-0" relative to directory`

I am not sure why this isn't working. I see the dependency right there in the devDependencies. I don't understand what is going on here.

**Comment by mariushop** [comment]
+1

**Comment by casesandberg** [comment]
Yes, you need to use Stage 0 to your babel https://babeljs.io/docs/plugins/preset-stage-0/

**Comment by StephanBijzitter** [comment]
Does that mean you have to install stage-0 as a dependency in the consuming package? If so, I'd prefer for it to be a peer dependency of react-color, allowing NPM/Yarn to complain when it is missing, instead of having to search inside this issue tracker.
