### ISSUE TITLE
React PropTypes deprecation warning

### ISSUE THREAD

**Issue by Ashoat** [casesandberg/react-color#341]
Using the package with React 15.5 triggers this warning:
```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
```
More info is here: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

Note that with React 16.0 it will be removed.

**Comment by donorman** [comment]
+1

**Comment by happycollision** [comment]
Looks like the issue isn't with this package, but with a dependency, unfortunately. This is the last warning I cannot clear out of my project. :man_facepalming:

**Comment by casesandberg** [comment]
Rejoice! @vvasilev- found where it was being used still, sneaky modules folder 😬. No more warnings in `react-color@2.11.7`

**Comment by happycollision** [comment]
And now the obsessives among us can sleep at night. Thanks!
