### ISSUE TITLE
Pickers default to saturation at 0.5 — possible to change default saturation?

### ISSUE THREAD

**Issue by IainIsCreative** [casesandberg/react-color#342]
Hey folks! I couldn't find a similar issue to this, but this is an odd one for me.

Basically, I just want to use `<HuePicker />` for a project, but I've noticed any colours I pick are of medium saturation i.e. When I set to red, the value is not `#ff0000` but `#4d1919`. Is there any way to change this? I just want to use `<HuePicker />` and nothing else, though it's hard to just use this if I can't change the default saturation and not get the most saturated hue.

My apologies if this is hard to understand, but thanks in advance!

**Comment by casesandberg** [comment]
Ah! Yes, that should be the behaviour of that. I have fixed it and pushed to `react-color@2.11.5`!

**Comment by IainIsCreative** [comment]
@casesandberg just tried it out — brilliant! Works perfectly, thank you very much!

**Comment by evgenyboxer** [comment]
@casesandberg Could I suggest having pure hue color as a prop? I actually need the original behavior... If you agree, I can open a PR for this.

I ended up writing my own custom HuePicker which is identical to the original one but without that hard coded line that overwrites onChange
