### ISSUE TITLE
How can I change the css (background, padding, border etc) of the <SketchPicker />

### ISSUE THREAD

**Issue by danishiqbal4** [casesandberg/react-color#343]
The `<SketchPicker />` has default styling like background, border-radius, padding etc, how can I change these and also add new styles to the child elements like inputs and span?

**Comment by casesandberg** [comment]
Each of the pickers consumes common components and just add styling around them so it is fairly straight forward! You can just copy the Sketch component (https://github.com/casesandberg/react-color/blob/master/src/components/sketch/Sketch.js) and add your own styling and components around the main ones. 

The only thing you will need to change is the common import at the top of the file, change:
```
import { ColorWrap, Saturation, Hue, Alpha, Checkboard } from '../common'
// to
import { ColorWrap, Saturation, Hue, Alpha, Checkboard } from 'react-color/lib/common'
```

**Comment by danishiqbal4** [comment]
Oh I thought there was some other way like passing an object or something like that. But anyways I took this way and it works fine. Thanks....

and btw it's 
`import { ColorWrap, Saturation, Hue, Alpha, Checkboard } from 'react-color/lib/components/common'`
