### ISSUE TITLE
Remove visible prop from ColorWrap

### ISSUE THREAD

**Issue by georeith** [casesandberg/react-color#349]
It is not used and prevents you passing it through from above. It appears to set the display prop on the wrapped child but does not appear to be used anywhere.

Would be much better to let someone pass through their own `visible` prop and control it themselves.

**Comment by casesandberg** [comment]
Ah, yes, this is an old API that just never got removed. I'm putting it on the list!

**Comment by casesandberg** [comment]
Removed in `react-color@2.12.0`
