### ISSUE TITLE
Block & Twitter don't store color in input field

### ISSUE THREAD

**Issue by Sicria** [casesandberg/react-color#350]
The Block & Twitter components both have an input field which does not display the current hex code of the ``color`` prop.

Is there a workaround for this?

**Comment by mbifulco** [comment]
I noticed this, too.  Would be great to have a fix for this.

**Comment by casesandberg** [comment]
This has been fixed in `react-color@2.12.0` !

**Comment by Sicria** [comment]
Thanks @casesandberg

**Comment by mbifulco** [comment]
Thank you!
