### ISSUE TITLE
Global event listeners.

### ISSUE THREAD

**Issue by cookednoodles** [casesandberg/react-color#357]
We have been having a few weird interactions on an application we are working on that uses react-color.

After hunting a bit, I noticed that react-color is adding  event listeners on mouseup/down to the whole window and not to the component :
https://github.com/casesandberg/react-color/search?utf8=%E2%9C%93&q=mouseup&type=

Is there a valid reason for doing this ?

**Comment by casesandberg** [comment]
If I remember correctly, we had to add the event listeners so that your mouse could drag sliders further than the bounding boxes for things. What issues are you running into with them?

**Comment by casesandberg** [comment]
The v3.0.0 is being actively developed and I have dug into this further and it is necessary. I have, however, moved the listeners over to document instead of window. Would this solve your problem?

**Comment by Moinax** [comment]
That's actually a big problem with editors like Slate for instance. 
Those kinds of editor use a lot of mouseUp and mouseDown events, for focus and so on.
So, we should be able to stop the propagation on the ColorPicker component to avoid a focus on the Slate editor, otherwise the focus will close the ColorPicker tool in our case.

**Comment by Jip-Hop** [comment]
The global event listeners also causes problems when using the color picker inside a new window using a react portal, e.g. with [react-new-window](https://www.npmjs.com/package/react-new-window ). When you click inside the color picker in the popup window, and then move the mouse over the parent window, the color picker handle starts to move. Therefore dragging in the color picker window itself doesn't work.
