### ISSUE TITLE
Help with .NET MVC Implementation

### ISSUE THREAD

**Issue by DiamontCP** [casesandberg/react-color#361]
Hello,
I need some help installing the react-color in an mvc project.
Can you install it on a new mvc project as an example and upload it?

Thanks!!!

**Comment by casesandberg** [comment]
I'm not sure what you mean by an MVC project? Please provide me with a link
to your project with the colo picker in it and I am happy to debug it.

**Comment by DiamontCP** [comment]
I want to install the widget in a Microsoft project MVC 5.
See the reference (https://www.asp.net/mvc)

**Comment by casesandberg** [comment]
Can you send me a link to the project where you tried to implement it? Happy to try and debug it

**Comment by DiamontCP** [comment]
https://github.com/DiamontCP/mvc-react-color

They are only twoo thinks in this repo.
1. New mvc project.
2. Form example.

It will be great if you can commit separate:
a) the react needed files for the installation.
b) A basic usage of the widget in the for I created.

I think it will be a good contribution for all the .Net community for using you're witget.

Thanks 4 all.

**Comment by DiamontCP** [comment]
Hi Case, have you seen my last post?

Thanks

**Comment by casesandberg** [comment]
Hey @DiamontCP, I, unfortunately, do not know .NET or MVC so I can't be of much help. If you have code where you can get it implemented I am more that happy to take a look and help out with a form example. 

I think a good first step would be to try and get NPM modules working within MVC: https://stackoverflow.com/questions/37935524/how-to-use-npm-with-asp-net-core

**Comment by DiamontCP** [comment]
Hi Case,
Thanks you much for the info. It is a very good approach what I am looking for.
If you think it would be useful, I can try it and do a tuto of this for those .net developers who want to use yours pickers.

**Comment by casesandberg** [comment]
That would be great! Feel free to post your findings in here so that anyone searching about it will be able to find info about it :)
