### ISSUE TITLE
Drag event doesn't work

### ISSUE THREAD

**Issue by qinfanpeng** [casesandberg/react-color#363]
Version: 2.12.1
While trying to drag Alpha slider to change Alpha, it doesn't work. and i got these message:
non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.

**Comment by casesandberg** [comment]
There is a related issue here: https://github.com/angular/material2/issues/4221. From what I understand, it is just a warning for a performance optimization and shouldn't break anything. Are you using a default color picker or importing the Alpha component itself?
