### ISSUE TITLE
Swatch Hover Event

### ISSUE THREAD

**Issue by pconerly** [casesandberg/react-color#365]
My team would like a hover event for when a user's mouse goes over a Swatch. (Specifically this is in Compact/CompactColor's Swatch, but I think it is generally useful for all uses of Swatches.)

Would you consider a PR that adds an `onSwatchHover` option to `Compact`?

**Comment by pconerly** [comment]
@casesandberg so I'm worried that I introduced some inconsistent behavior--

Compact is getting is getting a color object that's good, like:
```
    // color = {
    //   hex: '#333',
    //   rgb: {
    //     r: 51,
    //     g: 51,
    //     b: 51,
    //     a: 1,
    //   },
    //   hsl: {
    //     h: 0,
    //     s: 0,
    //     l: .20,
    //     a: 1,
    //   },
    // }
```

But the `onSwatchHover` event is just giving a simple hex `#dd6611`. 

Reading the code more, it's looking like I need to do something in `ColorWrap` for it? Gonna write a PR real quick

**Comment by pconerly** [comment]
The PR is #369

**Comment by sgrund14** [comment]
Would it be possible to add a offSwatchHover event to the circle picker? Say, if you wanted to view a color by hovering over it, but deselect/return to the previously selected cover upon the offHover event.

**Comment by pconerly** [comment]
@sgrund14 I think that makes sense. Given that my PR already added onSwitchHover, `offSwatchHover` should be pretty easy to add
