### ISSUE TITLE
Transparant color preset сolors

### ISSUE THREAD

**Issue by fast0490f** [casesandberg/react-color#367]
Hi, how do you look at it to make the background a [transparency grid](http://cdn-write.demandstudios.com/upload//image/05/DC/7FDE46BA-B311-4FFA-9C72-5074CE95DC05/7FDE46BA-B311-4FFA-9C72-5074CE95DC05.jpg) rather than a simple white color?

**Comment by pconerly** [comment]
Are you asking how Case added the grid, like in this?

![screen shot 2017-06-21 at 11 13 36 am](https://user-images.githubusercontent.com/469808/27399792-cabfd1b0-5672-11e7-97e8-430cd4073de5.png)

He did it with a small grid image and css to repeat it in the background. 

```
    position: absolute;
    top: 0px;
    right: 0px;
    bottom: 0px;
    left: 0px;
    background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAMUlEQ…CTZhw1gGGYhAGBZIA/nYDCgBDAm9BGDWAAJyRCgLaBCAAgXwixzAS0pgAAAABJRU5ErkJggg==) left center;
```

**Comment by casesandberg** [comment]
@pconerly is correct, if you would like to use a checkerboard background you can use CSS, or if you would like to use it as a component:
```jsx
import Checkboard from 'react-color/lib/components/common/Checkboard'
// ...
<Checkboard />
```

Alternatively, if you would like to have a transparent or "none" color swatch in a picker, you can include `transparent` as a swatch:
```jsx
<SketchPicker presetColors={ ['#fff', ..., 'transparent'] } />

**Comment by casesandberg** [comment]
I am going to close this due to inactivity, feel free to open up a new issue if you still need help!
