### ISSUE TITLE
Cursor jumping in the lower part of saturation component

### ISSUE THREAD

**Issue by lvl5hm** [casesandberg/react-color#371]
![bug](https://user-images.githubusercontent.com/22579162/27680777-9e931026-5cc5-11e7-931b-1237795efb67.gif)
When selecting color with saturation picker in the lower part, the cursor jumps to the bottom left corner of the component, also sometimes changing the hue color.

**Comment by casesandberg** [comment]
Ah yes, this is a known bug. I created a larger issue for it and started tracking it for the v3 release here https://github.com/casesandberg/react-color/issues/404
