### ISSUE TITLE
Spellcheck in color text inputs

### ISSUE THREAD

**Issue by vasconita** [casesandberg/react-color#372]
First of all, thanks to all contributors for this library. It's awesome, congratulations!

The only thing I find a little bit annoying is to have spell checking in color text inputs. I realized that it only happens in Chrome, but since it's the most used browser I think could be nice to disable spell checking in this case.

![react color - google chrome](https://user-images.githubusercontent.com/7622399/27792829-c8d3dbac-5ffb-11e7-9667-15b2e63aa084.jpg)

I think it's as simple as putting attribute spellCheck to false in input tag of [EditableInput.js](https://github.com/casesandberg/react-color/blob/master/src/components/common/EditableInput.js).

If you agree I can create a PR to change it.

**Comment by casesandberg** [comment]
Great idea! Yes please submit a PR with the change. Make sure to run "npm
run jest -- -u" before committing so the snapshot tests update with your
change.

**Comment by pconerly** [comment]
This got fixed, so I'm closing it :]
