### ISSUE TITLE
Standalone JS version

### ISSUE THREAD

**Issue by reardestani** [casesandberg/react-color#386]
Hi, Great component. 

Is there any fork/branch, ... for JS standalone version? We need to use this in a **none react** project.

**Comment by jeroenransijn** [comment]
Hi @reardestani, thanks for showing interest in this project. I am not sure if anyone tried to create a JS standalone version of `react-color`. Depending on your needs, you could only load React in the part of the app where you need the color picker.

Alternatively you could look at the native color input: https://caniuse.com/#search=color, or potentially other color pickers.
