### ISSUE TITLE
npm in dependencies?

### ISSUE THREAD

**Issue by dmr** [casesandberg/react-color#40]
First of all: Thank you for this project, keep up the good work!

In the package.json there is npm2 listed as a dependency.

Is this required?
Does react-color work with npm3?

I use npm3 for most of my projects and then with react-color I get errors because of this dependency.

**Comment by jonathanong** [comment]
there's no need to have npm as a dependency!

**Comment by casesandberg** [comment]
Ah, sorry! This was removed in `1.1.1` !
