### ISSUE TITLE
Question: Default use of block element inside inline-element

### ISSUE THREAD

**Issue by SpencerDawson** [casesandberg/react-color#400]
I noticed that the [handleFocus](https://github.com/casesandberg/react-color/blob/b89a69afb27166dda41ed81db9706eba8cfa35d8/src/helpers/interaction.js#L3) helper defaults to nesting the passed component inside a `<span />` element.

Given it's only use in the repo is [here](https://github.com/casesandberg/react-color/blob/b89a69afb27166dda41ed81db9706eba8cfa35d8/src/components/common/Swatch.js#L56), which is a block element.

Is there a specific purpose for this? It seems more likely that block elements would be passed to it, and as far as I am aware, block elements inside inline elements is invalid.

**Comment by casesandberg** [comment]
Ah, yeah, that whole concept needs to be cleaned up, handle focus was built with a different purpose in mind. The next version of react-color will be dropping it, actually. I am going to go ahead and close this, but feel free to open up another issue if you have any more questions.
