### ISSUE TITLE
react-color (and reactcss) now bundled as ClojureScript library jar.

### ISSUE THREAD

**Issue by craigmalone** [casesandberg/react-color#406]
Just out of politeness I wanted to let you know that I have added a wrapper jar/lib to make react-color easily accessible to ClojureScript projects, by including it as a package in CLJSJS.  (http://cljsjs.github.io/)

All links refer back to your project site and github project and use the same licence associated with your github project.

See: 
https://github.com/cljsjs/packages/tree/master/react-color
and  
https://clojars.org/cljsjs/react-color

And by the way, thanks for the color pickers - they are working well within my Clojurescript project.

**Comment by casesandberg** [comment]
Thanks Craig!
