### ISSUE TITLE
react-color gets cutoff when at the bottom of the screen

### ISSUE THREAD

**Issue by sontek** [casesandberg/react-color#407]
If you are at the bottom of the page the color picker gets cutoff:

<img width="265" alt="screenshot 2017-09-01 09 26 54" src="https://user-images.githubusercontent.com/151924/29974198-c0f0a21e-8ef7-11e7-8b9d-16a641123617.png">

Can we adjust this to popover the browser?  When there is extra content for scrolling its not that bad but when there is no scrollable content then its just cutoff and you can't get to it.

**Comment by casesandberg** [comment]
Currently, there is no way to have web elements pop over the browser. You could always create a wrapper component that makes the color picker pop upwards instead of downwards when it is open!

**Comment by Jerry-0919** [comment]
> Currently, there is no way to have web elements pop over the browser. You could always create a wrapper component that makes the color picker pop upwards instead of downwards when it is open!

How can I solve this issue when the wrapper class is a fresh div tag?
