### ISSUE TITLE
Build fails on case sensitive file systems

### ISSUE THREAD

**Issue by davidlanger** [casesandberg/react-color#41]
The current npm version 1.0.6 fails on case sensitive file systems because `Color.jsx`requires `var Sketch = require('./sketch/Sketch');` but the path is actually `./Sketch/Sketch`.

It is fixed in [master](https://github.com/casesandberg/react-color/commit/23c0c1a4cacb7733d7475874c9751a3e96fac073) so this is actually just a reminder to put it out there :)

Otherwise awesome component!

**Comment by jonathanong** [comment]
:+1:

**Comment by casesandberg** [comment]
My bad @davidlanger, just pushed `1.1.0` to npm with that fix!

**Comment by davidlanger** [comment]
Unfortunately that rename seems to not have made it to the published version. Try it yourself by installing the version from npm. The file is still called `lib/components/Sketch/Sketch.js`.

Such a shame OS X still ships with a case insensitive file system :/
