### ISSUE TITLE
latest update on `prop-types` break our CI

### ISSUE THREAD

**Issue by redguardtoo** [casesandberg/react-color#418]
Our CI server does NOT have git installed. But to instal the version of `prop-types` git is required

**Comment by jannisg** [comment]
Same here, behind a corporate firewall, the `prop-types` which points to the `anti-gravity` fork of `prop-types` will try to git clone the repo and everything fails due to security permissions.

Is there any reason why prop-types isn't just using the official package?

**Comment by heikowe** [comment]
Same here, dependency:
"prop-types": "https://github.com/anti-gravity/prop-types.git",

breaks our build. Why isn't prop-types using the official package?

**Comment by albertkim** [comment]
I hit the same problem, and with some node_modules searching, found that this package is using a strange fork of prop-types. Why is that?

For some reason, `2.13.6` has disappeared from the registry, so I have rolled my package.json react-color version to `2.13.5`. It appears to be working so far.

**Comment by casesandberg** [comment]
Sorry about that, it has been changed back in `react-color@2.13.8`
