### ISSUE TITLE
React 0.14

### ISSUE THREAD

**Issue by dmr** [casesandberg/react-color#42]
Is anybody already using react-color together with react 0.14.0-beta1?

From my experience porting other projects mostly removing getDOMNode() and findDOMNode() is enough to make it work.

```
-    var container = React.findDOMNode(this.refs.container);
+    var container = this.refs.container;
```

**Comment by u9520107** [comment]
yeah... kinda need these changes to play with Relay, which requires react >= 0.14.0-beta3.

**Comment by u9520107** [comment]
After hunting down the findDOMNode uses, things in the src should be easily fixed.
I am not sure exactly how the modules folder works though.
Those are already transpiled to es5, but some of them uses React.findDOMNode as well.

**Comment by dmr** [comment]
Thank you, I'll close this because the topic will pop up once react is out of rc.

**Comment by casesandberg** [comment]
Ah, good point!

I will get @u9520107's stuff merged into a new branch for `0.14.0` this week and will merge that into master when its out of rc

**Comment by asbjornenge** [comment]
Any progress here? I'm seeing the following trying to use with 0.14:

```
Warning: ColorPicker(...): React component classes must extend React.Component
invariant.js:39Uncaught Error: Invariant Violation: ColorPicker.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.
```

My Component:

```js
import React from 'react'
import ColorPicker from 'react-color'

export default class ShipShop extends React.Component {
    render() {
        return (
            <div className="ShipShop">
                <ColorPicker />
            </div>
        )
    }
}
```

Ideas?

**Comment by fabriciomoeller** [comment]
I've got the same error.

**Comment by u9520107** [comment]
The last time I saw similar warnings, I was loading multiple versions of React and mixing them together. The components extending one version will not be recognized as a react component by another version.

Just a guess though.

**Comment by casesandberg** [comment]
Sorry for the delay on this guys. This has been aligned with react `0.14.0` you can use it by updating to `react-color@1.2.0`
