### ISSUE TITLE
Question about onChange parameter with @types

### ISSUE THREAD

**Issue by doronbrikman** [casesandberg/react-color#423]
I think I have an issue with the `@types` of the project.
I want to know if it's on purpose or it's wrong.

Let's say I have a component that use the `SketchPicker` component but also wrapped with `CustomPicker`.
In my component I save the state of the color from the `SketchPicker` and when the user click OK I call the `onChange` function from what the `CustomPicker` HOC gives me.

But as the `@types` suggests, the `onChange` function is accepting only a `ColorResult` but as I saw in the source code, it seems that it knows to get a `Color`:

ColorWrap.js:
```
handleChange = (data, event) => {
    ...
        const colors = color.toState(data, data.h || this.state.oldHue)
        ...
```

color.js:
```
toState(data, oldHue) {
    const color = data.hex ? tinycolor(data.hex) : tinycolor(data)
    ...
```

So, this is wrong? or I didn't understand something and it's ok?

My component for reference:

```
@CustomPicker
export class SketchDialog extends React.Component<Props & InjectedColorProps> {
    colorResult: ColorResult; // Should be "Color" type?

    componentWillMount() {
        const { hex, rgb, hsl } = this.props;
        this.colorResult = { hex, rgb, hsl };
    }

    onChangeComplete = (colorResult: ColorResult) => {
        this.colorResult = colorResult;
    }

    onOk = () => {
        this.props.onChange(this.colorResult); // <- I wish to send just a "Color" type here
    }

    render() {
        return (
            <div>
                <SketchPicker 
                     color={this.props.hex} 
                     onChangeComplete={this.onChangeComplete} 
                     presetColors={[]} 
                 />
                <button onClick={this.onOk} />
            </div>
        );
    }
}
```

**Comment by doronbrikman** [comment]
It seems that if we change the ColorWrap.d.ts file to this:

```
import { ComponentClass, StatelessComponent } from "react";
import { HSLColor, RGBColor, ColorChangeHandler, Color, ColorResult } from "react-color";

export interface InjectedColorProps {
    hex: string;
    hsl: HSLColor;
    rgb: RGBColor;
    onChange: (color: Color | ColorResult) => void;
}

export interface ExportedColorProps {
    color?: Color;
    onChange?: ColorChangeHandler;
    onChangeComplete?: ColorChangeHandler;
}

export default function CustomPicker<A>(component: ComponentClass<A & InjectedColorProps> | StatelessComponent<A & InjectedColorProps>): ComponentClass<A & ExportedColorProps>;
```

it will be fixed.
I will try to make a PR later.

Do you have some comments on this until then?

**Comment by doronbrikman** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19730

**Comment by casesandberg** [comment]
Ah, this is great! Yeah, its a bit tough with changes because that gets out of date. I touched on it in [my v3 proposal](https://github.com/casesandberg/react-color/issues/413), where I think we will want to export our own ts and flow definition files!

**Comment by doronbrikman** [comment]
My PR has merged, so I'm closing this issue.
