### ISSUE TITLE
How do I use it in the browser?

### ISSUE THREAD

**Issue by imsheng** [casesandberg/react-color#425]
How do I use it in the browser? 
http://casesandberg.github.io/react-color/

**Comment by casesandberg** [comment]
I am not sure I understand your question, could you be more specific?

**Comment by imsheng** [comment]
can you provide an HTML example?
css js and html
run in browser, not on server

**Comment by casesandberg** [comment]
This project only works with React and something like [Webpack](https://github.com/webpack/webpack) or [Create React App](https://github.com/facebookincubator/create-react-app). You can see a basic example and implementation here: https://github.com/casesandberg/react-color/tree/master/examples/basic

**Comment by imsheng** [comment]
It would be better if you could provide the jQuery version ，I think a lot of people will need it，just as beautiful as home page

**Comment by casesandberg** [comment]
This is react-specific project, there are currently no plans to port it
over to any other frameworks.

If you have some time you should fork the repo and modify it to work with
jQuery, I would love to see it!

**Comment by casesandberg** [comment]
You can now use react-color stand alone in the browser in the new beta. You will still have to use react and reactDOM, but you can just find minified versions of them hosted online:

https://github.com/casesandberg/react-color/blob/3.0.0/examples/with-umd/index.html
