### ISSUE TITLE
Trademark concern

### ISSUE THREAD

**Issue by akihikodaki** [casesandberg/react-color#427]
Hi, this library looks nice and I'm really interested in using this library in production.
However, I wonder the usage of trademarks throughout the project could be problematic. For example,
> A Collection of Color Pickers from Sketch, Photoshop, Chrome, Github, Twitter, Material Design & more

That sounds if the implementation is same with, not a clone of ones of those projects.
Also, I wonder whether it is allowed to use the names of those products as the identifiers of interfaces.

I suggest:
* to change the documentation to explicit the implementations are clone
* Rename components (`Sketch` to `Palette`, `GitHub` to `Tile`, for example)

I can make a pull request if you'd like.
Thanks.

**Comment by casesandberg** [comment]
While I don't feel comfortable renaming the components, I think we can change up the messaging in the new 3.0.0 launch to be a bit more generic:  `A Collection of Color Pickers From Your Favorite Apps and Interfaces`. I'm going to attach this to the 3.0.0 milestone so we can track it there.
