### ISSUE TITLE
React Native support?

### ISSUE THREAD

**Issue by jomnius** [casesandberg/react-color#438]
Just started looking at React Native, so this is most likely a stupid question: can **react-color** be used in react native project?

From already closed issues I found a ticket saying that this component has been used in iPhone, but maybe it was inside a web browser? At least I could make this work:

```javascript
<View style = {{ flxex: 1 }}>
<PhotoshopPicker onChangeComplete={ this.handleChangeComplete } />;
</View>
```

Got error note **"Invariant Violation: View config not found for name div"**

**Comment by casesandberg** [comment]
`react-color` does not currently work in React native, however it will in the new 3.0.0 release that is in development https://github.com/casesandberg/react-color/issues/413

**Comment by jomnius** [comment]
Great, added my comment in there! Closing this ticket.

**Comment by shravyaramesh** [comment]
Does it work in react-native now??

**Comment by nathalia-rus** [comment]
Also wondering whether it works in React Native now :) ?

**Comment by shravyaramesh** [comment]
I’m not sure. I actually needed typescript support so I ended up creating one from scratch.

**Comment by jkliptonia** [comment]
How about now?
