### ISSUE TITLE
PresetColors in Component API

### ISSUE THREAD

**Issue by hellocreep** [casesandberg/react-color#44]
Hi,

There's a situation in my project, I need to use my own preset colors in the sketch color picker.

Do you have any plan to add the resetColors to the Component API ?

**Comment by casesandberg** [comment]
Yep, there totally is! I need to add it to the documentation. 

If you pass it `presetColors` as an array of hex colors that will do the trick!

https://github.com/casesandberg/react-color/blob/master/src/components/sketch/Sketch.jsx#L121
