### ISSUE TITLE
Build size & sub-components path

### ISSUE THREAD

**Issue by faiwer** [casesandberg/react-color#440]
Hello, this issue is about a bundle size. The next line from the `Include the Component` chapter of the readme:
```js
import { SketchPicker } from 'react-color';
```
- +120 KiB to bundle
- +25 KiB in gzip

```js
import SketchPicker from 'react-color/lib/components/sketch/Sketch';
```
- +66 KiB
- +11 KiB in gzip

Second variant is better, of course. But `/lib/components/sketch/` it's the insides of the library. It can change in the future. I think `react-color/sketch` is better, is it?

**Comment by casesandberg** [comment]
Yes, you are correct! There was actually a PR merged a month ago that fixes this, it places references to the individual components in the root of lib: https://github.com/casesandberg/react-color/pull/356
