### ISSUE TITLE
Track MousePosition

### ISSUE THREAD

**Issue by ant45de** [casesandberg/react-color#445]
Visit your [DemoPage](https://casesandberg.github.io/react-color/).
Drag the control element in the right bottom corner in Photoshop-/Chrome-/Sketch-Editor.
The control element will jump to the left bottom corner. This behaviour is the same for all points on the bottom line.
It would be nice to be able to drag the control element everywhere on the bottom line and prevent the jump to the left corner.

**Comment by casesandberg** [comment]
Yes! This is being actively developed in v3.0.0

**Comment by casesandberg** [comment]
Going to close this and keep track of it via: https://github.com/casesandberg/react-color/issues/404
