### ISSUE TITLE
 Cannot find module 'react-color'.

### ISSUE THREAD

**Issue by n-for-all** [casesandberg/react-color#449]
npm install react-color --save doesn't install the src directory, seems to be a problem in packages.json file.

can you please look into it?

thanks

**Comment by alampros** [comment]
The `/src` directory is not published to npm by design (see the [.npmignore](https://github.com/casesandberg/react-color/blob/master/.npmignore) file). Only the files needed to consume the module (most importantly the transpiled `/lib` directory) are published.

**Comment by n-for-all** [comment]
Using "import" shows module not found, i tried removing and installing again, also updated npm without luck, there is no /lib directory in the react-color folder.

![image](https://user-images.githubusercontent.com/171367/33799003-92e609c0-dd3c-11e7-9bfe-c3eea925274d.png)

**Comment by casesandberg** [comment]
This seems to be an old version of react-color. Can you look in the package.json and let me know what version number it is?
