### ISSUE TITLE
Wrong case of Sketch directory causes building error

### ISSUE THREAD

**Issue by fmontaigne** [casesandberg/react-color#45]
Hi,

First, thanks for you work on this component.

Running locally on my mac the build of the module is ok but on a linux environnement, npm can't find the Sketch file in the "sketch" directory because of case sensitivity.

The directory /lib/components/Sketch should be renamed to /lib/components/sketch

Thanks!

**Comment by casesandberg** [comment]
I just fixed this in `1.1.1` update to that via npm!
