### ISSUE TITLE
Color picker is not selecting what you click

### ISSUE THREAD

**Issue by vudduu** [casesandberg/react-color#455]
Environment: react + react-color (2.13.8)
Demo: [https://codesandbox.io/s/xrz36m842p](https://codesandbox.io/s/xrz36m842p)

Drag circle selector from black (#000000) to white (#FFFFFF) suddenly when moving the cursor you will see that instead of only select shades of grey in the path to white, it sometimes will select other colors.

Also the bug appears when you click on that special gray colors.

**2.13.5 works well**

**Comment by m10** [comment]
i can confirm this issue. dragging towards/away from the bottom or left edge (just a few pixels) exibits this behaviour too

**Comment by workshur** [comment]
i can confirm this issue too

**Comment by casesandberg** [comment]
This is being fixed in 3.0.0 and being tracked here: https://github.com/casesandberg/react-color/issues/404

**Comment by DenisBelkin** [comment]
Same problem

p.s. have this problem on 2.13.5 version too
