### ISSUE TITLE
Problems storing multiple colors when hue slider is changing

### ISSUE THREAD

**Issue by ghost** [casesandberg/react-color#457]
I'm using a custom picker similar to `<SketchPicker />`, and I'm storing the colors that I select in one array. The problem here is when I change the color view, using the hue slider, in the picker to select a new one. When I move the slider the pointer is automatically selecting the color that is changing in the color view of the picker and storing it in my array, and I don't want that. I thought it was problem of my custom picker and I replaced it with the `<SketchPicker />` but the problem is the same.

Is there a way to avoid this? Because I want to store the colors in my array when the user picks one, not automatically when the hue slider is changing.

Thanks in advance!

**Comment by casesandberg** [comment]
Can you paste a code example? It sounds like you are updating the state of the array on change which would be causing this issue.

**Comment by casesandberg** [comment]
I am going to go ahead and close this. If you are still having an issue please try using the newest version of this package. Otherwise, you can open a new issue.
