### ISSUE TITLE
TwitterPicker hover event changes the color in the selector input

### ISSUE THREAD

**Issue by rhernandog** [casesandberg/react-color#459]
Hi,

When I include a `onSwatchHover` to the twitter picker component, in the input at the end of the color swatches the color HEX code changes to the one being hovered, but it doesn't returns to the current selected color. Without the `onSwatchHover` event handler, the component works as expected, the color in the input field is not updated on hover, just on click.

The behavior that I expect is the color to be updated only in the `onClick` event regardless if a mouse over event is present.

Here's a live sample with the issue:
[![Edit n72ojn8jkm](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n72ojn8jkm)

If you run the sample and hover over any swatch, you'll see the color hex code updated in the input field. If you delete the code in line 27 on `index.js` you won't see that and the color code will update only with the `onClick` event.

**Comment by casesandberg** [comment]
This is quite bizarre.
