### ISSUE TITLE
Support valueLink semantics

### ISSUE THREAD

**Issue by jaredp** [casesandberg/react-color#46]
See https://facebook.github.io/react/docs/two-way-binding-helpers.html

**Comment by casesandberg** [comment]
Thanks for the suggestion!

My solution for not managing a bunch of two-way binding for each input was to just create a custom input component that just handles it for itself and just using a bunch of those input components. https://github.com/casesandberg/react-color/blob/master/src/components/common/EditableInput.jsx#L62-L72

This solution wouldn't really work as its currently implemented, as the has to call a callback to pass its value back up to a higher component.
