### ISSUE TITLE
Request: Remove Hard Coded Fonts

### ISSUE THREAD

**Issue by ericlowry** [casesandberg/react-color#460]
Hey There!
  Just started using react-color, so far it seems great.

  A minor thing, but in the ChromePicker, you have hardcoded the font-family to "Menlo" in the component style.  I can't figure out how to override it... my css style gets overridden by your component style.

Here is the offending line:

https://github.com/casesandberg/react-color/blob/3270a7f42cbfa185a03ac8d7d7bd6e7e7d3170c5/src/components/chrome/Chrome.js#L20

Maybe it was by design?  but, I don't really want to make my own just to get the component to use my font-family ;-)

Thanks!

Eric

**Comment by casesandberg** [comment]
The original decision was made to try and make the components look exactly the same as their counterparts. I think now though, consistency in your app makes more sense so all of the hard-coded fonts should be removed.

**Comment by ericlowry** [comment]
This is great news!

**Comment by dmk255** [comment]
Should this be closed before it is implemented in 3.0.0
