### ISSUE TITLE
examples are not using current project of react-color

### ISSUE THREAD

**Issue by hamavb** [casesandberg/react-color#462]
example projects are using a react-color version required by [@storybook/addon-knobs](https://github.com/storybooks/storybook/blob/master/addons/knobs/package.json) that's a devDeps of react-color.
I doubt that this's by design ? or am i missing something ?

```javascript
"@storybook/addon-knobs": {
      "version": "3.3.9",
      "resolved": "https://registry.npmjs.org/@storybook/addon-knobs/-/addon-knobs-3.3.9.tgz",
      "integrity": "sha512-...",
      "dev": true,
      "requires": {
        "babel-runtime": "6.26.0",
        "deep-equal": "1.0.1",
        "global": "4.3.2",
        "insert-css": "2.0.0",
        "lodash.debounce": "4.0.8",
        "moment": "2.20.1",
        "prop-types": "15.6.0",
        "react-color": "2.13.8", // <-- specific version of react-color
        "react-datetime": "2.11.1",
        "react-textarea-autosize": "5.2.1",
        "util-deprecate": "1.0.2"
      }
}
```

**update**: looking at a related pull requests #436, react-color was added as dependency with `latest` tag which pretty much fix the issue about this ticket.

Thought importing react-color relatively from current project would ease development by allowing testing current updates... 

feel free to close this ticket.

**Comment by casesandberg** [comment]
Thanks for bringing this up! We originally had relative paths but decided it would be better going forward for it to link to the package via npm so that the examples would be standalone
