### ISSUE TITLE
PhotoShop Picker onAccept onCancel not working?

### ISSUE THREAD

**Issue by noahkingUNC** [casesandberg/react-color#464]
I'm trying to run to separate functions when someone clicks the OK and Cancel button but I'm not sure if there's an issue or my syntax is wrong. This is what I have when using the input box that shows the color and opens up on click. Using React version 16.2.0

Wouldn't I just put inside <PhotoshopPicker onAccept={this.function} onCancel={this.anotherFunction} /> ?

Here's my code 

    return (
      <div>
        <div style={styles.swatch} onClick={this.handleClick}>
          <div style={styles.color} />
        </div>
        { this.state.displayColorPicker ? <div style={styles.popover} >
          <div style={styles.cover} onClick={this.handleClose} />
        <PhotoshopPicker color={this.state.color} onChange={() => console.log('testing 123')} 
          onAccept={() => console.log('yay')} />
        </div> : null }
      </div>
    )

**Comment by noahkingUNC** [comment]
Figured it out. The closing tag on the div about PhotoshopPicker was causing the issue.

**Comment by waynebloss** [comment]
How did your closing tag cause the issue?

I'm having the same problem, here is my code:

```jsx
        {this.state.show ? (
          <div className="ColorInput-popup">
            <div className="ColorInput-cover" onClick={this.handleClose} />
            <PhotoshopPicker
              {...options}
              color={this.state.color}
              onChangeComplete={this.handleChange}
              onAccept={this.acceptChange}
            />
          </div>
        ) : null}
```

`onChangeComplete` gets called, no problem.

I'm not sure how a closing tag could cause this because the JSX compiles just fine.

**Comment by waynebloss** [comment]
OK, I figured it out - You meant to say the `div` that has the `onClick={handleClose}` above the picker was causing it. A closing tag in the parlance of HTML and JSX is just a `</div>`.

Removing that `div` did fix the problem. Thanks.
