### ISSUE TITLE
SketchPicker width does not work correctly

### ISSUE THREAD

**Issue by JonathanWbn** [casesandberg/react-color#468]
In the SketchPicker component, the width property does not end up being the width of the component, but 20px more.
You can check it out even on the official demo: [https://casesandberg.github.io/react-color/](url).
The SketchPicker has a default width of 200px, but actually has a width of 220px. It always adds the padding (10px on the left, 10px on the right) to the actual width.

This could be fixed by just setting the `box-sizing` to `border-box` instead of `initial`.

I'm happy to submit a PR for this, but I am not sure if this can just get released since it will change the width with any current implementation.

**Comment by casesandberg** [comment]
Ah, I agree. It's not _really_ a breaking change, but I am going to track it in the 3.0.0 release so that it doesn't cause issues.
