### ISSUE TITLE
Add Example Using Portals

### ISSUE THREAD

**Issue by casesandberg** [casesandberg/react-color#482]

**Comment by comfroels** [comment]
Is portal functionality included in version 2.17.3? Or is this a thing that only 3.0.0 will have? We're needing this feature and I'd be willing to help out with it, if necessary.

**Comment by casesandberg** [comment]
Great! We currently don’t have any example with portals, but I would be more than happy to put one together for you.

Sent via Superhuman iOS ( https://sprh.mn/?vip=case@casesandberg.com )
