### ISSUE TITLE
SketchFields movementX is undefined

### ISSUE THREAD

**Issue by UXDart** [casesandberg/react-color#486]
Hello. it seems not many people is using the Sketch component... or at least the beta... on handleDrag() of EditableInput it is using movementX, but is not supported by many browsers. for what I know it should work on Chrome, but it doesn't. so the solution is to use screenX and save the prev value. movementX  = e.screenX - prevScreenX

HTH

**Comment by casesandberg** [comment]
Thanks for checking out the beta. Its not in a working state at the moment, you are correct.
