### ISSUE TITLE
Unable to use rgba colors in swatches

### ISSUE THREAD

**Issue by kriscarle** [casesandberg/react-color#488]
As of 2.14.0,  swatches will only accept hex values, while previously it worked with any valid value recognized by TinyColor including rbga. This appears to be introduced by #461 

My app uses transparency by default and I want the palette to appear the same as what is the user sees after the selection. 

Would it work to switch components without a manual hex input back to just `tinycolor(color).isValid()`?

**Comment by casesandberg** [comment]
Ah, that makes sense. Mind putting up a PR that reverts that change?

**Comment by glenselle** [comment]
We're hitting this issue too. We'd love to have a transparent option in our UI but the change event won't fire. If the change in https://github.com/casesandberg/react-color/pull/461 is reverted the current logic will cause the bug in https://github.com/casesandberg/react-color/issues/432 to resurface. It sounds like the solution is to support hex8 which would allow for an alpha value per the comment here https://github.com/casesandberg/react-color/issues/432#issuecomment-339823010 by @elvisvoer 

@kriscarle You mentioned working on a PR -- is this how you were planning to implement it?

As long as supporting hex8 is not a massive change I'd be willing to work on a PR for this.

**Comment by tamias** [comment]
I've also just encountered this issue.  I wanted to pass `'transparent'` as a color to the Swatches component; the swatch is correctly rendered as a checkerboard, but the change event doesn't fire.

Should passing `'transparent'` work, and if so, what arguments should be passed to the change event?
