### ISSUE TITLE
Updating to 1.2.0 throws error

### ISSUE THREAD

**Issue by enjoylife** [casesandberg/react-color#49]
`Uncaught Error: Invariant Violation: ColorPicker.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.`

**Comment by casesandberg** [comment]
Are you using react `0.14.0` ?

**Comment by jedwards1211** [comment]
Wow, I decided to dump the last color picker component I was using because of that error (and because this was is way better.  I first saw that with React 0.14 and I think it's a bug.

**Comment by casesandberg** [comment]
Looking into this later today, sorry for the trouble

**Comment by jedwards1211** [comment]
Sorry, I meant I think it's a bug with React 0.14.  `React.isValidElement` was returning false for some `div` because React hadn't attached a secret property to it.  I don't know why

**Comment by casesandberg** [comment]
Oh, even more interesting! I will do some snooping and see if I can fix it

**Comment by jedwards1211** [comment]
Admittedly, I should have kept a record of what I saw with the other color picker I was previously using.

The error when `ReactElement.isValidElement` below returns false:
`ReactCompositeComponent.js`:
```js
/**
   * @private
   */
  _renderValidatedComponent: function () {
    var renderedComponent;
    ReactCurrentOwner.current = this;
    try {
      renderedComponent = this._renderValidatedComponentWithoutOwnerOrContext();
    } finally {
      ReactCurrentOwner.current = null;
    }
    !(
    // TODO: An `isValidNode` function would probably be more appropriate
    renderedComponent === null || renderedComponent === false || ReactElement.isValidElement(renderedComponent)) ? process.env.NODE_ENV !== 'production' ? invariant(false, '%s.render(): A valid ReactComponent must be returned. You may have ' + 'returned undefined, an array or some other invalid object.', this.getName() || 'ReactCompositeComponent') : invariant(false) : undefined;
    return renderedComponent;
  },
```

It was returning false becase `object.$$typeof` below was `undefined`.  What I didn't figure out is why it was undefined.
`ReactElement.js`:
```js
/**
 * @param {?object} object
 * @return {boolean} True if `object` is a valid component.
 * @final
 */
ReactElement.isValidElement = function (object) {
  return typeof object === 'object' && object !== null && object.$$typeof === REACT_ELEMENT_TYPE;
};
```

**Comment by enjoylife** [comment]
it was just a issue with mixed react versions. Fixed once I upgraded to v0.14 across all my dependencies.

**Comment by jedwards1211** [comment]
Aha, good catch!  I think that was what was causing the problem with the other colorpicker I was using -- it did something silly like look for React in `window.React` and then requiring it if it didn't find it there.  So it was probably requiring an old version.

**Comment by casesandberg** [comment]
Really good catch! I will see if there is some error handling I can put in to throw a warning about this.
