### ISSUE TITLE
Alpha value textbox incorrect after first removing focus

### ISSUE THREAD

**Issue by nt1m** [casesandberg/react-color#492]
See https://github.com/mozilla/Themer/issues/159

**Comment by elvisvoer** [comment]
@nt1m can you try a build with the latest version because I cannot reproduce it in the latest version and the docs website is outdated.

**Comment by lmorchard** [comment]
Yeah, I'm thinking this has more to do with how we're trying to normalize values than an upstream issue with this component

**Comment by casesandberg** [comment]
Going to close this as it seems it has been resolved
