### ISSUE TITLE
Is there a way to customize the Picker to allow entering selected color in HEX only ?

### ISSUE THREAD

**Issue by alduro** [casesandberg/react-color#493]
<img width="291" alt="color_picker" src="https://user-images.githubusercontent.com/183364/38091580-4e29f426-333c-11e8-9c38-fa54e2770933.png">

Thanks in advance.

**Comment by davishyer** [comment]
From the README: `disableAlpha - Bool, Remove alpha slider and options from picker. Default false`

If you set this prop to true, you can remove the alpha slider. I don't see a way to remove the input field however. If you are looking to only get the saturation and hue, you could create your own component based on the CustomPicker (see https://casesandberg.github.io/react-color/#create)

**Comment by alduro** [comment]
thanks @davishyer I will try it.
