### ISSUE TITLE
Remove usages of unsafe lifecycle methods

### ISSUE THREAD

**Issue by Hypnosphi** [casesandberg/react-color#494]
React team recently published a blogpost: https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

TL;DR: `cWM`, `cWRP`, and `cWU` methods are considered unsafe for future async rendering and will be deprecated soon. The recommended way for open source maintainers to deal with it is to use [`react-lifecycles-compat`](https://github.com/reactjs/react-lifecycles-compat) package and migrate to new `static getDerivedStateToProps` method

**Comment by casesandberg** [comment]
We are upgrading to react@16 in the new major we are working on and will be removing all of them.
