### ISSUE TITLE
How to change the colors displayed on the TwitterPicker by default

### ISSUE THREAD

**Issue by aixinalei** [casesandberg/react-color#507]
I want to customize several colors displayed on TwitterPicker.
How can I do it？

**Comment by aixinalei** [comment]
The available API is colors 。。。

**Comment by studioraygun** [comment]
This should be explained more clearly. Example:

`// Set some default colours`
`const myColors = ['#000000', '#ffffc1']`
`// Pass myColors into the component`
`<TwitterPicker colors={myColors} color={ this.state.color } onChange={ this.handleChange } />`
