### ISSUE TITLE
Hash mark missing from `color.hex` passed to `onChange` handler

### ISSUE THREAD

**Issue by jedwards1211** [casesandberg/react-color#51]
![image](https://cloud.githubusercontent.com/assets/1448194/10519261/ab1620e4-732a-11e5-8f61-916a77bec539.png)

```jsx
    let colorPicker = <div>
      <Button onClick={ this.onColorClick } style={{backgroundColor: color}}/>
      <ColorPicker display={ displayColorPicker } type="swatches" onChange={this.onColorChange}/>
    </div>;
```

**Comment by mijamo** [comment]
Same issue with onChangeComplete

**Comment by casesandberg** [comment]
Fixed in `react-color@1.3.8`

**Comment by vdh** [comment]
This bug has returned as of 2.0.0, onChange & onChangeComplete returns a hex with no hash

**Comment by islemaster** [comment]
Seeing the same thing.  Master branch seems okay, but the 2.0.0 I get from npm contains the hash fix in the `/src` directory but not the `/lib` directory.  It's possible the published `/lib` is out of date.
