### ISSUE TITLE
Add alpha channel to hex format

### ISSUE THREAD

**Issue by json2d** [casesandberg/react-color#510]
Hex format is most compact, but lacks the alpha channel. These are supported in CSS:  https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#Syntax_2 So seems like why not, else the hex format is only useful when you dont need alpha

**Comment by leewz** [comment]
From what I understand, tinycolor added support for the #RGBA and #RRGGBBAA forms, but it was blocked by react-color because it was breaking text input of hex values (issue #432: "Chrome hex input bug").

It may be necessary to have both `isValidHex` and `isValidHex4`, with each text input box saying whether it accepts 3-channel and/or 4-channel forms.

**Comment by bitstrider** [comment]
Ah so to getting support for hex4/hex8 back is a matter of resolving #432

**Comment by casesandberg** [comment]
This can be achieved by combining the returned values:

```
handleChange = (color) => {
  console.log(color.hex + (color.rgb.a * 100)) // '#fafafa60'
}
```

Is this what you were looking for?

**Comment by bitstrider** [comment]
Yeah this works to get the hex string /w alpha, but then I'd also need to convert it back to rgba format when assigning to the `color` prop, since it only takes hex string w/o alpha. Doable but seems like a bulky approach and thought it'd be better just to add support for it within the component.

Right now I'm just sticking with the rgba object format with no issues, just would be easier to work with the hex string format especially when working with CSS

**Comment by yonatanmn** [comment]
Hex + alpha should also be in hex. so I guess: 
`color.hex + Math.round(color.rgb.a * 255).toString(16)) `
Works for me

**Comment by casesandberg** [comment]
I am going to go ahead and close this. We are changing the way hex colors are handled in the new version and this will no longer be an issue.

**Comment by hug0b** [comment]
Any news on supporting #RRGGBBAA ?
https://caniuse.com/#feat=css-rrggbbaa

**Comment by furnaceX** [comment]
> I am going to go ahead and close this. We are changing the way hex colors are handled in the new version and this will no longer be an issue.

Any update on this? Seems that HEX doesn't yet support alpha.

**Comment by aboveyunhai** [comment]
> @casesandberg Hex + alpha should also be in hex. so I guess:
> `color.hex + Math.round(color.rgb.a * 255).toString(16)) `
> Works for me

Just want to further expand the conversion. This will be broken when alpha convert to single digit so you want to add leading `0`.

```
var alpha = Math.round(color.rgb.a * 255).toString(16));
if(alpha.length < 2) alpha = '0' + alpha;
const hexWithAlpha = hex + alpha;
```

**Comment by arpitjp** [comment]
@casesandberg Any update on the alpha value support? Will be glad to raise a PR if you can review & merge it

**Comment by Ahsan-Ullah1871** [comment]
> I am going to go ahead and close this. We are changing the way hex colors are handled in the new version and this will no longer be an issue.

Hi @casesandberg  Is there have any update on this feature ?

**Comment by streamlinellc** [comment]
For anyone else looking juse use these functions to do what you need to do


```
function rgbToHexWithAlpha(rgb: { r: number; g: number; b: number; a: number }): string {
    const toHex = (value: number) => {
       const hex = value.toString(16);
       return hex.length === 1 ? "0" + hex : hex;
    };
  
    const r = toHex(rgb.r);
    const g = toHex(rgb.g);
    const b = toHex(rgb.b);
    const a = toHex(Math.round(rgb.a * 255));
  
    return `#${r}${g}${b}${a}`;
 }
 function hexWithAlphaToRgba(hex: string): { r: number; g: number; b: number; a: number } {
    if (!hex) return { r: 0, g: 0, b: 0, a: 1 };
    const hexWithoutHash = hex.replace("#", "");
    const r = parseInt(hexWithoutHash.substring(0, 2), 16);
    const g = parseInt(hexWithoutHash.substring(2, 4), 16);
    const b = parseInt(hexWithoutHash.substring(4, 6), 16);
    const a = parseInt(hexWithoutHash.substring(6, 8), 16) / 255;
  
    return { r, g, b, a };
 }
```

**Comment by denisbetsi** [comment]
For anyone else looking juse use these functions to do what you need to do

```typescript
function rgbToHexWithAlpha(rgb: { r: number; g: number; b: number; a: number }): string {
    const toHex = (value: number) => {
       const hex = value.toString(16);
       return hex.length === 1 ? "0" + hex : hex;
    };
  
    const r = toHex(rgb.r);
    const g = toHex(rgb.g);
    const b = toHex(rgb.b);
    const a = toHex(Math.round(rgb.a * 255));
  
    return `#${r}${g}${b}${a}`;
 }
 function hexWithAlphaToRgba(hex: string): { r: number; g: number; b: number; a: number } {
    if (!hex) return { r: 0, g: 0, b: 0, a: 1 };
    const hexWithoutHash = hex.replace("#", "");
    const r = parseInt(hexWithoutHash.substring(0, 2), 16);
    const g = parseInt(hexWithoutHash.substring(2, 4), 16);
    const b = parseInt(hexWithoutHash.substring(4, 6), 16);
    const a = parseInt(hexWithoutHash.substring(6, 8), 16) / 255;
  
    return { r, g, b, a };
 }
```
