### ISSUE TITLE
BlockPicker: don't invoke onChangeComplete when typing an hex color in EditableInput

### ISSUE THREAD

**Issue by ibc** [casesandberg/react-color#512]
Currently, as far as I type `#000` in the `EditableInput` within the `BlockPicker`, the `onChangeComplete` prop is called.

Well, actually I wanted to type `#000FFF`. Could `onChangeComplete` be called just when Enter is pressed or something like that?

**Comment by MattNot** [comment]
Same problem, only 3 chars... why?

**Comment by casesandberg** [comment]
I can indeed reproduce this here: https://codesandbox.io/s/0vo3zz6450. This is a bug.

**Comment by jakobsandberg** [comment]
@casesandberg what's the expected behaviour here?

**Comment by kinhbang89** [comment]
Hi I have been facing the same issue and I have noticed that when I typed valid hex color on the EditableInput, the library checker  _color.isValidHex(hexCode)_ is wrong in onChange handler because the hexCode is **{undefined: "#22194E"}**.

**Comment by erkkaha** [comment]
Looks like the issue is here https://github.com/casesandberg/react-color/commit/aba3336489fb0c45d21a988903eb76c7f2ea640c#diff-4584130a5bc9a8717f47d3c842478b49R77
_this.props.label_ is undefined ie not _null_ . Can the check be for falsy values instead of strictly _null_?

**Comment by casesandberg** [comment]
Makes sense to me. Do you mind throwing up a PR with that fix?

Sent via Superhuman iOS ( https://sprh.mn/?vip=case@casesandberg.com )

**Comment by juan0087** [comment]
I'm on the latest version 2.17.3 and the problem is still there. The hex code on the BlockPicker does not update/save.

**Comment by uzeuze** [comment]
@juan0087 I had the same issue. It is resolved after downgrading to version `2.14.1`.

**Comment by erkkaha** [comment]
@casesandberg Would it be possible to get a new release to get this fixed?

**Comment by juan0087** [comment]
@uzeuze Thanks! I downgraded to 2.14.1 and it saves now, but when you type the hex value it takes the first 3 characters and closes popup.

**Comment by alexDixonDev23** [comment]
You can also change the **handleChange** function in the module to check **e.target.value** other than the **hexCode**, works perfectly now!

**Comment by alexDixonDev23** [comment]
If you add a separate function in the Block file for onClick and the input, checking the **e.target.value** for the input and **hexCode** for onClick, it works pretty well!

<img width="1631" alt="Screen Shot 2019-07-11 at 10 10 46 AM" src="https://user-images.githubusercontent.com/42189657/61070715-31724280-a3c4-11e9-8012-731a20f3dbe2.png">
<img width="748" alt="Screen Shot 2019-07-11 at 10 10 37 AM" src="https://user-images.githubusercontent.com/42189657/61070716-31724280-a3c4-11e9-842e-97414b8ea985.png">

**Comment by focux** [comment]
It seems that @erkkaha fix is in the [last release](https://github.com/casesandberg/react-color/releases/tag/v2.17.3) but it didn't fix the issue. I'll be glad to fix it and open a PR if @casesandberg thinks it's okay.

**Comment by erkkaha** [comment]
@focux If you see https://github.com/casesandberg/react-color/compare/v2.17.3...master and https://github.com/casesandberg/react-color/pull/616 Fix has not been released yet. Downgrading is a way to fix this issue until new release is out.

**Comment by Amonaval** [comment]
@casesandberg  Can we expect this issue to be resolved in the latest upcoming release ?

**Comment by lardissone** [comment]
Any updates on this? Bug is still present.

**Comment by monkeytroy** [comment]
It appears this is still an issue on TwitterPicker.  Anyone know a work around?
