### ISSUE TITLE
how to disable one or all input? disableAlpha seems not what used for this

### ISSUE THREAD

**Issue by adamchenwei** [casesandberg/react-color#513]
Is it even possible? I am open to hacky way to do it as well.
Disabled case meaning, like some sort of greyed out and not accessible state like regular input element when attached to the disabled state.

thanks

**Comment by casesandberg** [comment]
This can be achieved if you make your own custom color picker and pass disabled to the fields that you are looking to disable. All of the pickers are built on top of some common components: https://github.com/casesandberg/react-color/blob/master/src/components/material/Material.js
