### ISSUE TITLE
Passing width and height to swatches in SketchPresetColors

### ISSUE THREAD

**Issue by amcdevitt97** [casesandberg/react-color#517]
As far as I'm aware, `<SketchPresetColors />` only accepts the props `Colors`, `onClick`, and `onSwatchHover`. Trying to add styling to that element modifies the container holding the swatches rather than the swatches themselves. The only way to modify the size of the swatches is to go into [SketchPresetColors.js](https://github.com/casesandberg/react-color/blob/master/src/components/sketch/SketchPresetColors.js) and directly modify the `swatchWrap` CSS style, which I'm trying to avoid at all costs. I'd really appreciate the ability to just have width and height (for the swatches) as props of SketchPresetColors. 

For reference, I'm going off the advice from https://github.com/casesandberg/react-color/issues/343

**Comment by casesandberg** [comment]
Hmm. Unfortunately there is no easy way to do this right now without duplicating the component and making your own and changing those values. 

There is a _really hacky_ way of doing this with CSS until I can come up with a better fix. You can target those swatches like this:
```
.sketch-picker .flexbox-fix:last-child div {
    width: 40px !important;
    height: 40px !important;
}
```

**Comment by danny-wang** [comment]
> Hmm. Unfortunately there is no easy way to do this right now without duplicating the component and making your own and changing those values.
> 
> There is a _really hacky_ way of doing this with CSS until I can come up with a better fix. You can target those swatches like this:
> 
> ```
> .sketch-picker .flexbox-fix:last-child div {
>     width: 40px !important;
>     height: 40px !important;
> }
> ```

it really solve my problem. thanks
