### ISSUE TITLE
Remove title in swatchs

### ISSUE THREAD

**Issue by PabloEzeRomano** [casesandberg/react-color#518]
Hi! I'm using the CirclePicker component and I was wondering if there was a way to display a custom title in the swatches or not show the tooltip at all, like in the Sketch for example. Thanks!

**Comment by casesandberg** [comment]
Unfortunately, there isn't an easy to way to do that right now. The next version of react-color will make it trivial, but we are still a ways away from release

**Comment by acoop133** [comment]
Has this been added yet? Not being able to disable tooltip is quite annoying.

**Comment by ConstanzaCurzio** [comment]
Any updates on this?
