### ISSUE TITLE
Some of the swatch columns have varying hue

### ISSUE THREAD

**Issue by jedwards1211** [casesandberg/react-color#52]
In most of the swatch columns, all of the colors have the same exact hue.  But in a few (for example the top left one), some of the colors (e.g. the middle one) have a different hue and look noticeably off.  Was this intentional?  Just wanted to check

**Comment by casesandberg** [comment]
All of the colors are pulled directly from Material Design (with the exception of the one that is highlighted by default on the documentation [line 81]). https://github.com/casesandberg/react-color/blob/master/src/components/swatches/Swatches.js#L70-L91

I should really be passing down that hard-coded one as props though and have the library actually use the real material design color. I will try and change that tonight!

**Comment by frnhr** [comment]
@casesandberg Is it possible to use my own list of colors with the swatch mode? How do I set them?

**Comment by casesandberg** [comment]
I can roll out a fix tomorrow night. If you want to tweak it locally to make it work for now do:

On line 190 in lib/components/Color/js: (https://github.com/casesandberg/react-color/blob/master/lib/components/Color.js#L190) add this.props before state like so: 
```
React.createElement(Picker, _extends({}, this.props, this.state …
```
And then just pass down an array of arrays to the color prop and that should make it work:
```
<ColorPicker type="swatches" colors={[ ['#fff', '#eee', '#ddd'], ['#333', '#222', '#111'] ]} />
```
