### ISSUE TITLE
can't align the component anywhere 

### ISSUE THREAD

**Issue by obiwankenoobi** [casesandberg/react-color#522]
I am trying to simply align the component in a specific side of the screen (or even center it)  but I cant do it no matter what. Here is a simple example of two components inside the same 

```
                    <div>
                        <BlockPicker/>                      
                        <Button >color</Button>
                    </div>
```

please note how the `Button` is align perfectly in the center but the `BlockPicker` isnt. Its work that way no matter what kind of styling Im trying to implement on it. 

## note

when I tried to style the component I did it like that `<BlockPicker/>  style={Style.someStyle}`

![screen shot 2018-07-14 at 8 58 34](https://user-images.githubusercontent.com/24577941/42721479-2ecea674-8744-11e8-8856-62951a068c78.png)

**Comment by jalmarazg** [comment]
Came up with a similar problem and I solved it like this. 

1. Created a new component folder in which I generated 2 files 
- _CustomizedBlockPicker.css_
- _CustomizedBlockPicker.js_

2. Then in the CSS file I configured the following classes (Button one is optional)

```css
.center {
    margin: auto;
}

.button {
    background-color: aqua;
    margin-bottom: 10px;
}
```

3. After that, I created the component part importing the CSS classes and adding them to each part of it using "classname".

```jsx
import React from 'react';
import { BlockPicker } from 'react-color';
import './CustomizedBlockPicker.css';

const CustomizedBlockPicker = () => {
    return (
        <div>
            <button className = "button">color</button>
            <BlockPicker className = "center"/>    
        </div>
    );
}

export default CustomizedBlockPicker;
```

4. Import it where needed it, like the following:

```jsx
import React, {Component} from 'react';
import CustomizedBlockPicker from '../CustomizedBlockPicker/CustomizedBlockPicker'

class AnyClassYouWant extends Component {
render() {
        return(
            <div>
...
                <CustomizedBlockPicker />  
...  
            </div>)
    }
}
```

5. The code should return something like this:

![imageedit_2_3744419846](https://user-images.githubusercontent.com/9245962/43360191-a3b4af82-9276-11e8-9fc1-e43cda146b1f.gif)

**Comment by casesandberg** [comment]
Yes, this second solution is correct. You can also wrap the color picker in a div and add styling to do that div to center it
