### ISSUE TITLE
Unable to update alpha channel

### ISSUE THREAD

**Issue by nevendyulgerov** [casesandberg/react-color#523]
Upon setting state, the picker (`SketchPicker`) fails to update its internal state for alpha.

Steps to reproduce:

1. Open the picker
2. Select a color
3. Select an alpha (opacity)

Upon `setState` the color is updated properly. The alpha, however stays the same. **Please, note that the alpha is properly updated in the `color` object.** However, the picker always displays alpha `100` in the alpha drag range input.

**Comment by nevendyulgerov** [comment]
I figured it out - my initial state object schema was a bit different that the required one. Thanks for the great color picker!

**Comment by timojaask** [comment]
@nevendyulgerov I've got the same problem. Would you mind sharing the initial state object that worked for you?

**Comment by samerdernaika** [comment]
any idea for this ? plz

**Comment by samerdernaika** [comment]
this is the solution https://github.com/casesandberg/react-color/issues/750#issuecomment-684882202
