### ISSUE TITLE
react-color is quite source heavy, even when minified

### ISSUE THREAD

**Issue by Glutnix** [casesandberg/react-color#524]
Just including `<ChromePicker>` in our project added 800kb of uncompressed source code to our build - 4.6MB to 5.4MB. Our minified build went from 497kb to 606kb. 

I wonder what dependencies it really needs, and which could be optimised away...

**Comment by Glutnix** [comment]
I got it down to 57k by just requiring the chrome component file:
```import * as ChromePicker from 'react-color/lib/Chrome';```

As for size impact, I think the big culprit is lodash's debounce method.

**Comment by casesandberg** [comment]
You are correct, and size is the major focus of the rewrite. The best way currently is to import from the lib folder.

**Comment by jordymeow** [comment]
Hello,

I still find the bundle is quite heavy for what it does; any plans to make it smaller? I doubt the dependency on lodash is useful nowadays. This library seems to be the most used currently, but I guess most dependencies could be replaced.
