### ISSUE TITLE
Issues with TwitterPicker and Swatches

### ISSUE THREAD

**Issue by dextermb** [casesandberg/react-color#527]
Hey,

I'm having issues with the `TwitterPicker` when attempting to click a `Swatch`. Here's my code:
```
<TwitterPicker
	triangle={'hide'}
	color={project.color}
	colors={['red']}
	onChange={e => console.warn(e)}
/>
```

I checked the source code and `Swatch` has an [`onClick`](https://github.com/casesandberg/react-color/blob/master/src/components/twitter/Twitter.js#L133) prop that uses the same function as `onChange` for the text box within the `TwitterPicker` (which works fine). But for some reason I can't seem to get it to fire.

I am able to get an output from using [`onSwatchHover`](https://github.com/casesandberg/react-color/blob/master/src/components/twitter/Twitter.js#L134) but ideally I would like to be able to click a `Swatch` before setting the color.

Any ideas why this might not be working?

**Comment by casesandberg** [comment]
Are your swatches hex codes? It checks to make sure its a valid hexcode, maybe its failing there? https://github.com/casesandberg/react-color/blob/master/src/components/twitter/Twitter.js#L114

**Comment by dextermb** [comment]
@casesandberg Even when using the default colors it doesn't seem to work either

**Comment by casesandberg** [comment]
In terms of clicking a swatch before setting the color, you can just intercept the onChange and save that as state:
```
state = {
  temporaryColor: null,
}
<TwitterPicker
	color={project.color}
	colors={['red']}
	onChange={handleColorChange}
/>
```

**Comment by dextermb** [comment]
Any updates on this, @casesandberg?

**Comment by dextermb** [comment]
Hmm, it seems to only ignore clicks on the swatches when the picker first opens. After hiding it and remounting it, it then seems to work as expected.

**Comment by dextermb** [comment]
@casesandberg I haven't been on the project in a month now- I've been put on stuff.
