### ISSUE TITLE
Specify that the color parameter isn't optional

### ISSUE THREAD

**Issue by proevilz** [casesandberg/react-color#531]
If you do not use the `color` parameter on the Sketch component, it doesn't work correctly. The color changes but the draggable circle amongst other things do not update in position.

I feel as though you should specify this in the documentation if this _is_ the intended functionality.

See my [CodeSandbox](https://codesandbox.io/s/p702086pzq) for an example, I have remove `color={this.state.color}` from the component - add it to make it fully functional again.

**Comment by casesandberg** [comment]
This is a fantastic point. I am adding it to the 3.0.0 milestone to make sure it gets fixed in the new release
