### ISSUE TITLE
Solution for `display: flex` in older browsers

### ISSUE THREAD

**Issue by beat-the-buzzer** [casesandberg/react-color#534]
I want to know why not use css files because some broswers cannot know how to display flex.
If we use css files, we can use tools like `autoprefixer` to adapt some low version broswers.

**Comment by casesandberg** [comment]
We chose to use inline styles so that the components could be used easily without having to use a bundler or pipeline that requires CSS compilation. 

In the next major version that we are working on I will make sure to have a solution for flexbox in older browsers.
