### ISSUE TITLE
Blur `input` when clicking outside on a swatch

### ISSUE THREAD

**Issue by beat-the-buzzer** [casesandberg/react-color#535]
There is a bug.
When input area is focused, at the same time, if we click to change the color, this input area is not changed.
In other words, the input area should have been `blured`.

**Comment by adamdicarlo** [comment]
I am just a passerby, not the maintainer, but you're more likely to get attention on an issue with a descriptive title. It's also better manners. Instead of "there is a bug", name this something like "Doing X while Y should Z".

**Comment by jakobsandberg** [comment]
I can look into this guy

**Comment by casesandberg** [comment]
I am going to go ahead and close this as it no longer seems to be an issue. Please try using the newest version of this package and if you are still seeing it please open a new issue.
