### ISSUE TITLE
Everything is included [bundle size]

### ISSUE THREAD

**Issue by adjourn** [casesandberg/react-color#537]
I find the size of this wonderful package a big issue.

E.g the following imports result in 200Kb/130Kb/30Kb (stat/parsed/gzipped), **including dependencies.**

```js
import {CustomPicker} from 'react-color';
import {Alpha, Hue, Saturation} from 'react-color/lib/components/common';
```

It seems to include everything, including premade color pickers. Beta version is basically the same.
![davinci](https://user-images.githubusercontent.com/17890701/45598786-07d9cc00-b9ea-11e8-8678-f39870c404a3.png)

This is with 100% production settings (`Node process.env, Webpack --mode production`).

**Comment by purplesquirrels** [comment]
I haven't tested this for bundle size but try using separate imports to directly import each component, and then import ColorWrap from the common directory instead of CustomPicker (the default react-color import brings in all the colour pickers)

```js
import ColorWrap from "react-color/lib/components/common/ColorWrap";
import Alpha from "react-color/lib/components/common/Alpha";
import Hue from "react-color/lib/components/common/Hue";
import Saturation from "react-color/lib/components/common/Saturation";
```
