### ISSUE TITLE
Memory leak: Canvas element created for every checkboard get

### ISSUE THREAD

**Issue by greeze** [casesandberg/react-color#538]
[Line 25 of checkboard.js](https://github.com/casesandberg/react-color/blob/master/src/helpers/checkboard.js#L25-L30) calls `render` every time, even if the canvas has been cached. Line 25 should be moved after the cache check to prevent creating orphan canvases.

**Comment by casesandberg** [comment]
Great catch. Would you be open to putting up a PR fixing this issue?

**Comment by jakobsandberg** [comment]
Turns out I made a duplicate ticket for this issue, here is the open PR with the fix: https://github.com/casesandberg/react-color/pull/569

**Comment by casesandberg** [comment]
This was fixed with https://github.com/casesandberg/react-color/pull/546
