### ISSUE TITLE
Low percentage problem for `Saturation` 

### ISSUE THREAD

**Issue by unkernet** [casesandberg/react-color#539]
There is some glitch on saturation and brightness values between 0 and 1.
After f414b01760fffdab3031a0d1414541f2fa7442b4 you are using tinycolor2 from npm and have loose changes made in 65700534f6bf0c1937a7bcb0243be43792a3905d

**Comment by casesandberg** [comment]
This is a duplicate of https://github.com/casesandberg/react-color/issues/216. We are tracking this issue in the 3.0.0 version we are working on here: https://github.com/casesandberg/react-color/issues/404
