### ISSUE TITLE
Having multiple ChromePickers on the page, event problem

### ISSUE THREAD

**Issue by bogdantroanca** [casesandberg/react-color#544]
If there are more ChromePickers on one page, dragging away from one of them on the page or over other ChromePicker, all colors change chaotic.  

I made a codesandbox to see exactly what happens. For example, choose a color in the middle of both colopickers. Then, drag with the mouse inside the top colorpicker, and go in the second one with the left click still pressed. You will see the color in the bottom colorpicker will jump in the bottom left corner of the picker. So the event is not independent for each colorpicker, or something like this.

https://codesandbox.io/s/z3kr0oqm93

**Comment by casesandberg** [comment]
This must have to do with the draggable event handlers being attached to the document. We are working on a better solution in the next major release so that this won't be an issue. I will track this there to make sure it gets resolved.
