### ISSUE TITLE
Pass children down to Checkboard

### ISSUE THREAD

**Issue by BernardoFBBraga** [casesandberg/react-color#547]
I'd like to use checkboard as a background for a button.

e.g.

```
<Checkboard>
        <button/>
</Checkboard>
```

This would be very simple if https://github.com/casesandberg/react-color/blob/master/src/components/common/Checkboard.js passed down the children prop to the div

Would that be ok?

**Comment by casesandberg** [comment]
Sure. Feel free to open up a PR with the change.

**Comment by Saumya29** [comment]
Can I take this? @casesandberg
