### ISSUE TITLE
Can we position color-picker such that it remains inside viewport everytime ?

### ISSUE THREAD

**Issue by Rahulkr204** [casesandberg/react-color#551]
<img width="1112" alt="screen shot 2018-10-11 at 1 49 20 pm" src="https://user-images.githubusercontent.com/8544323/46790424-87925680-cd5c-11e8-90a6-34b640d94da0.png">
I want this popover to open on top.

**Comment by boiawang** [comment]
+1

**Comment by Rahulkr204** [comment]
Any updates in this issue ? @casesandberg

**Comment by casesandberg** [comment]
Positioning of the color-picker is outside the scope of this package. I would suggest using something like [react-popover](https://github.com/littlebits/react-popover) to handle positioning relative to the window.
