### ISSUE TITLE
Can it support positioning at level of body tag?

### ISSUE THREAD

**Issue by designlook** [casesandberg/react-color#553]
If I have it inside a drawer or side bar, it can get cut off due to overflow hidden of that DIV. Maybe have option to have div for color pop-up be after <body> tag?

**Comment by bertanyaman** [comment]
+1

**Comment by casesandberg** [comment]
Can you paste a code example of this? Positioning should be handled outside of this library and there should be a straight-forward way of placing the component somewhere where it wont get cut off.

**Comment by casesandberg** [comment]
I am going to go ahead and close this. If you are still having an issue please try using the newest version of this package. Otherwise, you can open a new issue.
