### ISSUE TITLE
consider replacing react-css for a lighter alternative

### ISSUE THREAD

**Issue by giladv** [casesandberg/react-color#555]
hello,
while optimizing a bundle with this package, i found out reactcss(32k) weighs almost as much as react-color(39.5k for a single picker). it make no sense integrating an expensive css library inside a small project like this and effectively doubling it's size as a result. 

thanks.

**Comment by casesandberg** [comment]
We are working on v3.0.0 of this package and will be removing both `reactcss` and `tinycolor2` which add to the bulk of the bundle size.
