### ISSUE TITLE
Customize TwitterPicker using TypeScript

### ISSUE THREAD

**Issue by Codeluck** [casesandberg/react-color#556]
Hi there! Thank you for the awesome component.

I am using your library + typings + TypeScript. Now I am gonna implement a 'no-color' feature so I added a 'none' value to my 'colors' array so it generates a div with title="none" as a result. However, if you look at ```handleChange``` function in TwitterPicker you should see a validation at line 114:
```color.isValidHex(hexcode) && onChange({```
So I never receive a callback when clicking at a particular color. Now I need to create my own 'EnhancedTwitterPicker' component in Type Script to avoid that. Do you have any suggestions how to do that? I don't think we have any typings for sub-component such as Swatch or ColorWrap. Another approach is to override ```handleChange``` function but it's also impossible because it's been defined within a closure. Please, let me know what do you think.

**Comment by casesandberg** [comment]
To have no color change I suggest using "transparent" as a value. The current pickers are set to handle that specific case in the way you are expecting.

**Comment by casesandberg** [comment]
I am going to go ahead and close this. If you are still having an issue please try using the newest version of this package. Otherwise, you can open a new issue.
