### ISSUE TITLE
UI is corrupted on my app but working successfully on codesandbox 

### ISSUE THREAD

**Issue by abdallahokasha** [casesandberg/react-color#559]
React-color UI is corrupted on my App but it's working successfully here on [codesandbox](https://codesandbox.io/s/1zpj33vrv7)

Although the same version is used in the two cases
    "react-color": "^2.14.1",

**Comment by casesandberg** [comment]
Can you expand more on what you mean by "Corrupting"? Can you provide the code you are using so that we can debug it to see whats going on?

**Comment by casesandberg** [comment]
It looks like you have a CSS selector that is targeting all divs on the page:
```
div {
    border-radius: 5px;
    padding: 10px;
}
```
I would suggest changing this to something more specific as its what is causing styling issues within the color picker.
