### ISSUE TITLE
componentWillReceiveProps causes React.StrictMode to error

### ISSUE THREAD

**Issue by rpearce** [casesandberg/react-color#563]
As per https://reactjs.org/docs/strict-mode.html#identifying-unsafe-lifecycles, might want to update `componentWillReceiveProps` to `getDerivedStateFromProps` or some other "safe" lifecycle method so that components using this library can adhere to React's new `StrictMode`

**Comment by jakobsandberg** [comment]
Update:

Looks like we'll be getting React 16 in v3 🙂 https://github.com/casesandberg/react-color/blob/3.0.0/package.json#L64

**Comment by casesandberg** [comment]
😎

**Comment by casesandberg** [comment]
I am going to close this as we will be using `getDerivedStateFromProps` in 3.0.0.
