### ISSUE TITLE
Can add style prop to all components?

### ISSUE THREAD

**Issue by Theoton** [casesandberg/react-color#564]
I think a lot of people have a need for custom styles

**Comment by DannyDelott** [comment]
Same boat, particularly with the default `box-shadow` on the Compact picker. Looks really weird when embedded in card style UIs.

**Comment by schester44** [comment]
Probably not the answer you're looking for but you could always wrap the component in a styled-component (or similar) and target the specific elements via their class?

**Comment by Theoton** [comment]
This has been published at react-color@2.17.0. Cheers! 

[https://github.com/casesandberg/react-color/pull/447](https://github.com/casesandberg/react-color/pull/447)

![image](https://user-images.githubusercontent.com/18453647/50371767-29a3aa00-05fc-11e9-8594-460defbbb6e4.png)


> Probably not the answer you're looking for but you could always wrap the component in a styled-component (or similar) and target the specific elements via their class?


It's ugly to use 'class' and '!important' now, I will update to 2.17.0.
