### ISSUE TITLE
SliderPicker break components

### ISSUE THREAD

**Issue by 0957758592** [casesandberg/react-color#565]
I have check all Pickers and only **SliderPicker**  breaks Components. 

`Uncaught Error: The style prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX.`

Any solution?

**Comment by thiagozulato** [comment]
Same error here. 

There is a wrong condition `styles.wrap || ''` in this file

https://github.com/casesandberg/react-color/blob/master/src/components/slider/Slider.js#L25

**Comment by thiagozulato** [comment]
@0957758592 You can try passing custom styles to the component like:

 `<Slider styles={{ default: { wrap: {} } }} />`. 

You need passing an empty object to wrap key.

**Comment by 0957758592** [comment]
@thiagozulato Thank you, but I'm not sure about this solution.
I have use only two parameters:

`<SliderPicker  color={primary}  onChange={this.handleChangePrimary}  />`

where `color` comes from the state and `onChange` - also can't brake my Component:

  `handleChangePrimary = color => { this.setState( { primary: color.hex }); };` 

Nothing more.

So now I use another one Picker as **`<CompactPicker/>`**

**Comment by thiagozulato** [comment]
@0957758592 yeah, you're right. It's not a good solution. But if you want to use `<Slider />` you need passing **style** prop otherwise you will have the problem.
