### ISSUE TITLE
Tags/Versions

### ISSUE THREAD

**Issue by gor181** [casesandberg/react-color#57]
Hello,

Would you please be so kind to create tags or versions?
Ideally would be for react < 14 and react >= 14.

I have a large code base which I need to rewrite to be compatible with react >= 14 and would be great to hook up to a tag/version for react-color.

Thanks a lot

**Comment by casesandberg** [comment]
Just released 1.3.0 which is >= 0.14.0

https://github.com/casesandberg/react-color/releases/tag/1.3.0
