### ISSUE TITLE
AlphaPicker with vertical direction is upside down

### ISSUE THREAD

**Issue by inconduit** [casesandberg/react-color#576]
this may be subjective, but the vertical alpha picker has the 100% alpha point at the bottom, which is counterintuitive from a UI perspective. in the docs i don't see an option to change this. is there a workaround?

a secondary issue is the scroll handle being off center from the track.

<AlphaPicker direction="vertical" />

here's a screenshot to illustrate:

<img width="72" alt="screen shot 2019-01-21 at 11 02 53 am" src="https://user-images.githubusercontent.com/1611256/51486212-135d4b00-1d6e-11e9-800d-75e64d0b5480.png">

**Comment by casesandberg** [comment]
Unfortunately, the alpha picker is only that one direction at the moment. I would be more than happy to merge a PR that reverses it if you want to take a stab at it. 

As for the off-center handle, if you can paste a code snippet I can help you out.

**Comment by inconduit** [comment]
i don't have the time for a PR right now but thanks all the same for confirming the issue. i have a workaround in place. i'll leave the issue open for visibility.

**Comment by casesandberg** [comment]
I am going to go ahead and close this, it will be supported with the new version we are working on.
