### ISSUE TITLE
Feature request: 'width' as a prop for ChromePicker

### ISSUE THREAD

**Issue by cokencode** [casesandberg/react-color#578]
Hi there, thanks for a great library👍 

Is there a plan to support `width` as a prop for ChromePicker? or is there any reason not supporting it?
Currently, I can change the width by passing down `width` value via `styles` prop. But I have to set `styles` prop to an object that looks like below
```js
{
  'default': {
    picker: {
      width: '500px'
    }
  }
}
```
I think the support for `width` prop will make it much easier.
If 'width' prop can be added to ChromePicker, I'm happy to send a PR for it!

**Comment by casesandberg** [comment]
Awesome! Yes I think it makes sense to support width on the ChromePicker.
Happy to help you land a PR that does that.
