### ISSUE TITLE
How to add `transparent` on `SketchPicker`?

### ISSUE THREAD

**Issue by zhaoyi0113** [casesandberg/react-color#579]
I am using `SketchPicker` in my website and want to add a `transparent` button on the picker. What is the easiest way to do that?

**Comment by sukhminderx** [comment]
You can add a preset color value as 'TRANSPARENT'

**Comment by zhaoyi0113** [comment]
Is there any doc or sample which demonstrate how to set `preset`?  Below is my code and is `preset` a property can be passed in?

```
<SketchPicker
                            color={this.state.color}
                            className={`${colorPickerClassName} color-picker`}
                            onChangeComplete={color => {
                                this.props.setColor(color);
                                this.setState({ color });
                            }}
                        />
```

**Comment by sukhminderx** [comment]
yeah, pass it as  props as:
`presetColors - Array of Strings or Objects, Hex strings for default colors at bottom of picker. Default ['#D0021B', '#F5A623', '#F8E71C', '#8B572A', '#7ED321', '#417505', '#BD10E0', '#9013FE', '#4A90E2', '#50E3C2', '#B8E986', '#000000', '#4A4A4A', '#9B9B9B', '#FFFFFF']
presetColors may also be described as an array of objects with color and title properties: [{ color: '#f00', title: 'red' }] or a combination of both`

**Comment by zhaoyi0113** [comment]
works great. Thanks.
