### ISSUE TITLE
e.preventDefault() inside passive event listener in mobile devices

### ISSUE THREAD

**Issue by fsubal** [casesandberg/react-color#581]
With `"react-color": "^2.17.0"`

In Chrome 71.0.3578.98, with devtools responsive mode, the following warning is emitted.

![2019-01-28 18 01 56](https://user-images.githubusercontent.com/5250706/51824884-d6252a00-2326-11e9-804d-9f7a5affea84.png)

It look like React implicitly `addEventListener`s `touchmove` event as `{ passive: true }`.

Since [you should not fire `e.preventDefault()` in `touchmove` handler](https://www.chromestatus.com/features/5093566007214080), which `Saturation` component is violating it.

https://github.com/casesandberg/react-color/blob/8bde391b44d9336bccae91757b748b32d91bb1cd/src/components/common/Saturation.js#L20-L26

Fundamentally it is caused by `saturation.calculateChange()`, so it seems this could be solved by

1. making `.calculateChange` not requiring `Event` object
2. not using `Saturation.this._handleChange` for `onTouchmove`, replacing to another event handler

**Comment by fsubal** [comment]
Also reproduced in https://casesandberg.github.io/react-color/

![2019-01-28 18 14 52](https://user-images.githubusercontent.com/5250706/51825712-aecf5c80-2328-11e9-93df-7f635c30aa1f.png)

**Comment by casesandberg** [comment]
Hmm, this is an interesting case. I am going to look back through to see why preventDefault was added in the first place. We might be able to just remove it.

**Comment by geoffroy72** [comment]
Looks like this is a known issue with Chrome and React:
https://github.com/facebook/react/issues/8968

**Comment by casesandberg** [comment]
I am going to go ahead and close this as it has to do with a specific version of React and not this package itself.
