### ISSUE TITLE
cannot find module @icons/material/UnfoldMoreHorizontalIcon

### ISSUE THREAD

**Issue by ElienVissers** [casesandberg/react-color#586]
After npm installing react-color, the following line of code: 

`import { CirclePicker } from 'react-color';`

seems to break everything. The error message reads:

> cannot find module @icons/material/UnfoldMoreHorizontalIcon
 

During npm install, the following dependencies were skipped: 

```
SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

```
I don't know if those dependencies are important, and if yes how to install them? I have manually re-installed @icons/material but this did not solve my issue.

Thank you in advance.

**Comment by casesandberg** [comment]
What version of the package are you using? The CirclePicker does not use any icons so I am not sure why that would be giving you errors. Maybe try importing the picker directly:
```
import CirclePicker from 'react-color/lib/Circle'
``

**Comment by ElienVissers** [comment]
Importing it directly fixed it, and it works great now! Thank you!
