### ISSUE TITLE
Incorrect input value when leaving the editable inputs

### ISSUE THREAD

**Issue by Cyrus-d** [casesandberg/react-color#588]
Look like there is a problem with editable input. 

Step to reproduce :

1.  Set the colour to green with saturation component, the 'G' input should be 255.
2.  Click on each input and leave the input, the value of the input will be replaced with invalid value.

Apparently, the input value is replaced with the initial value and ignoring the current value.

![image6](https://user-images.githubusercontent.com/4041334/52534590-6a39bd00-2d3b-11e9-85f9-cc87c9b5f6eb.gif)

Thanks,

**Comment by casesandberg** [comment]
Can you paste the code you are using? Are you storing the returned value in state and passing it back down to the PhotoshopPicker?

**Comment by Cyrus-d** [comment]
its actually happens in the demo page too, so I'm not sure if pasting code can help. thanks,

**Comment by casesandberg** [comment]
On this page: http://casesandberg.github.io/react-color/ ? I cant seem to reproduce it. Are you using Master? The doccumentation site it out of date. Also, what browser / OS are you using?

**Comment by Cyrus-d** [comment]
hi, yes on the page you have linked. yes, i am using master. the OS is windows 10, and I have tested with the following browsers:

chrome Version 72.0.3626.119 (Official Build) (64-bit)
ie edge
firefox 65.0.1

the result was same in all of the above browsers.

Thanks,

**Comment by cokencode** [comment]
I have looked into this issue. The version of react-color package on [demo page](https://casesandberg.github.io/react-color/) is outdated. It is using the version before #420 PR is merged. I think the docs needs to be updated with latest version of the package.

@Cyrus-d Are you using old version of react-color?

@casesandberg I got a question while I was looking into `<EditableInput />` component. Why is there `blurValue` in the state? I could not figure out a case that needs `blurValue` in the state. I just feel like `blurValue` in the state is redundant...

**Comment by Cyrus-d** [comment]
@cokencode yes I have been using the older version, just tried the new version, and the problem is solved, thanks for the fix, however now I have noticed a new problem:

Step to reproduce :

1. select one of the input.
2. change colour with saturation, the field value won't change.

![image6](https://user-images.githubusercontent.com/4041334/53662186-370f8d00-3c5a-11e9-85b6-7d82b11c347d.gif)

is it intentional, I think its more appropriate to remove the focus from input when using saturation.

because this is a different problem should I open a new issue?

Thanks,

**Comment by cokencode** [comment]
@Cyrus-d I have known that issue as well. There has been an issue opened already #398 
Also, there is already a PR opened that fixes this issue. #437

**Comment by Cyrus-d** [comment]
thanks for the info.
