### ISSUE TITLE
Feature request: Enhance SketchPicker with hsl input

### ISSUE THREAD

**Issue by kriswep** [casesandberg/react-color#589]
I'd really love to have the SketchPicker with a hsl input option.
Ideally, you could change the default input option (on first render) via a to be defined prop.
Also, it would be nice to have an option to initially open the ChromePicker in hsl mode.

Tell me your thoughts. If you'd consider that a good addition, I could work on a PR.

**Comment by casesandberg** [comment]
The goal of the library is to provide components that are most closely related to their live counterparts. In the case of the SketchPicker its only built for RGBA. It is really easy for you to make your own custom color picker that doesn't HSLA by copying this file and tweaking a few things: https://github.com/casesandberg/react-color/blob/master/src/components/sketch/Sketch.js. You would only need to change the `SketchFields` component to reflect the changes in colorspace.
