### ISSUE TITLE
Importing only one type of picker at once

### ISSUE THREAD

**Issue by skosch** [casesandberg/react-color#59]
Feature request: it would make this amazing library even more amazing if the components were provided individually. As it is, I have to bundle ~200KB of libraries even though I only end up using a fraction of them. (Or if this is already possible and I'm just not smart enough to find out how to do that, please help!)

In any case, thanks a million for a wonderfully useful tool!

**Comment by casesandberg** [comment]
@skosch Couple questions:
* Are you using ES6?
* Are you using a module loader? (JSPM, Webpack, Browserify)
* How are you bundling it?

**Comment by skosch** [comment]
Yes; Webpack; and I'm doing a simple `import ColorPicker from 'react-color'`. I only need the swatch dialog, so all the others (and the components within them) could be ignored.

**Comment by casesandberg** [comment]
Got it. I can try and get a fix in tonight that will allow you to do: `import ColorPicker from 'react-color/swatch'` and only require that color picker!

**Comment by skosch** [comment]
Awesome. That's exactly the kind of splitting up of files I was looking for. Thanks so much :)

**Comment by idolize** [comment]
+1 This would be great!

**Comment by casesandberg** [comment]
Just published `react-color@1.3.0` which allows you to:
```
import SwatchesPicker from 'react-color/swatches';
```

**Comment by kumarharsh** [comment]
Hi @casesandberg, I'm using `react-color@1.3.0` and using

```
import SwatchesPicker from 'react-color/swatches';
```

is giving me an error:

```
ERROR in ./src/app/.../components/Settings.js
Module not found: Error: Cannot resolve module 'react-color/swatches' in ...
```

**Comment by casesandberg** [comment]
Digging into this today

**Comment by casesandberg** [comment]
@kumarharsh I couldnt figure out how to get the 'react-color/swatches' syntax to work, but you can just deconstruct the import to grab whichever picker you want standalone:
```
import { SwatchesPicker } from 'react-color';
```

**Comment by kumarharsh** [comment]
yes, I had started using that itself. I posted this because of your previous comment, which said the same thing.

**Comment by nss213** [comment]
To be clear, `import { SwatchesPicker } from 'react-color';` doesn't actually exclude the code for the other color pickers from your build. I did find 
```import ChromePicker from 'react-color/lib/components/chrome/Chrome';```
to work for me though.
