### ISSUE TITLE
Unable to preventDefault inside passive event listener due to target being treated as passive

### ISSUE THREAD

**Issue by anuraghazra** [casesandberg/react-color#591]
I think this is why preventDefault() is not working in mobile devices #590.

![react-color](https://user-images.githubusercontent.com/35374649/53019195-3288ee80-347a-11e9-9611-970296d9dec6.PNG)

**Comment by casesandberg** [comment]
Do you have some time to dig into this an put up a PR with a solution?

**Comment by casesandberg** [comment]
Closing as duplicate of https://github.com/casesandberg/react-color/issues/581

**Comment by anuraghazra** [comment]
Okay, I will try to give it a go hopefully fixing the bug.
