### ISSUE TITLE
node-canvas 2.0 is not compatible with your implementation

### ISSUE THREAD

**Issue by aziz** [casesandberg/react-color#595]
Here are the breaking changes: https://github.com/Automattic/node-canvas/blob/master/CHANGELOG.md#200

**Comment by casesandberg** [comment]
We do not use canvas in this project. Are you referring to passing in your own canvas object not working?

**Comment by casesandberg** [comment]
I am going to go ahead and close this issue. If you are still having an issue please try using the newest version of this package and If it's still an issue feel free to open a new one.

**Comment by csandman** [comment]
For anyone else that's curious, this just changed the way you import node-canvas for SSR.

To import the constructor, do 

```js
import { Canvas } from 'canvas'
```

instead of

```js
import Canvas from 'canvas'
```

Everything about the `react-color` implementation should stay the same.
