### ISSUE TITLE
Can't override styles of inner picker components like SketchFields for SketchPicker, etc.

### ISSUE THREAD

**Issue by RoslerWS** [casesandberg/react-color#596]
Providing a styles prop to the chosen picker only gives the option to add / override styles on the outer most component. I need to be able to increase the font size of the hex / rgb fields, and there is no way to pass down styles to the SketchFields in the SketchPicker to do so.

**Comment by casesandberg** [comment]
There currently is no direct way to do this with inline styles. You can get around this by using CSS, however:
```
.sketch-picker span {
    font-size: 24px;
}
```

**Comment by towfiqi** [comment]
I dont understand why you couldn't add custom classes to all the divs, so the inner components could be styled by anyone?
