### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'material.red['500']')

### ISSUE THREAD

**Issue by Orangetronic** [casesandberg/react-color#597]
I am using the SketchPicker component, and i'm getting the following error thrown from `/lib/components/circle/Circle.js`

Have material-color changed their export pattern or something?

Is anybody else getting similar behaviour?

**Comment by casesandberg** [comment]
Hmmm, it looks like [`material-colors`](https://www.npmjs.com/package/material-colors) it was last published 10 months ago. It could be a particular configuration you have with your build setup. I can't seem to reproduce this, are you still having problems?

**Comment by Orangetronic** [comment]
it's a weird one -- i can't see anything that's changed either with react-color, or with material-colors (or with our build process!)

I was hoping somebody else might've bumped into the same thing, but if it's not easily reproducible I'd say close this for now, and I'll re-open or raise another issue as and when I have any more conclusive info on why this is happening.

I suspect it's going to end up being one of those "stand on your head and run `npm cache clean` four times backwards" type issues!
