### ISSUE TITLE
bundle.js includes react

### ISSUE THREAD

**Issue by WickyNilliams** [casesandberg/react-color#60]
The bundle includes React. You should add React and ReactDOM to webpack externals so that they are not included

**Comment by casesandberg** [comment]
The bundle is for the documentation website only, only the `lib` dir gets used in prod.

**Comment by WickyNilliams** [comment]
Touché. I thought it might have been for UMD support (might be worth considering, it's a pretty simple change to support)

**Comment by casesandberg** [comment]
Cool! I will look into it :)
