### ISSUE TITLE
React-color 2.17 is breaking

### ISSUE THREAD

**Issue by liron-navon** [casesandberg/react-color#603]
I'm using storybook addon-knobs, it uses react-color as a dependency, and it has an error in it's story files, I guess it tries to find the .storybook directory which is missing, I tried uninstalling knobs and only installing react-color, it still breaks the build with the same error.

```
ERROR in ./node_modules/react-color/lib/components/swatches/story.js
Module not found: Error: Can't resolve '../../../.storybook/report' in '/Users/lna11126/Desktop/my-app/node_modules/react-color/lib/components/swatches'
 @ ./node_modules/react-color/lib/components/swatches/story.js 9:14-51
 @ . sync .story\.jsx?$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true
```
This is the file: `react-color/lib/components/swatches/story.js`

<img width="1093" alt="Screen Shot 2019-03-28 at 22 21 47" src="https://user-images.githubusercontent.com/18119833/55190564-b1bfbf80-51a8-11e9-8bbe-b17d355f05c5.png">

**Comment by casesandberg** [comment]
It looks like you are using a broad glob pattern when searching for stories in your project and it is pulling in stories from this package. Are you doing this intentionally? If you omit it from searching the `node_modules` folder it will fix this problem.
