### ISSUE TITLE
ColorPicker Slider issue

### ISSUE THREAD

**Issue by loick** [casesandberg/react-color#62]
Hi,

first of all, nice plugin :)

I have an issue with the Slider ColorPicker though, : 
```javascript
import React, {Component, PropTypes} from 'react'
import ColorPicker from 'react-color'

export default class MyClass extends React.Component
{
    render() {
        return (
                <ColorPicker type="slider" />
        )
    }
}

React.render(
  <MyClass/>,
  document.getElementById('react-root')
);
```

And i get the following error on the drag and drop: 
"Uncaught TypeError: container.getBoundingClientRect is not a function" on the handleChange function. 

Do you have any fix for this, or did i do something wrong ? 

Thanks !

**Comment by loick** [comment]
I checked on your code and I think, in the handleChange function of the Hue.js, we need to add : 

```javascript
var container = this.refs.container.getDOMNode();
```

Instead of : 

```javascript
var container = this.refs.container;
```

**Comment by loick** [comment]
Okay, this is because you have a dependency of Reatc 0.14 right ? The "this.refs.container" is not working for me because i miss the "getDOMNode" function. I will check on your tags.

**Comment by ericmcgregor** [comment]
same issue

**Comment by casesandberg** [comment]
The current version of React Color uses 0.14.0, correct. To use React Color with an older version of react instally `reactcss@1.1.2`

**Comment by freddyrangel** [comment]
Coming across the same issue. reactcss@1.1.2 doesn't seem to be a thing on npm. Perhaps I'm missing something here?

**Comment by freddyrangel** [comment]
Ah I figured it out. You meant react-color@1.1.2, not reactcss@1.1.2 :)
