### ISSUE TITLE
BUG - pick left edge of Saturation and Hue can not be clicked but still dragged.

### ISSUE THREAD

**Issue by tanth1993** [casesandberg/react-color#621]
Hi. as the Title I have 2 custom components: Saturation and Hue.
when I pick a color around left edge, the Hue is jumped up and down and I can not click on Hue, but it still be dragged. 
My customers want to click on Hue when they pick color on left edge. 
So any solutions for this??? 
Thank you!

**Comment by casesandberg** [comment]
This has been fixed with https://github.com/casesandberg/react-color/pull/670 and will be released shortly as `react-color@2.18.0`
