### ISSUE TITLE
Warning Warning: componentWillReceiveProps has been renamed, and is not recommended for use

### ISSUE THREAD

**Issue by cardimajs** [casesandberg/react-color#634]
I,m using last stable version and get this warning.

react-dom.development.js:12050 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: ColorPicker, EditableInput

**Comment by glennpatrickryan** [comment]
I've left a similar comment on the issue: 
https://github.com/casesandberg/react-color/issues/458#issuecomment-519944281

**Comment by cfed** [comment]
Thanks @hlodver for sharing patch-package. It's exactly what I need.

**Comment by jasonrobson** [comment]
I am also waiting for this :v, is there any clue about when they are going to update it?

**Comment by CyanoFresh** [comment]
same problem

**Comment by mikkpokk** [comment]
Problem occurs on this file also: https://github.com/casesandberg/react-color/blob/master/src/components/common/ColorWrap.js

**Comment by acoop133** [comment]
Has this project been abandoned?

**Comment by casesandberg** [comment]
This was fixed with https://github.com/casesandberg/react-color/pull/662 and will be released shortly as `react-color@2.18.0`

**Comment by gonzofish** [comment]
Thanks @casesandberg
