### ISSUE TITLE
Color selection cursor is jarring over shades of grey

### ISSUE THREAD

**Issue by yury-n** [casesandberg/react-color#636]
![Untitled](https://user-images.githubusercontent.com/1035576/63350597-c32f8100-c36e-11e9-9dd7-768eca4be865.gif)

seems like it happens on any type of the picker (tried a couple).

2.13.5 is the last version where this bug didn't happen.

**Comment by boris-hocde** [comment]
Hi, I've got the same issue. It only happen on left and bottom borders. Right & top borders are ok.
https://drive.google.com/file/d/1cIkarAs-Vadv6mcXtyX3OCYyQ7CE3s7d/view

**Comment by casesandberg** [comment]
This has been fixed with https://github.com/casesandberg/react-color/pull/670 and will be released shortly as `react-color@2.18.0`
