### ISSUE TITLE
Allow passing in width for "Sketch"

### ISSUE THREAD

**Issue by danawoodman** [casesandberg/react-color#64]
First off, great component!

It seems the "Sketch" will support widths other than `200px` so it would be great if there was a prop to pass that down. That, or some docs on how to pass down that with ReactCSS (not sure that is possible as I'm not familiar with that project). 

Thanks!

**Comment by casesandberg** [comment]
This has been fixed in `react-color@1.3.0` just pass down the width as a prop:
```
<ColorPicker type="sketch" width="300" />
```
