### ISSUE TITLE
Janky motion issues

### ISSUE THREAD

**Issue by PCMACHero** [casesandberg/react-color#644]
There are 2 severe issues with the movement / motion when dragging the pointer on the color box.

1) The motion is janky, not smooth / 60 frames per second.
2) You can drag the mouse while holding the pointer, outside of the box (useful for getting the absolute edge of a box, like if you want a solid white or solid black), except when circling out of the box on the bottom right corner, it loses its handle and the pointer starts jumping around randomly or loses control.

These issues occur even when using "onChangeComplete" or whatever it is.

**Comment by nickmealey** [comment]
I've also run into this issue

**Comment by obsius** [comment]
![bug](https://user-images.githubusercontent.com/20999862/67887397-67b90680-fb08-11e9-947b-2a88c6ba71b8.gif)

+1

**Comment by mikalai-sauchanka** [comment]
Reported it here: #656

**Comment by casesandberg** [comment]
This has been fixed with https://github.com/casesandberg/react-color/pull/670 and will be released shortly as `react-color@2.18.0`
