### ISSUE TITLE
Chrome Picker Source from onChange is always RGB

### ISSUE THREAD

**Issue by JCron245** [casesandberg/react-color#648]
I thought the intent of the 'source' key in the onChange event was to show which 'editable field' is in use by the Chrome Picker but it always returns 'rgb'. Am I misunderstanding the usage, or is there a bug?

**Comment by casesandberg** [comment]
This is definitely a bug. Putting a fix up for it now!

**Comment by stanislaw-grin** [comment]
After the fix it's always hsv
