### ISSUE TITLE
BlockPicker input not working

### ISSUE THREAD

**Issue by focux** [casesandberg/react-color#651]
The input in the BlockPicker component isn't working, I expect the input to trigger one of the onChange methods if a valid hex value was entered.

**Reproduction:**
https://codesandbox.io/s/goofy-visvesvaraya-rfvi1?fontsize=14

**Comment by vieira** [comment]
I am also experiencing this issue, it works with `2.17.0`.

**Comment by focux** [comment]
@vieira I had downgraded to `2.14.1` because I read in another issue that it was working on that version but if you say it's working on 2.17.0, I'm going to use that one. Thank you.

**Comment by vieira** [comment]
Seems that this was fixed in #616 but not released yet 😞

**Comment by souuu** [comment]
Any update for this please ? :(

**Comment by Fensterbank** [comment]
Is anything blocking a release?
Since it was fixed in #616 a new version should be released.

For now, everybody using the npm packages will end up with a broken BlockPicker.

**Comment by casesandberg** [comment]
Sorry about that. This will be released shortly as `react-color@2.18.0`
