### ISSUE TITLE
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

### ISSUE THREAD

**Issue by Murphycx94** [casesandberg/react-color#660]
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

**Comment by djrumbold** [comment]
This is a duplicate of #634

**Comment by casesandberg** [comment]
This was fixed with #662 and will be released shortly as react-color@2.18.0
