### ISSUE TITLE
Prevent text selection

### ISSUE THREAD

**Issue by nmoreaud** [casesandberg/react-color#667]
When i click-move mouse from color picker to outside the sketch picker, the html page text becomes selected.
It would be nice to prevent text selection once the main color area is clicked, until the mouse button is released.

**Comment by casesandberg** [comment]
This is unfortunately a limitation of browsers because you are clicking the mouse down. There is nothing we can really do about this.

**Comment by hzhu** [comment]
It seems like the text on the home page isn't selected when a color picker thumb is active and hovered over text. How is it achieved on the home page? I tried digging into it, but running the home page locally is broken: https://github.com/casesandberg/react-color/issues/727 https://github.com/casesandberg/react-color/issues/446.

![2020-12-01 15 33 43](https://user-images.githubusercontent.com/1811365/100809314-b3fd0700-33ea-11eb-9ba7-461eb84fcfad.gif)

**Comment by nmoreaud** [comment]
I already fixed this kind of bugs in html pages, it can probably be fixed here too

**Comment by bayati-code** [comment]
Worked for me!
css:
```
body{
    -webkit-touch-callout: none; /* iOS Safari */
    -webkit-user-select: none; /* Safari */
     -khtml-user-select: none; /* Konqueror HTML */
       -moz-user-select: none; /* Old versions of Firefox */
        -ms-user-select: none; /* Internet Explorer/Edge */
            user-select: none;
}
```
