### ISSUE TITLE
Colorpicker as component

### ISSUE THREAD

**Issue by KevinDenys** [casesandberg/react-color#669]
![image](https://user-images.githubusercontent.com/17174443/71991107-e763ff80-3234-11ea-8ac3-05deb184a317.png)
Is there a way to get this as a component?
Where you can pass a onClick and a value

**Comment by casesandberg** [comment]
Yep! You can find more details here http://casesandberg.github.io/react-color/#create-helpers. 

You can use just the `Saturation` component.
