### ISSUE TITLE
Cannot Change Color

### ISSUE THREAD

**Issue by damnitrahul** [casesandberg/react-color#674]
The color choosing circle and the sliders are fixed and do not move with upon click and drag. Hence its does not allow us to choose a color in the latest version 2.18.0.

Everything works fine on rolling back to 2.17.3.

**Comment by vkarakoulakoglou** [comment]
I have the same issue. The "onChange", "onChangeComplete", "onAccept"  events work in the background as expected, however the UI is "frozen" ie the sliders and the buttons have no visible effect when interacting with them.

I've also tried the 2.17.3, but I had the same problem. Have you found any solution/workaround for this?

**Comment by somyarocketium** [comment]
@vkarakoulakoglou make sure in package.json you have the exact version "2.17.3" and not "^2.17.3", tried it worked for me , but looking fwd for a resolution in latest version

**Comment by vkarakoulakoglou** [comment]
@somyarocketium  thanks for your reply. I already had it like that, however I also had wrongly set the onChange method so it was never updating its value. I guess the fix for the latest version would be out soon. cheers

**Comment by maniac0s** [comment]
I am here sitting the whole day trying to get that color picker into a react-draggable component and it doesn't work. I thought it was draggable messing with the events on the color picker then I tried to put it into a modal from the reactstrap library and had the same problem. It just doesn't allow me to move the selector circle nor the sliders and it doesn't work either, buttons work however. Had I just looked here because I already had the colorpicker working a few weeks ago just wanted to move it into a draggable.

Is this really a bug in the version? I have installed
+ react-color@2.18.0

**Comment by Matrixbirds** [comment]
I got same issue...

**Comment by navicstein** [comment]
Am also experiencing this issue

**Comment by SlehMas** [comment]
I solved the issue by installing the exact version 2.17.3 (ran nom i react-color@2.17.3) just like @somyarocketium said

**Comment by wntechs** [comment]
I had the same issue with latest version and solved it by defining default color property.
`<HuePicker
                    color={this.state.background}
                    onChangeComplete={ this.handleChangeComplete }/>`

**Comment by kylekirkby** [comment]
> I had the same issue with latest version and solved it by defining default color property.
> `<HuePicker color={this.state.background} onChangeComplete={ this.handleChangeComplete }/>`

This didn't solve my issue. I'm using the ChromePicker and the only thing that solved the issue for me was reverting to 2.17.2 as @somyarocketium mentions. Thank you! 

Maintainers - any idea what is going on in the latest version?

BR,

Kyle

**Comment by rffaguiar** [comment]
Same issue as @kylekirkby: using ChromePicker and the ui circle doesn't move even though the color is updated (`console.log(color)` on `onChangeComplete`)

**Comment by webdevfrancisco** [comment]
> > I had the same issue with latest version and solved it by defining default color property.
> > `<HuePicker color={this.state.background} onChangeComplete={ this.handleChangeComplete }/>`
> 
> This didn't solve my issue. I'm using the ChromePicker and the only thing that solved the issue for me was reverting to 2.17.2 as @somyarocketium mentions. Thank you!
> 
> Maintainers - any idea what is going on in the latest version?
> 
> BR,
> 
> Kyle

same here! rolling back to 2.17.3 worked for me.

**Comment by listao** [comment]
Any updates on this issue? I'm running into the same issue with the sliders not updating their position. As the other say the color value does update accordingly on `onChange` and `onChangeComplete`. 

I even copied the exact class for the ButtonExample and it doesn't work, but when I copied and pasted on https://codesandbox.io/, it seem to work just fine...

The rollback didn't resolve the issue for me.

**Comment by neighborhood999** [comment]
`<EditableInput />` same as this issue, ref [link](https://codesandbox.io/s/react-color-custom-gtxto)

**Comment by xoxwgys56** [comment]
<SliderPicker /> works on 2.17.3, past version was ^2.18.0

**Comment by casesandberg** [comment]
This has been fixed and will be release in `react-color@2.18.1`

**Comment by nsthorat** [comment]
Seeing this in 2.18.1.

**Comment by hke-cheng** [comment]
The bug still here.

**Comment by aleafo** [comment]
still 2.18.1

**Comment by greeneman42** [comment]
If you're still having this issue, remember that the components are controlled only.  You must supply a hex color string via the color prop that gets updated via onChange or onChangeEnd.

**Comment by krishnaPC** [comment]
@casesandberg Can confirm that this issue still exists in 2.18.1.  Can this issue be reopened?

**Comment by KPChakravarthy** [comment]
@casesandberg I can confirm that this issue still exists in 2.18.1 and rolling back to 2.17.3 fixes it. Can you please reopen this ticket?

**Comment by bmeunier1974** [comment]
Also seeing the bug in 2.18.1 Fixed by rolling back to version 2.17.3.

**Comment by jacob-alxndr** [comment]
color prop value needs to be updated onChange. 
2.18.1 works as long as that value is being updated.

**Comment by jasoncui** [comment]
Was experiencing this issue with latest version using React Hooks. Found a solution by defining a separate color state, and updating this value onChangeComplete. The component then takes the color state as a prop.

**Comment by eliasbobadilla** [comment]
I had the same issue with Slider Picker but it' fix adding a default color: <SliderPicker color={current.color} />

**Comment by saba-bg** [comment]
> @vkarakoulakoglou make sure in package.json you have the exact version "2.17.3" and not "^2.17.3", tried it worked for me , but looking fwd for a resolution in latest version

works for me thanks

**Comment by ImAbhishekTomar** [comment]
Same issue facing with ("react-color": "^2.19.3",) this version.

I have already tried.
```
1. <ChromePicker color={item.color} onChange={(e) => handlerOnColorChange(e, item)} />
2. <ChromePicker  onChange={(e) => handlerOnColorChange(e, item)} />
3. <ChromePicker  onChangeComplete={(e) => handlerOnColorChange(e, item)} />
4. <SketchPicker  onChangeComplete={(e) => handlerOnColorChange(e, item)} />
5. <ChromePicker />
6. <SketchPicker />
```

**Comment by tilnea** [comment]
> Same issue facing with ("react-color": "^2.19.3",) this version.
> 
> I have already tried.
> 
> ```
> 1. <ChromePicker color={item.color} onChange={(e) => handlerOnColorChange(e, item)} />
> 2. <ChromePicker  onChange={(e) => handlerOnColorChange(e, item)} />
> 3. <ChromePicker  onChangeComplete={(e) => handlerOnColorChange(e, item)} />
> 4. <SketchPicker  onChangeComplete={(e) => handlerOnColorChange(e, item)} />
> 5. <ChromePicker />
> 6. <SketchPicker />
> ```

I'm experiencing the same problem with 2.19.3

**Comment by SkynI25** [comment]
Have same issue here too

**Comment by SkynI25** [comment]
> > Same issue facing with ("react-color": "^2.19.3",) this version.
> > I have already tried.
> > ```
> > 1. <ChromePicker color={item.color} onChange={(e) => handlerOnColorChange(e, item)} />
> > 2. <ChromePicker  onChange={(e) => handlerOnColorChange(e, item)} />
> > 3. <ChromePicker  onChangeComplete={(e) => handlerOnColorChange(e, item)} />
> > 4. <SketchPicker  onChangeComplete={(e) => handlerOnColorChange(e, item)} />
> > 5. <ChromePicker />
> > 6. <SketchPicker />
> > ```
> 
> I'm experiencing the same problem with 2.19.3

Have same issue here too.

**Comment by syanenko** [comment]
Confirm this issue with version 2.19.3 on Win7, Chrome 88.0.4324.150

**Comment by BenBrostoff** [comment]
Also had the same issue on 2.19.3, OSX, Chrome 88.0.4324.182  and also Firefox 85.0 (also confirmed rolling back to 2.17.3 resolved).

**Comment by akashchokshi** [comment]
Version: ^2.19.3
Working code snippet:
```
const [color, setColor] = useState('#ffffff'); // define a state for the color prop

// setState when onChange event triggered
const handleChange = (color: any) => {
    setColor(color.hex);
  };

<SketchPicker
          color={color}
          onChange={handleChange}
          onChangeComplete={handleChangeComplete}
        />
```

**Comment by Tripparsugo** [comment]
had the same issues, rolling back to 2.17.3 as suggested worked

**Comment by gsouvik** [comment]
2.19.x didn't work for me, I followed others and went back to 2.17.3 and it works. I wonder how major versions are being released and something which used to work, doesn't work in the current versions.

**Comment by joshmillgate** [comment]
Same issue 2.19.x didn't work for me, I followed others and went back to 2.17.3 and it works.

**Comment by maurorpo** [comment]
import React, {useState} from 'react';

const [color, setColor] = useState("#121212");

  const handleChange = (value) => {
    setColor(value.hex)
    console.log(color)
  }
  
  <Change>
      <ChromePicker color={color} onChange={ handleChange } />
    </Change>
    
    This work for me.
    Version ^2.19.3

**Comment by Mahdi15-879** [comment]
I solved the issue by installing the exact version 2.17.3 (ran npm install --save react-color@2.17.3) just like @somyarocketium said

**Comment by MGreif** [comment]
Solved it for the `<SliderPicker />` using Version 2.17.3 using a seperated State for the color and passing the color to the SliderPicker

**Comment by pintosack** [comment]
> Version: ^2.19.3 Working code snippet:
> 
> ```
> const [color, setColor] = useState('#ffffff'); // define a state for the color prop
> 
> // setState when onChange event triggered
> const handleChange = (color: any) => {
>     setColor(color.hex);
>   };
> 
> <SketchPicker
>           color={color}
>           onChange={handleChange}
>           onChangeComplete={handleChangeComplete}
>         />
> ```

This is what worked for me.

**Comment by aditodkar** [comment]
Solution mentioned by @pintosack  worked for me version `"react-color": "^2.19.3"`

**Comment by TangoPJ** [comment]
> Version: ^2.19.3 Working code snippet:
> 
> ```
> const [color, setColor] = useState('#ffffff'); // define a state for the color prop
> 
> // setState when onChange event triggered
> const handleChange = (color: any) => {
>     setColor(color.hex);
>   };
> 
> <SketchPicker
>           color={color}
>           onChange={handleChange}
>           onChangeComplete={handleChangeComplete}
>         />
> ```

It worked for me, but IMO it's pretty strange

**Comment by Licodeao** [comment]
Whatever version 2.19.3 or version 2.17.3, maybe should be considerated about chaning the color variable with using onChange function, it worked for me.

**Comment by TimeTerminal** [comment]
The latest version (v2.19.3) requires `handleChangeComplete` to be set. This works for me:

```javascript
const [color, setColor] = useState("#FFFFFF");

<ChromePicker
  color={color}
  onChangeComplete={(colorResult) => setColor(colorResult.hex)} // <- Make you add this line
/>
```

**Comment by yalogica** [comment]
I had the same issue, but this solution works for me

```ts
const [color, setColor] = useState("#FFFFFF");

return (
   <SketchPicker color={color} onChange={(colorResult) => setColor(colorResult.hex)} /> 
);
```
