### ISSUE TITLE
Is it possible to name a picker?

### ISSUE THREAD

**Issue by maniac0s** [casesandberg/react-color#676]
I would like to access the name attribute of the component for instance with e.target.name or something in the handleChange function.

    <SketchPicker name="fill" onChange={handleChange} />

What ever I tried, name is always undefined and e only contains the div I clicked in the colorpicker.

    const handleChange = (color, e) => {
        console.log(e);
    }

**Comment by ludovic-bekaert** [comment]
Why about using this method ?
```
<SketchPicker onChange={(color, e) => handleChange(color, e, 'fill')} />
```

```
const handleChange = (color, e, name) => {
    console.log(name);
}
```

**Comment by maniac0s** [comment]
Since it is not possible to just access any component attribute in reactjs, this is how I did it now: 

Create a react component "ColorPicker"
Put it with a name <ColorPicker type="fill" />
Access via props.type

                    <SketchPicker
                        color={buttonColor}
                        onChange={(color) => {
                            context.object().set({[props.type]: color.hex});
                        }}
                        onChangeComplete={(color) => setButtonColor(color.hex)}
                    />
