### ISSUE TITLE
NaN on selecting color can't select color

### ISSUE THREAD

**Issue by philholden** [casesandberg/react-color#68]
```jsx
constructor() {
  super(
    this.state = {
    color: '#333'
  }
  this.onChange = color => {
    console.log(color)
    this.setState({ color: '#' + color.hex })
  }
}

render() {
  return (
    <div className="demo">
      <ColorPicker color={this.state.color} type="chrome" onChangeComplete={this.onChange}/>
    </div>
  )
}
```

When I click on the color picker I get the following value logged from onChange:

```json
{
  "hsl": {
    "h": null,
    "s": null,
    "l": null,
    "a": 1
  },
  "hex": "00NaNNaN",
  "rgb": {
    "r": 0,
    "g": null,
    "b": null,
    "a": 1
  },
  "hsv": {
    "h": null,
    "s": null,
    "v": null,
    "a": 1
  },
  "oldHue": null
}
```

**Comment by casesandberg** [comment]
I cant seem to reproduce this. Can you update to the latest version and let me know if you are still having issues?

**Comment by banool** [comment]
I know this is 7 years old hahah but I'm seeing this issue now too. Sometimes you click and it's NaN.

**Comment by karex** [comment]
I managed to reproduce this (after 8 years). 😄

Steps:
1. Set the color state value to empty string: "".
2. Drag the Hue Slider, but don't touch the Saturation Pointer.
3. Result: #NaNNaNNaN

![image](https://github.com/user-attachments/assets/32eac27f-348f-4b92-81f8-22e5dc392022)
