### ISSUE TITLE
onChangeComplete fires when stop moving mouse not on mouseUp

### ISSUE THREAD

**Issue by maniac0s** [casesandberg/react-color#681]
onMouseUp does not fire when adding it to a picker component. Inspector also doesn't show an event bound to the picker div. So I thought I could use onChangeComplete instead but that fires each time I stop moving the mouse and not, as I thought, on releasing the mouse button.

Is it somehow possible to trigger an onMouseUp kind of event in the picker? I need that to finalize color picking in the react context variables.

    <SketchPicker
        color={buttonColor}
        disableAlpha={true}
        onChange={(color) => { //fires all the time as it should
            context.setObjAttr(props.type, color.hex, false); //false = omits render costly function call
        }}
        onChangeComplete={(color) => { //fires when stopping mouse movement for a short time
            setButtonColor(color.hex); //this is OK for color picker button update but not for promoting it to context
        }}
        onMouseUp={(color) => { //not firing at all
            context.setObjAttr(props.type, color.hex, true); //"finalize" the color change promoting it to all components
        }}
    />

**Comment by ambr89** [comment]
@maniac0s do you have found any solution about it?
