### ISSUE TITLE
Firefox CirclePicker white pixel bug

### ISSUE THREAD

**Issue by caoanhhao** [casesandberg/react-color#682]
Status:
![image](https://user-images.githubusercontent.com/6824340/75308710-b0e45180-5881-11ea-84ae-1342ef083224.png)

Cause:
https://github.com/casesandberg/react-color/blob/6a7f338ad46fa2ac9b0635091d2a7f798f5513d5/src/components/circle/CircleSwatch.js#L20

Solution:
assign background same color with box shadow. Tested in chrome and firefox.
```
background: color,
```

**Comment by ckweb** [comment]
I'm seeing the white pinhole in Safari, but not in Firefox (Mac).
![image](https://user-images.githubusercontent.com/138840/76996817-91908f80-6928-11ea-9959-4086878b856b.png)

**Comment by casesandberg** [comment]
This has been fixed and will be release in `react-color@2.18.1`
