### ISSUE TITLE
onChangeComplete function that calls setState stops color change

### ISSUE THREAD

**Issue by essencient** [casesandberg/react-color#684]
I have found that when I call setState from a function passed to onChangeComplete the color in the UI reverts to the initial color set when the picker is created even though onChangeComplete as returned the new color. I am using version ^2.17.2

**Comment by Maadtin** [comment]
Is this the same thing that is happening to you? #683 ? :/

**Comment by essencient** [comment]
Yes, Although I think I may have worked out what is happening. When a change to any state causes render() to be called the picker color property as set is reapplied which overrides the newcolor setting of the picker resetting the picker back to the color prop setting.

**Comment by essencient** [comment]
Reading the documentation I think this behaviour is by design. Documentation says '
Color controls what color is active on the color picker. You can use this to initialize the color picker with a particular color, or to keep it in sync with the state of a parent component.'
The latter part suggests that you need to update the value of the color prop with the value provided by the onChangeComplete function call for it not revert to the previous value.

**Comment by casesandberg** [comment]
Correct, yes, you need to pass down the new color value state on every change to keep the color picker in sync with the changes.

**Comment by casesandberg** [comment]
You can see a basic example of it here with hooks, however it would also work with setState: https://github.com/casesandberg/react-color/blob/master/examples/basic-with-react-hooks/src/App.js
