### ISSUE TITLE
Color selection in SketchPicker not representative of mouse click when near bottom edge

### ISSUE THREAD

**Issue by SpaceWarf** [casesandberg/react-color#686]
I ran into an issue with the SketchPicker where whenever I try to select a color near the bottom edge of the picker, the selection is not representative of where the mouse click event occured. This sounds similar to issues #683 and #684, but it's not quite the same thing because the color doesn't revert to its previous state; it seems more random than a simple revert.

I have created a minimal repo with [create-react-app](https://github.com/facebook/create-react-app) that reproduces the bug: https://github.com/SpaceWarf/react-color-test 
As you will see, the SketchPicker is simply enclosed in a `div` and the selected color is managed in the state of the component.
```
import React from 'react';
import { SketchPicker } from 'react-color';
import './App.css';

class App extends React.Component {
    state = {
        selectedColor: undefined
    };

    onChangeColor = (selectedColor, event) => {
        this.setState({ selectedColor });
    }

    render() {
        const { selectedColor } = this.state;
        return (
            <div className="App">
                <h1>Try selecting colors very close to the bottom edge of the picker</h1>
                <h3>Simple clicks and drag actions do not seem to work as expected</h3>
                <SketchPicker
                    width={220}
                    color={selectedColor}
                    onChange={this.onChangeColor}
                />
            </div>
        );
    }
}

export default App;

```

**Comment by casesandberg** [comment]
This is a known issue and it being worked on in the v3.0.0 release under "Base Draggable Component": https://github.com/casesandberg/react-color/issues/413

I am going to close this as we are already tracking it there.
