### ISSUE TITLE
Total JS size is huge

### ISSUE THREAD

**Issue by japgolly** [casesandberg/react-color#687]
Hi! This project looks absolutely beautiful but I just imported `GithubPicker` and `ChromePicker` into my project and my prod-mode output after bundling increased by 143,413 bytes which is huge.

Is this something that will be addressed in #575 ?

**Comment by japgolly** [comment]
Here's a bit more detail about where the size is coming from:

```
react-color                 160.77 KB
lodash                      139.92 KB
tinycolor2                   35.84 KB
reactcss                     12.82 KB
material-colors               5.48 KB
@icons/material               3.18 KB
prop-types                    2.67 KB
```

**Comment by japgolly** [comment]
^^ sizes are unminified btw

**Comment by ricokahler** [comment]
I second this. By doing a quick check on [bundlephobia](https://bundlephobia.com/result?p=react-color@2.18.0), it seems like this package isn't bundled using ES modules.

![image](https://user-images.githubusercontent.com/10551026/78468814-2f39dc00-76e9-11ea-8f19-fdfa14af13d8.png)

[Source](https://bundlephobia.com/result?p=react-color@2.18.0)

You can actually get some very big bundle size wins by:
- supporting tree shaking via an ES6 modules build/bundle. you can do this by creating an ESM bundle and adding the `module` property to the published package.json. [(reference)](https://rollupjs.org/guide/en/#publishing-es-modules)
- bundling with rollup. rollup creates bundles with nice output and supports ESM bundles
- only importing the colors your need from `material-colors`
- removing lodash
- removing tinycolor2 for an internal version (maybe using a [canvas implementation](https://github.com/ricokahler/parse-to-rgba))

None of these have to breaking changes btw. These could be addressed in a minor before 3.x.

Let me know if you're accepting PRs, this is a great lib and I'd happy to contribute!

**Comment by oscarmorrison** [comment]
+1

**Comment by ricokahler** [comment]
@casesandberg @atfzl I would suggest re-opening this (I think it auto closed when the PR merged). Still a bit to go but HUGE improvement 🎉
