### ISSUE TITLE
Make Component mobile/touch friendly

### ISSUE THREAD

**Issue by hisapy** [casesandberg/react-color#69]
Currently, in version "1.3.0", the pickers are not working in mobile.

_Tested in iPhone 6_

**Comment by casesandberg** [comment]
@hisapy digging into this

**Comment by hisapy** [comment]
Thx @casesandberg ... Great job so far!

**Comment by casesandberg** [comment]
I just wanted to confirm: It seems like things like swatches and stuff work on mobile, its just the draggable areas (hue and opacity) that are not working?

**Comment by hisapy** [comment]
Exactly. But unlike other color pickers I've tried, I cannot even touch a point (without dragging) to pick a color.

**Comment by mattbierner** [comment]
Created a simple pull request that fixes the touch problem @hisapy was describing.

The bigger problem in my testing on an iPhone is that the screen scrolls when dragging the sliders, and when touch and dragging to select the saturation. I tried a simple fix by adding lots of `preventDefault` and `stopPropagation` calls in the component event handlers, but that did not work.

**Comment by michaelpeterlee** [comment]
Re: <HuePicker width="100%" /> 

Works on mobile, however the slider button does not move.

**Comment by michaelpeterlee** [comment]
This is still in a 'closed' state. If ignoring, please advise so we can schedule in our development.
