### ISSUE TITLE
Custom color palete

### ISSUE THREAD

**Issue by MarcoFromBerlin** [casesandberg/react-color#691]
Hi everybody!
This plugin looks great and but I just would like to create a picker (I'm using BlockPicker) witha selection of colors.
How can I do this?

Thanks!

**Comment by casesandberg** [comment]
You can check out the API for block picker here: http://casesandberg.github.io/react-color/#api-individual. There is a `colors` prop which you can provide an array of colors:
```
<BlockPicker color={['red', '#aeee00']} />
```

**Comment by marcodisco123** [comment]
great ! thanks!

take care it's `colors`

`<BlockPicker color={['red', '#aeee00']} />`
