### ISSUE TITLE
Custom Color Tooltip

### ISSUE THREAD

**Issue by hgabor995** [casesandberg/react-color#692]
Hi!

I like this plugin, it is absolutely useful.
But I would need to give the colors unique titles.
Can you add support for this (for all Picker just like `<Sketch />`)?

Eg.
```jsx
<CirclePicker colors={[
  { title: 'Red', color: '#f5222d' },
  { title: 'Green', color: '#52c41a' },
  { title: 'Blue', color: '#1890ff' },
]}>
```

It would be best if the title could be ReactNode, but it would be enough to support string
Eg.
```jsx
{ title: <div style={{ color: '#f5222d' }}>Red</div>, color: '#f5222d' }
```

**Comment by casesandberg** [comment]
Unfortunate this is not something we will be able to support directly with a CirclePicker. You can follow the documentation to create your own custom color picker and put your own titles in there!
