### ISSUE TITLE
Formik custom color picker

### ISSUE THREAD

**Issue by alainib** [casesandberg/react-color#693]
i'm trying to create a custom color picker with formik form

the probleme her is that parent component color are not changed : 

    import {SketchPicker} from "react-color";

    export const MyColorPicker = ({label, ...props}) => {
      // with useField is should not use onChange but i get an error without defining it myself
      const [field] = useField(props);
      const [color, setColor] = useState("#333");
      const handleChange = color => {
        setColor(color.hex);
        field.onChange(color.hex);
      };
      const onComplete = color => {
        setColor(color.hex);
        field.onChange(color.hex);
      };
      return (
        <div style={{padding: 10}}>
          <label>{label}</label>
          <SketchPicker {...props} {...field} color={color} onChange={handleChange} onChangeComplete={onComplete} />
        </div>
      );
    };

as exemple this work : 

    export const MyTextAreaField = ({label, ...props}) => {
    const [field, meta] = useField(props);

      if (field && field.value === null) {
        field.value = "";
      }
      return (
        <div style={{display: "flex", flexDirection: "column"}}>
          <label className="MuiFormLabel-root MuiInputLabel-root MuiInputLabel-animated MuiInputLabel-shrink MuiFormLabel-filled">
            {label}
          </label>
          
          <TextareaAutosize
            rows={10}
            {...field}
            {...props}
            style={{marginTop: 10, fontFamily: "Helvetica Neue", fontSize: 15}}
          />
          {meta.touched && meta.error ? <div className="error">{meta.error}</div> : null}
        </div>
      );
    };

and parent code : 

        <Formik
          initialValues={{
            data: { title :'', shortDescription:'', description:'', color:'')
          }}
          onSubmit={values => {
           console.log(values.data) ; // data.color stay null 
          }}>
          <Form>
             <MyTextAreaField id="data.description" name="data.description" label={t("PROJECT.DESCRIPTION")} />
                
             <MyColorPicker id="data.color" label={t("PROJET.COLOR")} name="data.color" />
          </Form>
        </Formik>   
                 

any idea?
thanks

**Comment by LuisDev99** [comment]
Hi, did you figure it out?

**Comment by alainib** [comment]
fixed code with modal who open on click 



`import React, {useState} from "react";
import {useTranslation} from "react-i18next";
import {Fade, Modal, Grid, Button} from "@material-ui/core";

import {makeStyles} from "@material-ui/core/styles";
const useStyles = makeStyles(theme => ({
  modal: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center"
  },
  modalContent: {
    backgroundColor: theme.palette.background.paper,
    boxShadow: theme.shadows[7],
    minHeight: 400,
    margin: 10,
    padding: theme.spacing(2, 4, 3),
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-between"
  }
}));
import {ChromePicker} from "react-color";
export const ColorPicker = ({label, onChange, currentColor}) => {
  const {t} = useTranslation();
  const classes = useStyles();
  const [color, setColor] = useState(currentColor || "#333");
  const [showPicker, setShowPicker] = useState(false);
  const handleChange = color => {
    setColor(color.hex);
  };

  return (
    <div
      style={{display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "center", padding: 10}}>
      <label>{label}</label>
      <div
        style={{
          marginLeft: 20,
          padding: 15,
          paddingLeft: 20,
          paddingRight: 20,
          borderRadius: 3,
          backgroundColor: color
        }}
        onClick={() => setShowPicker(true)}></div>
      {showPicker && (
        <Modal
          className={classes.modal}
          open={showPicker}
          closeAfterTransition
          BackdropProps={{
            timeout: 500
          }}>
          <Fade in={true}>
            <div className={classes.modalContent}>
              <label>{label}</label>
              <div
                style={{
                  backgroundColor: color,
                  marginTop: 10,
                  marginBottom: 10,
                  padding: 40,
                  borderRadius: 3
                }}>
                <ChromePicker color={color} onChange={handleChange} />
              </div>
              <Grid container spacing={10} justify="space-evenly">
                <Grid item xs={12} md={6} align="center">
                  <Button
                    color="inherit"
                    onClick={() => {
                      setShowPicker(false);
                    }}>
                    {t("ACTIONS.CANCEL")}
                  </Button>
                </Grid>
                <Grid item xs={12} md={6} align="center">
                  <Button
                    color="inherit"
                    type="submit"
                    onClick={() => {
                      onChange(color);
                      setShowPicker(false);
                    }}>
                    {t("ACTIONS.SAVE")}
                  </Button>
                </Grid>
              </Grid>
            </div>
          </Fade>
        </Modal>
      )}
    </div>
  );
};

/*
import "rc-color-picker/assets/index.css";
import ColorPicker from "rc-color-picker";
export const MyRCColorPicker = ({label, onChange}) => {
  return (
    <div style={{display: "flex", flexDirection: "row", alignItems: "flex-start", padding: 10}}>
      <span style={{paddingRight: 20}}>{label}</span>
      <ColorPicker color={"#36c"} onChange={obj => onChange(obj.color)}>
        <div className="react-custom-trigger">
          <span style={{paddingLeft: 20, paddingRight: 20}}>{"   "}</span>
        </div>
      </ColorPicker>
    </div>
  );
};*/
`

**Comment by LuisDev99** [comment]
Thank you very much!

**Comment by casesandberg** [comment]
Glad you figured this out!
