### ISSUE TITLE
Error Parsing file when trying to use react-color

### ISSUE THREAD

**Issue by mattvv** [casesandberg/react-color#7]
When including react-color in my project and trying to compile, I get the following:

```
Error: Parsing file /Users/mattvv/Documents/projects/xxx/node_modules/react-color/src/components/Color.jsx: Unexpected token (177:6)
```

I'm using react 0.13.3 and react-color 1.0.0 is there any other dependencies I may be missing?

**Comment by mattvv** [comment]
From what I can tell it looks like it's caused by the following:

https://github.com/andreypopp/reactify#code-in-3rd-party-packages-isnt-being-transformed-by-reactify

I am attempting workarounds now and will see how it goes.

**Comment by mattvv** [comment]
I added -g reactify to my watchify build, and now I get the following errors:

```
Error: Parsing file /Users/mattvv/Documents/projects/xxx/node_modules/react-color/src/components/chrome/ChromeFields.jsx: Redefinition of property (122:2)
Error: Cannot find module 'react-material-design' from '/Users/mattvv/Documents/projects/bark-ui/node_modules/react-color/src/components/swatches'
[Error: write after end]
Error: Cannot find module 'react-material-design' from '/Users/mattvv/Documents/projects/xxx/node_modules/react-color/src/components/material'
[Error: write after end]
Error: Cannot find module 'react-material-design' from '/Users/mattvv/Documents/projects/xxx/node_modules/react-color/src/components/compact'
[Error: write after end]
```

Can you guys publish to NPM using code compiled down to plain ES5 which is runnable in browsers and Node.js as-is.
This would save me from having to compile and find/install all these plugins in my projects build.

**Comment by casesandberg** [comment]
Sorry, yes, I will work on this now @mattvv

**Comment by casesandberg** [comment]
Really sorry @mattvv, I should have done that from the get-go. Just did a pull request which has lib files that are es5 by default and also fixed the broken pathing for some other modules. 

Please update to 1.0.2 via npm!

**Comment by mattvv** [comment]
Thank you for the speedy update! 
I upgraded to 1.0.3 via npm but I'm experiencing the following :(

```
Error: Parsing file /Users/mattvv/Documents/projects/xxx/node_modules/react-color/modules/react-material-design/src/components/Raised.jsx: Unexpected token (71:6)
Error: Parsing file /Users/mattvv/Documents/projects/xxx/node_modules/react-color/modules/react-material-design/src/components/Tile.jsx: Unexpected token (72:6)
[Error: write after end]
Error: Parsing file /Users/mattvv/Documents/projects/xxx/node_modules/react-color/modules/react-material-design/src/components/Tabs.jsx: Unexpected token (191:16)
[Error: write after end]
```

**Comment by casesandberg** [comment]
You mind giving it one more go? I just pushed `react-color@1.0.4` which changes everything over to ES5 so you should have no problems :)

**Comment by mattvv** [comment]
Confirmed working now! Thanks for the speedy response @casesandberg !
