### ISSUE TITLE
Corners Jumping in Saturation Field and Hue

### ISSUE THREAD

**Issue by Wink007** [casesandberg/react-color#701]
this commit doesn't help [Fixes Corners Jumping in Saturation Field #670
](https://github.com/casesandberg/react-color/pull/670/files)
Problem still exists @casesandberg.
Any ideas how to resolve?
![react-color1](https://user-images.githubusercontent.com/28154465/78890354-2856f480-7a6e-11ea-914e-1c3e7e67a09d.gif)

**Comment by lazysergey** [comment]
I see 2 issues here:
1) lower edge **saturation drag** causes **saturation jumps**
2) lower right corner **saturation drag** causes **hue jumps** from very right to very left position

**Comment by Wink007** [comment]
any ideas?

**Comment by joncursi** [comment]
Looks like this problem is sort of addressed in `v2.18.0` (https://github.com/casesandberg/react-color/commit/ca8d1c642c92068ad95d9749fd3673932d65b742), however `v2.18.0` [has problems of its own](https://github.com/casesandberg/react-color/commit/ca8d1c642c92068ad95d9749fd3673932d65b742). :/

**Comment by casesandberg** [comment]
This is a known issue and it being worked on in the v3.0.0 release under "Base Draggable Component": https://github.com/casesandberg/react-color/issues/413

I am going to close this as we are already tracking it there.
