### ISSUE TITLE
GATSBY WEBPACK SSR BUILD ERROR

### ISSUE THREAD

**Issue by AGMETEOR** [casesandberg/react-color#702]
Trying to integrate `Tina CMS` into a gatsby theme called `novela`.

However, due to a package `@icons/material` used in react-color the SSR build fails. It says it can't find some of the icons like `@icons/material/CheckBox` even after I manually install `@icons/material`.

**Comment by anindha** [comment]
This is unrelated to `react-color`. Please refer to [here](https://github.com/narative/gatsby-theme-novela/issues/323#issuecomment-620329183). This issue can be closed.
