### ISSUE TITLE
More props for "swatches" picker

### ISSUE THREAD

**Issue by homaxweb** [casesandberg/react-color#71]
Hi, it would be great to have more opportunities to customize "swatches" (box size, now its set to 320x240, or override all styles like positionCss)

For other types It could be useful to hide some elements of a component (keep hex block in "Material" and hide rgb block)

**Comment by casesandberg** [comment]
Sure! Give me a list of options you would like and I will see if I can get some of them in there. Off the top of my head:

- Change fixed width columns to flexbox so you can provide less colors in each column. 
- Change height and width

As for the material picker, it might be easier for you to just create your own custom picker and remove / add which elements you like. It is really easy, literally just copy this file and modifiy it: https://github.com/meunal/react-color/blob/master/src/components/material/Material.js and then pass that component in to the color picker: <ColorPicker custom={ SimpleHexPicker } />

**Comment by homaxweb** [comment]
Thx for quick reply. I've just started using your component. It's all I need now, but later I'll complement the list probably.

**Comment by casesandberg** [comment]
Cool!

What size do you intend to use it at? And how many colour columns do you want to use? Just so I can make sure it looks good that way when developing it.

**Comment by homaxweb** [comment]
Current number of columns is enough, and I'd like to have 2 options: horizontal (6-7 columns per row) and vertical (3 columns per row)

**Comment by casesandberg** [comment]
@homaxweb You can now declare height and width on the picker with `react-color@1.3.2`! So for 7 across you can do:
```
<ColorPicker type="swatches" width="372" height="240" />
```
And for 3 columns per row you can do:
```
<ColorPicker type="swatches" width="172" height="300" />
```
