### ISSUE TITLE
White circle indicator is not following the cursor when dragging the color

### ISSUE THREAD

**Issue by rnwathon** [casesandberg/react-color#725]
Hai, this is my first time using the component. 

When I tried to import and use the component (without giving it any props), the white circle and the slider (hue & alpha) is not responding to my click-drag movement.

```
import React from 'react'
import { ChromePicker } from 'react-color'

class Color extends React.Component {
  render(){
    <ChromePicker />
  }
}
```

Then I tried to give it the props:

```
import React from 'react'
import { ChromePicker } from 'react-color'

class Color extends React.Component {
  state = {
    color: "#ffffff"
  }

  onChange = color => {
    console.log(color.hex)
    this.setState({
      color: color.hex
    })
  }

  render(){
    <ChromePicker 
        color={this.state.color} 
        onChange={this.onChange} />
  }
}
```

Then I found out:
1. When I just console.log the color.hex (without setState), the event actually works. It logging all color value when I click-drag around but the indicator just not following the cursor.

2. When I added the setState, the event is no longer working onChange (click-drag). It only works when I just **click** the color area and then the white circle is moved to that spot (I assume this is because of the color props)

I tested SketchPicker, PhotoshopPicker, and ChromePicker in create-react-app with **React version "^16.13.1"** and **Chrome Version 83.0.4103.61.**

**Comment by rnwathon** [comment]
I'm closing this issue since it is already resolved after quite some times debugging

**Comment by koentjev** [comment]
hi rnwathon, I am experiencing the exact same problem. Can you explain what you did to resolve this issue?

**Comment by tiagocdr** [comment]
Would have been nice if you posted the solution that worked for you.

**Comment by spacedogstudios** [comment]
@tiagocdr with the useState hook, you do something like this:

```
const [pickerColor, setPickerColor] = React.useState('#000000');

<ChromePicker
  color={pickerColor}
  onChange={color => {
    setPickerColor(color.hex);
  }}
/>
```
