### ISSUE TITLE
How to make SketchPicker auto-close when clicking outside the picker window?

### ISSUE THREAD

**Issue by ankitkanojia** [casesandberg/react-color#732]
Hi there,

You're doing great, keep it up!!

I just have one concern related to auto close functionality using SketchPicker, currently I've integrated everything on my end but can not able to make auto close functionality on clicking of outside of picker. Have research on it and even tried few options but can not able to get succeeded, therefor I've come up to you.

Can you please guide me or share me the reference link so that my issue get resolved.

Thank you

**Comment by zeeshanjan82** [comment]
@ankitkanojia you need to display the color picker in popover format, check the first example in this page: https://casesandberg.github.io/react-color/

**Comment by ankitkanojia** [comment]
Yeah great, this is what i want. Thank you so much for your support.
