### ISSUE TITLE
Cannot resolve 'file' or 'directory' ./sketch/Sketch

### ISSUE THREAD

**Issue by ron116** [casesandberg/react-color#75]
I found directory ./sketch and him name contains first char is capital. Linux OS  are dependent registers, and I have some trouble.
![2016-01-19 11 21 45](https://cloud.githubusercontent.com/assets/8145548/12413355/50ffdcf6-be9f-11e5-8815-8732f71d41af.png)

In repository https://github.com/casesandberg/react-color/tree/master/lib/components all right.

What you thing about this? 

On Windows all right) because windows are not dependent of registers.

**Comment by zivester** [comment]
Yes I believe this was introcued [here](https://github.com/casesandberg/react-color/commit/8e1f43dfb97d9920bba8eea4b0a5e682cf320e68#diff-c491f2fa48a3eb9b9a2e3a33f4c7c689R39)

**Comment by ron116** [comment]
Can I something do about it? or you correct?

**Comment by casesandberg** [comment]
Ah, I don't have my gulp process clearing out that directory on every build, that is the issue. I will have this fixed within the hour

**Comment by casesandberg** [comment]
Sorry about that guys. Just pushed out a fix for this `react-color@1.3.3`

I have gulp cleaning out that directory now before it compiles new code into it, so we shouldnt run into this issue in the future!
