### ISSUE TITLE
how to build this thing? 

### ISSUE THREAD

**Issue by zilahir** [casesandberg/react-color#759]
I would like to test my extended features in my fork repo. 

doing `npm prepublish`

Trying to build it (with the default babel config), then: 

`Uncaught Reference Error: exports is not defined`

if i change the babel config to

```
{
  "presets": [
    "@babel/env",
    "@babel/preset-react"
  ]
}

```

getting `SyntaxError: /Users/richardzilahi/zilahir/react-color/src/Alpha.js: Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled (1:8):`. 

So, what is the hidden magic way to get a build version out of this thing? :) 

Thank you!

**Comment by atfzls** [comment]
Can you give more details.
I just tried cloning it fresh and running `npm install` and `npm run prepublish` and it is working.

**Comment by zilahir** [comment]
oh with the original config the build works for me too, but when i want to use it within an other project as: 

```
import { SketchPicker } from 'react-color'

<SketchPicker />
```

then the error is the one i mentioned: 

![image](https://user-images.githubusercontent.com/6687149/91812663-26b6e480-ec3a-11ea-9250-3b9c54c09edf.png)

I have created a demo repo: 

https://github.com/zilahir/react-color

**Comment by atfzl** [comment]
You are trying to use `@babel/x` plugins and presets in your fork. 
These are only supported for the latest version of babel which is 7 I think.
We are using babel 6 in this project.

**Comment by zilahir** [comment]
@atfzl i got that, the only problem, what with the initial settings, i am getting the error i sent the screenshot about. 

that what happens, if i build with the provided babel settings. :((

**Comment by zilahir** [comment]
ok, i solved the problem, the entire babel configuration needed to be updated, also the `use-module-babelrc.js` now i am able to build it as it supposed to work :)
