### ISSUE TITLE
2.19 release

### ISSUE THREAD

**Issue by bobbysciacchitano** [casesandberg/react-color#764]
Hello, would it be possible to get a 2.19 release to NPM so we can get access to the transparency fixes?

Thanks.

**Comment by pkmnct** [comment]
@casesandberg Yes, I'd like to get 2.19 for the input label improvements for accessibility. It seems to be released on GitHub but not npm.

**Comment by marywhite** [comment]
Any updates on this?

**Comment by casesandberg** [comment]
Just released `react-color@2.19.1`

**Comment by marywhite** [comment]
Thanks!
