### ISSUE TITLE
Tree shaking isn't working

### ISSUE THREAD

**Issue by Charlie91** [casesandberg/react-color#782]
This library weights around 178kb in my production bundle and that is pretty much.
I've found that despite I import only one picker in my code, my bundle has sources of all of them and this is sad.
any workarounds with this? I use Webpack 4.

**Comment by atfzl** [comment]
Can you share a repository where this can be reproduced.

**Comment by Charlie91** [comment]
@atfzl,  sure, try it
https://github.com/Charlie91/react-starter-boilerplate-hmr

**Comment by Charlie91** [comment]
Well, I've made some research and found the solution that works perfect.
Here is the PR #784

**Comment by atfzl** [comment]
Fixed by #784. Thanks @Charlie91.

**Comment by SuperIRis** [comment]
Hello! This fix works, however it has not been published to NPM, would you mind publishing it so the dependencies get updated and the fix can be used?
