### ISSUE TITLE
a "source" key in the `onChange` color object

### ISSUE THREAD

**Issue by chriddyp** [casesandberg/react-color#81]
Love this project, many thanks!

I'm displaying a color swatch and string next to my color picker: 
![image](https://cloud.githubusercontent.com/assets/1280389/12538468/1efe86dc-c2a8-11e5-9beb-18f814837aed.png)

I'd like to be able to display the color string in the format of the most recently updated input box.

![image](https://cloud.githubusercontent.com/assets/1280389/12538494/ba47f3a8-c2a8-11e5-94bd-069cb9c85921.png)

For example, if the user entered the color in the RGB input box, I'd like to display the color as `rgb(25, 77,  51)`.

Or, if they edited the hex box last, then I'd like to display the color in hex `#194D33`.

Is this in the scope of the project? I'm happy to contribute if so!

**Comment by casesandberg** [comment]
This is definitely in the scope of the project. I dont have time to work on it right now, but if you want to dig in and have each of the components pass that up be my guest!

**Comment by casesandberg** [comment]
Fixed in `react-color@1.3.8`
