### ISSUE TITLE
Bug: Alpha component is not working with Chrome Color Picker

### ISSUE THREAD

**Issue by liuliangsir** [casesandberg/react-color#814]
As the above title says, I can not drag chrome pointer inside Alpha component. I find that the demo [here](http://casesandberg.github.io/react-color/) is working. I create a small [demo](https://codesandbox.io/s/modest-shape-t06g2) to reproduce the issue above.

**Comment by commuteandassosciate** [comment]
Hey, I have received the same issue. What did you do to resolve it?

**Comment by commuteandassosciate** [comment]
I received the same issue - how did you fix it?

**Comment by raunicorn** [comment]
Is this problem solved?
