### ISSUE TITLE
Guide/Tutorial how to make my own version of picker

### ISSUE THREAD

**Issue by michaltaberski** [casesandberg/react-color#83]
Hey,

I can't find any guide how to assemble my own version of color picker. Could I ask you for any hint at this issue?

**Comment by casesandberg** [comment]
I dont have a guide at the moment, but I will put it on my list of things to do to put one together. If you take a look in `src` you can see each of the color pickers, those are essentialy just custom color pickers. You can steal one of those as a starting point and go from there!
