### ISSUE TITLE
Case-sensetive folder name breaks on Linux

### ISSUE THREAD

**Issue by alexander-daniel** [casesandberg/react-color#84]
Hey again! 

I'm running into a really odd issue. 

`v1.3.5`

I can see that the `lib/components/sketch` here has `'sketch'` as lower-case:
https://github.com/casesandberg/react-color/tree/master/lib/components

And the import of that component is made with lower-case:
https://github.com/casesandberg/react-color/blob/master/lib/components/SketchPicker.js#L35

**However**! When `npm` installing (`npm i react-color@1.3.5`), I noticed that the folder has an **uppercase** first letter. This won't cause any problems on OSX, however Linux *is* case-sensitive, so we get the following when trying to build/bundle on our CI servers (running Ubuntu):

```bash
Error: Cannot find module './sketch/Sketch' from '/myproject/node_modules/react-color/lib/components'
```

It seems to be searching for the lower-case, but I SSH'd into the test-box and saw this:
<img width="818" alt="screen shot 2016-01-26 at 11 10 53 am" src="https://cloud.githubusercontent.com/assets/5408720/12586296/b621db74-c41d-11e5-9216-2819d1045ae0.png">

So perhaps you're publishing from your local repo and the directory name has an uppercase? Not too sure how there could be sync issues between the github repo and the npm package, as cloning this repo works just fine and the folders are all appropriately-cased.

It is *only* when you `npm i react-color` that this issue occurs. 

Any ideas? Thanks for your time!

**Comment by mdoelker** [comment]
I can confirm this behaviour starting version 1.3.5.

**Comment by benjie** [comment]
Try:
```
git config core.ignorecase false
```

**Comment by liesislukas** [comment]
i have same issue. Moved project from os x to ubuntu and it broke.

**Comment by asaldivar** [comment]
+1

**Comment by tamagokun** [comment]
Have been running into this as well!

**Comment by vramana** [comment]
Can this be problem with npm ??

**Comment by ninoperin** [comment]
same problem here when deploying on debian. i think it's a problem with npm too. when cloning the repo from github everythink looks fine. when installing via npm the sketch folder is still uppercase.

**Comment by casesandberg** [comment]
Ah, this bug drove me insane a few months ago. I have completely renamed the folder so we shouldnt run into any more issues!

Update to `react-color@1.3.6`

**Comment by ghostCoder** [comment]
Can anyone confirm if `react-color@1.3.6` fixed this issue?
I am still getting it with `react-color@1.3.6`...

**Comment by alexander-daniel** [comment]
@ghostCoder Can confirm it's working for me with `1.3.6`
