### ISSUE TITLE
Cannot make this work

### ISSUE THREAD

**Issue by essekia** [casesandberg/react-color#87]
Noob here. 

`define(['react', 'es6!vendor/react-color/src/components/ChromePicker'], function(React, ColorPicker) {`
For some reason I cannot make this work. When I include it, I get the following error:

**Uncaught Error:** Module name "components/Color" has not been loaded yet for context: _. Use require([])

Is the process to include this in a requireJS setup different than with commonJS?

And if I include the ChromePicker directly, then the imported files have path point from the root js file. instead of the relative paths.

Can you also explain if these paths have to be registered in the requireJS's main js file?

```
import React from 'react';
import ReactCSS from 'reacts';
import merge from 'merge';
import isPlainObject from 'lodash.isplainobject';
import debounce from 'lodash.debounce';
import color from '../helpers/color';

import Chrome from './chrome/Chrome';
```

**Comment by casesandberg** [comment]
Hmm. Can you explain your setup a little more, I am not sure what you are asking?
