### ISSUE TITLE
Unexpected Reserved word

### ISSUE THREAD

**Issue by MFIMichael** [casesandberg/react-color#9]
>ERROR in ./~/react-color/src/components/Color.jsx
>Module parse failed: S:\GitHub\MyFlock\node_modules\react-color\src\components\Color.jsx Line 35: >Unexpected reserved word
>You may need an appropriate loader to handle this file type.
>| };
>|
>| class ColorPicker extends ReactCSS.Component {
>|
>|   constructor(props) {
> @ ./~/react-color/src/index.js 2:17-50

All I did was install and place the component as 
```<ColorPicker type="slider" />```

On react 0.13.3

**Comment by MFIMichael** [comment]
Should note I do have jsx-loader (0.13.1) and babel-loader (5.1.4) in my project.

**Comment by MFIMichael** [comment]
overlooked that I had an exclude on node_modules for my jsx loader. When I removed that, it made it through and then hit the following in Compact, Swatches, and Material. 

>Cannot resolve module 'react-material-design'

node manager can't find the repo, and google searching has not revealed it. Doesn't look like it's included with material-ui, so not sure where to get it?

**Comment by MFIMichael** [comment]
Thanks for the quick fix! Latest version results in the following for me.

>ERROR in ./~/react-color/src/index.js
>Module not found: Error: Cannot resolve 'file' or 'directory' ./components/Color in >S:\GitHub\MyFlock\node_modules\react-color\src
> @ ./~/react-color/src/index.js 3:17-46

**Comment by casesandberg** [comment]
That's my bad @MFIMichael, I was a bit too liberal with aliasing in Webpack so I went ahead and fixed all the pathing within the modules in the newest update. 

Updating to 1.0.2 via npm should do the trick!

**Comment by MFIMichael** [comment]
On version 1.0.2, now, and getting the following:

>ERROR in ./~/react-color/modules/react-material-design/index.js
>Module not found: Error: Cannot resolve 'file' or 'directory' ./src/components/Raised in >S:\GitHub\MyFlock\node_modules\react-color\modules\react-material-design
> @ ./~/react-color/modules/react-material-design/index.js 4:10-44
>
>ERROR in ./~/react-color/modules/react-material-design/index.js
>Module not found: Error: Cannot resolve 'file' or 'directory' ./src/components/Tile in >S:\GitHub\MyFlock\node_modules\react-color\modules\react-material-design
> @ ./~/react-color/modules/react-material-design/index.js 5:8-40
>
>ERROR in ./~/react-color/modules/react-material-design/index.js
>Module not found: Error: Cannot resolve 'file' or 'directory' ./src/components/Tabs in >S:\GitHub\MyFlock\node_modules\react-color\modules\react-material-design
> @ ./~/react-color/modules/react-material-design/index.js 7:8-40

**Comment by MFIMichael** [comment]
#12 - From v1.0.3

>ERROR in ./~/react-color/modules/react-material-design/src/components/Raised.jsx
>Module parse failed: S:\GitHub\MyFlock\node_modules\react-color\modules\react-material-design\src\components\Raised.jsx Line 7: Unexpected reserved word
>You may need an appropriate loader to handle this file type.
>| var ReactCSS = require('reactcss');
>|
>| class Raised extends ReactCSS.Component {
>|
>|   classes() {
> @ ./~/react-color/modules/react-material-design/index.js 2:10-48
>
>ERROR in ./~/react-color/modules/react-material-design/src/components/Tile.jsx
>Module parse failed: S:\GitHub\MyFlock\node_modules\react-color\modules\react-material-design\src\components\Tile.jsx Line 7: Unexpected reserved word
>You may need an appropriate loader to handle this file type.
>| var ReactCSS = require('reactcss');
>|
>| module.exports = class Tile extends ReactCSS.Component {
>|
>|   classes() {
> @ ./~/react-color/modules/react-material-design/index.js 3:8-44
>
>ERROR in ./~/react-color/modules/react-material-design/src/components/Tabs.jsx
>Module parse failed: S:\GitHub\MyFlock\node_modules\react-color\modules\react-material-design\src\components\Tabs.jsx Line 18: Unexpected reserved word
>You may need an appropriate loader to handle this file type.
>| // }
>|
>| class Tabs extends ReactCSS.Component {
>|
>|   constructor(props) {
> @ ./~/react-color/modules/react-material-design/index.js 5:8-44

**Comment by MFIMichael** [comment]
This happens if there is an exclude on the node_modules folder, which I think is fairly common?

**Comment by casesandberg** [comment]
Ah yes, that is fairly common. I just pushed `react-color@1.0.4` which changes the entire repo over to ES5 so it will work without having to take out that exclude!
