### ISSUE TITLE
How to make disappear overflowY & borders when using SwatchesPicker

### ISSUE THREAD

**Issue by ekaradon** [casesandberg/react-color#90]
Hello,

I am looking for a solution in order to remove the css properties `overflow-y` and `border` but also `box-shadow` from SwatchesPicker but I cannot find a way to do this. 
Below what I am always getting:
![spectacle s23123](https://cloud.githubusercontent.com/assets/9439390/12956289/9b4910fe-d027-11e5-9aa1-44611a937e9c.png)

Is there a way to do it through props? Do I have to implement a custom color picker? 

Anyway, thanks a bunch for this awesome component!

**Comment by casesandberg** [comment]
Probably best to just make your own custom picker. You can copy the entire picker from `src/components/swatches` and then tweak any of the styles there!
