### ISSUE TITLE
Exception when moving to the lastest version (1.2.1 to 1.3.7)

### ISSUE THREAD

**Issue by ThePainnn** [casesandberg/react-color#92]
Hi, I was updating our dependencies. We have a new exception each time we render a ColorPicker:

> Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of 

This is React 0.14.7

Code: 

```
var ColorPicker = require('react-color');

<ColorPicker
                    type             = "sketch"
                    position         = "below"
```

Since ColorPicker is an object. By checking it, I found a workaround:  <ColorPicker.default , which is a function and work as expected.

I wonder if we are doing something wrong.

Thanks.

**Comment by casesandberg** [comment]
Ah, sorry about that @ThePainnn, the lib is in a state of flux as I am upgrading things and I didnt mean for this to happen. For now if you deconstruct the import like this: 
```
var { ColorPicker } = require('react-color');
```
Or use ES6 import:
```
import ColorPicker from 'react-color';
```
This will be fixed with the new minor version I am introducing shortly.
