### ISSUE TITLE
Using 'display' displays the Color Picker outside of viewport

### ISSUE THREAD

**Issue by fabianfett** [casesandberg/react-color#93]
I tried to stay as close as possible to the example at http://casesandberg.github.io/react-color/#usage-display to display the picker depending on the current state.

```javascript
import React from 'react';
import ColorPicker from 'react-color';

class ColorButton extends React.Component {

  constructor(props) {
    super(props);

    this.state = {
      displayColorPicker: false
    };
    this.handleClick = this.handleClick.bind(this);
  }

  handleClick() {
    this.setState({ displayColorPicker: !this.state.displayColorPicker });
  }

  render() {
    return (
      <div>
        <button onClick={ this.handleClick }>Pick Color</button>
        <ColorPicker
          display={ this.state.displayColorPicker }
          onClose={ this.handleClick }
        />
      </div>
    );
  }
}

export default ColorButton;
```

Though I noticed that the color picker is always displayed outside the normal viewport. The direction is depending on the `position` attribute. Since I use the Foundation Framework for styling, I disabled all external loaded css, which means that the only remaining css is react-color's, to eliminate possible side effects. I even put my ColorButton in my RootComponent and disabled all other components. Though the problem persisted.

Also this problem occurred in Safari, Chrome and Firefox. Do the external divs need any special css treatment? How can I make this work?

**Comment by elrumordelaluz** [comment]
Since `<ColorPicker>` renders as an `absolute` positioned Element, takes the nearest ancestor that has position defined as a reference (position should be any value other than `static`). 
This allows you control the position of the `ColorPicker` (through `props` or any other way) but I think it would be useful to include an advice in the Documentation.

In your case, this little change should work:
```js
render() {
    return (
      <div style={{ position: `relative` }}>
        <button onClick={ this.handleClick }>Pick Color</button>
        <ColorPicker
          display={ this.state.displayColorPicker }
          onClose={ this.handleClick }
        />
      </div>
    );
  }
```

**Comment by casesandberg** [comment]
Yes, sorry this is a little confusing. I am currently working on the next major version of this package and there will be a clear separation of hiding and showing the color picker. In the mean time I will definitely add the position relative wrapper to the docs.

**Comment by fabianfett** [comment]
Thanks so much. This fixed it! Shall this issue stay open?

**Comment by casesandberg** [comment]
I am going to close it and open a new one for better documentation.

**Comment by casesandberg** [comment]
https://github.com/casesandberg/react-color/issues/94
