### ISSUE TITLE
ColorPicker causing binding issue.

### ISSUE THREAD

**Issue by ZephyrXero** [casesandberg/react-color#98]
When I include the ColorPicker component within one of my own components, it is somehow causing React to lose it's ref to the parent of my component. This causes event bindings to break, and the parent component doesn't even show up in the React View tool. I'm not sure why, but removing the ColorPicker made everything work again for me.

I am developing with ES6/Babel, so I wonder if that could be part of the conflict?

Sample code of how I was using it:
```
class ColorSelector extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      color: this.props.color,
      showPicker: false
    };
    this.togglePicker = this.togglePicker.bind(this);
    this.updateHexColor = this.updateHexColor.bind(this);
  }
  togglePicker() {
    this.setState({ showPicker: !this.state.showPicker });
  }
  updateHexColor(event) {
    this.setState({ color: event.target.value });
  }
  render() {
    return (
      <div className='color-selector'>
        <input type='text' id={this.props.id} className='hex-value' value={this.state.color} onChange={this.updateHexColor} />
        <button type='button' className='picker-button' onClick={this.togglePicker}>
          <div className='swatch' style={{ backgroundColor: this.state.color }} />
          <ColorPicker key={'picker-' + this.props.id} type='sketch' position='below' display={this.state.showPicker} color={this.state.color} />
        </button>
      </div>
    );
  }
}
```

**Comment by casesandberg** [comment]
Im not sure if I understand exactly. I don't see a ref here: `<div className='color-selector'>`

**Comment by ZephyrXero** [comment]
It's not my color-selector that's losing the ref, but the parent component I'm putting it inside of.

**Comment by detky** [comment]
I had the same situation. If you place the picker inside an own component, some things dont work anymore. In my case, not only bindings were gone, all parameters were also ignored (display={true} type="compact").
@ZephyrXero, for me the solution was to go back to 1.3.8

Regards
